### ISSUE TITLE
non-latin text is not aligned

### ISSUE THREAD

**Issue by beviah** [lhotse-speech/lhotse#1046]
i.e. arabic, russian, etc. 

text field in response has valid non-latin transcript, yet there are no alignments.

**Comment by pzelasko** [comment]
Can you provide more context?

**Comment by beviah** [comment]
```
from lhotse import CutSet, RecordingSet, align_with_torchaudio, annotate_with_whisper
recordings = RecordingSet.from_dir(fld, pattern="*.wav")
cuts = annotate_with_whisper(recordings, device='cuda', language='ar')
cuts_aligned = align_with_torchaudio(cuts)
for cut in cuts_aligned:
    alignments = cut.supervisions
```
    
word alignments are always empty for texts of non-latin scripts, as if no text was detected.

**Comment by pzelasko** [comment]
You’d need an ASR model that supports your target language. You can check if there’s one available in torchaudio: https://pytorch.org/audio/stable/pipelines.html

Otherwise you’d need to train or fine tune your own. You can also try word alignments from faster whisper (unmerged yet in #1017).

**Comment by beviah** [comment]
Awesome! it works, thanks!
