### ISSUE TITLE
Fbank calculation cost too much space

### ISSUE THREAD

**Issue by OswaldoBornemann** [lhotse-speech/lhotse#1063]
I have almost 40,000 hours of audio data, including wenetspeech. I split the `cuts_train_raw.jsonl.gz`, which is saved with speed perturbation, into almost 13,000 `cuts_train_raw.id.jsonl.gz`. However, i found that during the fbank calculation process, the space has almost exceed 2T. However, i could not provide the space out of 2T, so how to solve this problem ?

**Comment by desh2608** [comment]
If you don't have sufficient storage, you may have to switch to "on-the-fly" feature extraction during the model training.

**Comment by danpovey** [comment]
Lately we have been disabling the speed perturbation, because it turns out that if you use SpecAugment the speed perturbation does not help.
