### ISSUE TITLE
Supervision and feature frame size mismatch

### ISSUE THREAD

**Issue by rouseabout** [lhotse-speech/lhotse#1064]
For some specific entries in my dataset, I observse a mismatch of between supervision duration and actual audio samples passed to the feature extractor. The mismatch is very small, equating to one or two samples, but is enough to cause an additional feature frame to be allocated. During training, icefall/utils.py fails with an assertion because the audio in frame size (computed from audio samples) does not match the supervision frame size (computed from supervision duration).

```
def filter_uneven_sized_batch(batch: dict, allowed_max_frames: int):
[...]
	assert T == supervisions["num_frames"].max(), (T, supervisions["num_frames"].max())
```

This mismatch can occur in two places. I am curious what the best solution is.

**Mismatch 1: CutSet.trim_to_supervisions() with supervision durations that do not compute to a round number of samples**

My dataset has some supervision durations (in seconds) that do not compute to a round number of samples at the original recording sample rate. When trim_to_supervisions() is called, add_durations() is used to recalculate the cut duration. The new duration is calculated by converting the supervision duration(s) from seconds to samples (with ROUND_HALF_UP), adding then up, and then converting back to seconds.

Worked example using atcosim_zf1_02_120_000000_000107:

- 	supervision duration: 3.7249687 seconds (119198.9984 samples at 32000 kHz)

After trim_to_supervisions() 

- 	cut duration: 3.72496875 seconds (119199 samples at 32000 kHz)

If we resample to 16000 and calculate frame size for 10ms window:

- 	supervision frames: 372 frames  (`compute_num_frames(3.7249687, 0.01 ,16000)`)
- 	feature frames:  373 frames (`compute_num_frames(3.72496875, 0.01 ,16000)`)

Solutions?:

- 	During the prepare phase of the recipe, fix problematic segment duration values so they calculate to a round number of samples.

**Mismatch 2: MonoCut.load_audio() optimization**

commit e4c5cf97f introduces the optimization:

```
                # set duration=None when cut covers the whole recording
                # to let the audio loading code "know" to read everything
                duration=self.duration
                if not math.isclose(
                    self.duration, self.recording.duration, abs_tol=1e-3
                )
                else None,
```

Even with 10^-3 tolerance, the number of samples returned by load_audio() is sometimes sufficiently different to cause an extra feature frame to be allocated.

Worked example using “atcosim_sm4_05_025_000000_000553”:

- 	recording duration = 5.53496875 seconds (177119 samples at 32000 Hz)
- 	supervision duration = 5.5349375 seconds (177118 samples at 32000 Hz)

	
After trim_to_supervisions():

- 	cut duration = 5.5349375 seconds (177118 samples at 32000 Hz)
- 	here load_audio() does not optimize and returns 177118 samples, matching the supervision duration

After resample(16000):

- 	cut duration = 5.5349375 (88559 samples at 16000 Hz)
- 	recording duration = **5.535** (88560 samples at 16000 Hz)
- 	supervision duration = 5.5349375 (88559 samples at 16000 Hz)
- 	here load_audio() optimizes, and returns 88560 samples, no longer matching the supervision duration
- 	supervision frames: 554 frames  (`compute_num_frames(5.535, 0.01 ,16000)`)
- 	feature frames:  553 frames (`compute_num_frames(5.5349375, 0.01 ,16000)`)

Solutions?

- Consider reverting commit e4c5cf97f
- Improve optimization to consider window size in the threshold calculation

**Comment by pzelasko** [comment]
Thanks for a detailed description!

For case 1, it's best to fix the supervision information.

Case 2 would only be triggered when the optimization can in fact kick in and load the whole recording. The reason you had this issue is because the supervision segment is shorter by one sample, you called `.trim_to_supervisions()`, and got a cut that was only one sample shorter. I think in your case this problem will disappear once supervision segments have correct duration with no further code changes needed.

**Comment by pzelasko** [comment]
... but technically, we could fix case 2 by computing what's the expected number of samples based on cut duration and truncate the loaded audio to match that.

**Comment by pzelasko** [comment]
Closing via #1071
