### ISSUE TITLE
Inconsistent number of samples in a MixedCut

### ISSUE THREAD

**Issue by osadj** [lhotse-speech/lhotse#1074]
Hello,

Noise and reverb augmentation with MixedCut both fail. Please see below for more details. 

`AssertionError: Inconsistent number of samples in a MixedCut: please report this issue at https://github.com/lhotse-speech/lhotse/issues showing the cut below. MixedCut:
MixedCut(id='55404f53-d33e-fc58-dcfe-1e0cfa9ab0f6', tracks=[MixTrack(cut=MonoCut(id='c084d2f5-daf8-10ad-ea1d-489c366ce909', start=0.0, duration=8.49, channel=0, supervisions=[SupervisionSegment(id='eq7B0SNL5YQ__U__S0_eq7B0SNL5YQ__U__S0---0019.210-0027.700_000000-000849', recording_id='eq7B0SNL5YQ__U__S0---0019.210-0027.700', start=0.0, duration=8.49, channel=0, text='transcript not available', language='sl', speaker='eq7B0SNL5YQ__U__S0', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='eq7B0SNL5YQ__U__S0---0019.210-0027.700', sources=[AudioSource(type='file', channels=[0], source='../voxlingua107/train/sl/eq7B0SNL5YQ__U__S0---0019.210-0027.700.wav')], sampling_rate=16000, num_samples=135840, duration=8.49, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='bc4ffd31-eebe-9372-34e7-f417722ab629', start=0.0, duration=18.45, channel=0, supervisions=[], features=None, recording=Recording(id='noise-free-sound-0820', sources=[AudioSource(type='file', channels=[0], source='../musan/noise/free-sound/noise-free-sound-0820.wav')], sampling_rate=16000, num_samples=295214, duration=18.450875, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=16.49884437779523)], transforms=None)
[extra info] When calling: MixedCut.load_audio(args=(MixedCut(id='55404f53-d33e-fc58-dcfe-1e0cfa9ab0f6', tracks=[MixTrack(cut=MonoCut(id='c084d2f5-daf8-10ad-ea1d-489c366ce909', start=0.0, duration=8.49, channel=0, supervisions=[SupervisionSegment(id='eq7B0SNL5YQ__U__S0_eq7B0SNL5YQ__U__S0---0019.210-0027.700_000000-000849', recording_id='eq7B0SNL5YQ__U__S0---0019.210-0027.700', start=0.0, duration=8.49, channel=0, text='transcript not available', language='sl', speaker='eq7B0SNL5YQ__U__S0', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='eq7B0SNL5YQ__U__S0---0019.210-0027.700', sources=[AudioSource(type='file', channels=[0], source='../voxlingua107/train/sl/eq7B0SNL5YQ__U__S0---0019.210-0027.700.wav')], sampling_rate=16000, num_samples=135840, duration=8.49, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='bc4ffd31-eebe-9372-34e7-f417722ab629', start=0.0, duration=18.45, channel=0, supervisions=[], features=None, recording=Recording(id='noise-free-sound-0820', sources=[AudioSource(type='file', channels=[0], source='../musan/noise/free-sound/noise-free-sound-0820.wav')], sampling_rate=16000, num_samples=295214, duration=18.450875, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=16.49884437779523)], transforms=None),) kwargs={})`

And for reverb and noise augmentation:

`AssertionError: Inconsistent number of samples in a MixedCut: please report this issue at https://github.com/lhotse-speech/lhotse/issues showing the cut below. MixedCut:
MixedCut(id='d034760f-833f-3b7f-150f-9a1d3401c6c6_rvb', tracks=[MixTrack(cut=MonoCut(id='c19330dd-884b-140f-dfca-4e9965ebf67b', start=0.0, duration=10.78, channel=0, supervisions=[SupervisionSegment(id='fj3nR9ZX1Ew__U__S3_fj3nR9ZX1Ew__U__S3---2803.610-2814.390_000000-00
1078', recording_id='fj3nR9ZX1Ew__U__S3---2803.610-2814.390', start=0.0, duration=10.78, channel=0, text='transcript not available', language='fr', speaker='fj3nR9ZX1Ew__U__S3', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='fj3nR9ZX1Ew
__U__S3---2803.610-2814.390', sources=[AudioSource(type='file', channels=[0], source='../voxlingua107/train/fr/fj3nR9ZX1Ew__U__S3---2803.610-2814.390.wav')], sampling_rate=16000, num_samples=172480, duration=10.78, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='26fa9ea1-9c66-d317-ab95-410753e6d6a3', start=0.0, duration=10.78, channel=0, supervisions=[], features=None, recording=Recording(id='noise-free-sound-0469', sources=[AudioSource(type='file', channel
s=[0], source='../musan/noise/free-sound/noise-free-sound-0469.wav')], sampling_rate=16000, num_samples=172488, duration=10.7805, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=17.290758494598506)], transforms=[{'name': 'Reve
rbWithImpulseResponse', 'kwargs': {'rir': {'id': 'medium-Room006-00052', 'sources': [{'type': 'file', 'channels': [0], 'source': '../rir/simulated_rirs/mediumroom/Room006/Room006-00052.wav'}], 'sampling_rate': 16000, 'num_samples': 16000, 'duration': 1.0, 'ch
annel_ids': [0], 'transforms': None}, 'normalize_output': True, 'early_only': False, 'rir_channels': [0], 'rir_generator': None, 'RIR_SCALING_FACTOR': 3.0517578125e-05}}])
[extra info] When calling: MixedCut.load_audio(args=(MixedCut(id='d034760f-833f-3b7f-150f-9a1d3401c6c6_rvb', tracks=[MixTrack(cut=MonoCut(id='c19330dd-884b-140f-dfca-4e9965ebf67b', start=0.0, duration=10.78, channel=0, supervisions=[SupervisionSegment(id='fj3nR9ZX1Ew__U
__S3_fj3nR9ZX1Ew__U__S3---2803.610-2814.390_000000-001078', recording_id='fj3nR9ZX1Ew__U__S3---2803.610-2814.390', start=0.0, duration=10.78, channel=0, text='transcript not available', language='fr', speaker='fj3nR9ZX1Ew__U__S3', gender=None, custom=None, alignment=None)
], features=None, recording=Recording(id='fj3nR9ZX1Ew__U__S3---2803.610-2814.390', sources=[AudioSource(type='file', channels=[0], source='../voxlingua107/train/fr/fj3nR9ZX1Ew__U__S3---2803.610-2814.390.wav')], sampling_rate=16000, num_samples=172480, dura
tion=10.78, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='26fa9ea1-9c66-d317-ab95-410753e6d6a3', start=0.0, duration=10.78, channel=0, supervisions=[], features=None, recording=Recording(id='noise-free-s
ound-0469', sources=[AudioSource(type='file', channels=[0], source='../musan/noise/free-sound/noise-free-sound-0469.wav')], sampling_rate=16000, num_samples=172488, duration=10.7805, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0,
 snr=17.290758494598506)], transforms=[{'name': 'ReverbWithImpulseResponse', 'kwargs': {'rir': {'id': 'medium-Room006-00052', 'sources': [{'type': 'file', 'channels': [0], 'source': '../rir/simulated_rirs/mediumroom/Room006/Room006-00052.wav'}], 'sampling_rat
e': 16000, 'num_samples': 16000, 'duration': 1.0, 'channel_ids': [0], 'transforms': None}, 'normalize_output': True, 'early_only': False, 'rir_channels': [0], 'rir_generator': None, 'RIR_SCALING_FACTOR': 3.0517578125e-05}}]),) kwargs={})
[extra info] When calling: MixedCut.load_audio(args=(MixedCut(id='d034760f-833f-3b7f-150f-9a1d3401c6c6_rvb', tracks=[MixTrack(cut=MixedCut(id='d034760f-833f-3b7f-150f-9a1d3401c6c6_rvb', tracks=[MixTrack(cut=MonoCut(id='c19330dd-884b-140f-dfca-4e9965ebf67b', start=0.0, d
uration=10.78, channel=0, supervisions=[SupervisionSegment(id='fj3nR9ZX1Ew__U__S3_fj3nR9ZX1Ew__U__S3---2803.610-2814.390_000000-001078', recording_id='fj3nR9ZX1Ew__U__S3---2803.610-2814.390', start=0.0, duration=10.78, channel=0, text='transcript not available', languag
e=95, speaker='fj3nR9ZX1Ew__U__S3', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='fj3nR9ZX1Ew__U__S3---2803.610-2814.390', sources=[AudioSource(type='file', channels=[0], source='../voxlingua107/train/fr/fj3nR9ZX1Ew__U_
_S3---2803.610-2814.390.wav')], sampling_rate=16000, num_samples=172480, duration=10.78, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='26fa9ea1-9c66-d317-ab95-410753e6d6a3', start=0.0, duration=10.78, ch
annel=0, supervisions=[], features=None, recording=Recording(id='noise-free-sound-0469', sources=[AudioSource(type='file', channels=[0], source='../musan/noise/free-sound/noise-free-sound-0469.wav')], sampling_rate=16000, num_samples=172488, duration=10.7805,
 channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=17.290758494598506)], transforms=[{'name': 'ReverbWithImpulseResponse', 'kwargs': {'rir': {'id': 'medium-Room006-00052', 'sources': [{'type': 'file', 'channels': [0], 'source': '../rir/simulated_rirs/mediumroom/Room006/Room006-00052.wav'}], 'sampling_rate': 16000, 'num_samples': 16000, 'duration': 1.0, 'channel_ids': [0], 'transforms': None}, 'normalize_output': True, 'early_only': False, 'rir_channels': [0], 'rir_generator': None, 'RIR_SCALIN
G_FACTOR': 3.0517578125e-05}}]), type='MixedCut', offset=0.0, snr=None), MixTrack(cut=PaddingCut(id='a2d43ef4-d9dc-e0c3-3b4e-fdb4b945eb25', duration=9.05, sampling_rate=16000, feat_value=-23.025850929940457, num_frames=None, num_features=None, frame_shift=None, num_samp
les=144800, custom=None), type='PaddingCut', offset=10.78, snr=None)], transforms=None),) kwargs={})`

**Comment by desh2608** [comment]
Could you please show the sequence of operations you performed that resulted in the errors? More details would be useful to debug.

**Comment by osadj** [comment]
Thanks @desh2608. I'm using v1.14. I'll give it a try with current HEAD.

As for the operations, essentially I'm using the `cut_transforms` functionality of the K2 dataset (similar to the example):

train_dataset = K2SpeechRecognitionDataset(
    cut_transforms=[
        CutMix(musan_cuts, snr=[10, 20], p=0.5),
        ReverbWithImpulseResponse(rir_recordings, p=0.5),
    ],
    input_transforms=[]
    input_strategy=AudioSamples(),
)

I just found that setting  `pad_to_longest` to `False` helps resolve the issue for CutMix, but there is no such option for Reverb. Any quick workarounds would be great. 

Also, I notice that CutMix does not preserve the range of the original audio (i.e., before adding noise), so the noise corrupted version is no longer in [-1, 1]. Can you please help add an option for this?

**Comment by osadj** [comment]
Thanks, @desh2608. As you suggested, this issue seems to be fixed in `lhotse-1.15.0.dev0`.

**Comment by pzelasko** [comment]
OK, great. I'll release 1.15 to PyPI today.
