### ISSUE TITLE
SpecAugment `state_dict` not compatible with PyTorch's

### ISSUE THREAD

**Issue by osadj** [lhotse-speech/lhotse#1075]
Hello, I'm using the SpecAugment module as a layer in my model, however I see that the custom `state_dict` method is incompatible with Pytorch's. In particular, `destination`, `prefix`, and  `keep_vars` arguments are missing, and PyTorch complains. Can you please help fix this?

**Comment by pzelasko** [comment]
Would you be willing to contribute the fix? You'd need to modify the method here: https://github.com/lhotse-speech/lhotse/blob/e982003c1777a8f48ee40580bd835c931a03062d/lhotse/dataset/signal_transforms.py#L262

**Comment by osadj** [comment]
Thanks, @pzelasko. Sure. I'll send you a PR.
