### ISSUE TITLE
`CutMix` noise augmentation does not preserve the amplitude range of the original audio

### ISSUE THREAD

**Issue by osadj** [lhotse-speech/lhotse#1076]
Hello, I noticed that CutMix noise augmentation does not preserve the amplitude range of the original audio (i.e., before adding noise), so the noise corrupted version is no longer in [-1, 1]. Can you please help add an option for this?

For your reference, I'm following the K2 dataset example for this:

`train_dataset = K2SpeechRecognitionDataset(cut_transforms=[ CutMix(musan_cuts, snr=[10, 20], p=0.5), ], input_transforms=[], input_strategy=AudioSamples(),)`

**Comment by pzelasko** [comment]
Hmmm perhaps we should introduce either clipping or a limiter here, but also in other places. What number/percentage of samples goes beyond [-1, 1] in your scenario?

**Comment by osadj** [comment]
Thanks, @pzelasko. On a toy experiment, with a batch size of 8 and SNR range [10, 20], this happens to at least one cut in almost every batch.  

I'd suggest rescaling the augmented audio as follows:

```
y = augment_fn(x)
scale = max(abs(x)) / max(abs(y))
y = y * scale
```

where x and y are the original and augmented audios.

**Comment by pzelasko** [comment]
Sounds good, we could do that

**Comment by osadj** [comment]
@pzelasko do you have an update on this? This hasn't been fixed in the past two releases.

**Comment by pzelasko** [comment]
Ah, it slipped my mind. Would you be open to making a PR with the relevant changes?

**Comment by pzelasko** [comment]
I'm starting to think maybe a better solution is to use a limiter to post-process the audio. Can you try to apply e.g. this to your use case and let me know if that helped? https://github.com/pzelasko/cylimiter

**Comment by osadj** [comment]
Thanks. One problem with post-processing the audio after the fact is that we lose access to the original range. Can you please elaborate briefly what your implementation of the limiter does? I'm concerned about the distortions it introduces. Re-scaling by amplitude (or rms) is the safest approach imho.

**Comment by pzelasko** [comment]
I missed this. Limiter monitors the loudness level and dynamically decreases the gain when the signal is about to exceed some level. You can check e.g. this for a description of limiter https://www.izotope.com/en/learn/an-introduction-to-limiters-and-how-to-use-them.html
