### ISSUE TITLE
Cut describe show wrong duration statistics of VCTK

### ISSUE THREAD

**Issue by trunglebka** [lhotse-speech/lhotse#1081]
Expected:
- Correct duration statistics with respect to supervision duration

Actual:
- Incorrect duration statistics, see below image 

Lhotse version: current master branch latest commit

Steps to reproduce:
- prepare VCTK
- using `lhotse cut describe` to show statistics of the dataset

![image](https://github.com/lhotse-speech/lhotse/assets/16150250/f91f1996-0b08-4a7d-b2b8-97cac15252ae)

**Comment by pzelasko** [comment]
Please make sure that the CutSet was created correctly and it contains the relevant supervisions. I think the error might be there rather than in `describe`.

**Comment by trunglebka** [comment]
I've looked at supervisions manifest, it contains "valid" duration. 
The `describe` seem use start time of supervision to count speaker and that make me confuse

**Comment by pzelasko** [comment]
I think the issue is elsewhere, in constructing the CutSet. If you created the manifest with `lhotse cut simple ...` then try the option `--force-eager`; if you used `CutSet.from_manifests()` then specify `lazy=False`.

**Comment by trunglebka** [comment]
force-eager worked.
![image](https://github.com/lhotse-speech/lhotse/assets/16150250/d54681b4-34b6-46cd-a13a-bd040e94c001)
