### ISSUE TITLE
large dataset shuffle question

### ISSUE THREAD

**Issue by godiclee** [lhotse-speech/lhotse#1084]
Hi I would like to know if lhotse natively support shuffling a large cutset in a totally random manner?

I notice that cutset.shuffle() has an argument buffer_size. While buffer_size = len(cut_set), it should perform (near) random shuffling on the whole dataset. However, memory went up to over 160gb (while original cut set has only size 10gb). Is this phenomenon normal?

**Comment by pzelasko** [comment]
> I notice that cutset.shuffle() has an argument buffer_size. While buffer_size = len(cut_set), it should perform (near) random shuffling on the whole dataset. However, memory went up to over 160gb (while original cut set has only size 10gb). Is this phenomenon normal?

The buffer_size is not intended to be as large as len(cut_set), but rather sth closer to 50k / 100k / 200k cuts depending on your CPU memory. As Dan mentioned it's best to use `shuf` once to pre-shuffle and then you won't need such a large buffer size anyway. Another option that I recently recommended to somebody was to use `load_manifest_lazy("pipe:gunzip -c cuts.jsonl.gz | shuf")` which will shuffle differently each time you iterate the cut set.

**Comment by godiclee** [comment]
Thanks a lot! It works perfectly! (shuf pre-shuffle, then use streaming data loader during training)

**Comment by csukuangfj** [comment]
> yes, and I want to shuffle the whole cutset, which is created from egs/wenetspeech and a few smaller dataset

I suggest that you don't need to combine the splits into a big cutset.

**Comment by danpovey** [comment]
But fangjun, if he doesn't combine them, won't it access them sequentially?  Or at least not in a thoroughly-mixed way?

**Comment by csukuangfj** [comment]
> But fangjun, if he doesn't combine them, won't it access them sequentially? Or at least not in a thoroughly-mixed way?

https://github.com/k2-fsa/icefall/blob/82f34a238875188ae86552c2655026cc14b41c76/egs/librispeech/ASR/pruned_transducer_stateless3/gigaspeech.py#L62
```python3
        return lhotse.combine(lhotse.load_manifest_lazy(p) for p in sorted_filenames)
```

The above line shows how we use multiple splits in icefall.

> won't it access them sequentially

Users can 
(1) shuffle sorted_filenames if they want
(2) shuffle within each file if they want

I think it is equivalent to combining the splits offline. We are combining splits on-the-fly and it is more flexible.


The downsides of combining all splits in a single large file are that:
(1) It takes several hours to combine all the splits
(2) The resulting file is more than 10GB if the dataset is very large. I don't think it is a good idea to have a very large file.

**Comment by pzelasko** [comment]
Please see this recently merged PR in Lhotse, it ultimately solves the issue of combining splits by randomizing their order every time CutSet is iterated over, and it's all done lazily (no waiting to combine).

https://github.com/lhotse-speech/lhotse/pull/1085
