### ISSUE TITLE
Recommended way to load cutset splits for feature extraction w/out regenerating raw splits

### ISSUE THREAD

**Issue by AdolfVonKleist** [lhotse-speech/lhotse#1088]
Is there an easy native way to directly load raw cut splits without regenerating them?

I'm currently using the spgi boilerplate in my own generic dataset builder.  However I have a very large dataset and the fbank generation is becoming a bottleneck.  I would like to distribute the fbank computations over all the GPUs I have on my training node, but I noticed that here the raw cut splits are regenerated every time I run the script:

- https://github.com/k2-fsa/icefall/blob/master/egs/spgispeech/ASR/local/compute_fbank_spgispeech.py#L97
```python
    if args.train:
        logging.info("Processing train")
        cut_set = load_manifest_lazy(src_dir / "cuts_train_raw.jsonl.gz")
        chunk_size = len(cut_set) // args.num_splits
        cut_sets = cut_set.split_lazy(
            output_dir=src_dir / f"cuts_train_raw_split{args.num_splits}",
            chunk_size=chunk_size,
        )
        start = args.start
        stop = min(args.stop, args.num_splits) if args.stop > 0 else args.num_splits
        num_digits = len(str(args.num_splits))
        for i in range(start, stop):
            idx = f"{i + 1}".zfill(num_digits)
            cuts_train_idx_path = src_dir / f"cuts_train_{idx}.jsonl.gz"
            logging.info(f"Processing train split {i}")
            cs = cut_sets[i].compute_and_store_features_batch(
                extractor=extractor,
                storage_path=output_dir / f"feats_train_{idx}",
                batch_duration=500,
                num_workers=4,
                storage_type=LilcomChunkyWriter,
                overwrite=True,
            )
            cs.to_file(cuts_train_idx_path)
```

since all the raw cutsets already exist on disk, I am looking for a function that would allow me to return the `cut_sets` object without calling `.split_lazy`, i.e., just return the list for the precomputed files.  Then I can easily split these across my GPUs and run the feature extraction in parallel. 

The splitting is also pretty slow so it would be nice to be able to easily avoid repeating it for no reason.  I followed the code here but it looked like the generation of this list is tied to the actual writing activity pretty tightly.  Any hints on how to modify this behavior, maybe with a native function that I missed, would be greatly appreciated.

**Comment by pzelasko** [comment]
It looks to me like you could add some conditional logic to only perform `split_lazy` if the splits don't already exist; you can do sth like checking: 

```python
cut_paths = sorted((src_dir / f"cuts_train_raw_split{args.num_splits}").glob("*.jsonl.gz"))
if len(cut_paths) == expected_num_splits:
  # skip splitting
  cut_sets = [CutSet.from_file(p) for p in cut_paths]
else:
  # split
  cut_sets = cut_set.split_lazy(...)
```

**Comment by AdolfVonKleist** [comment]
@pzelasko thanks! `CutSet.from_file` looks like it was the ticket.
