### ISSUE TITLE
training using multi-GPU with webdataset

### ISSUE THREAD

**Issue by clockw** [lhotse-speech/lhotse#1098]
I would like to use webdataset for training according to https://colab.research.google.com/github/lhotse-speech/lhotse/blob/master/examples/02-webdataset-integration.ipynb

But I found out that it always leads to an unequal number of batches in distributed workers, then the training process will stuck. What should I change or set to make the number of batches even in distributed training?

```
train = K2SpeechRecognitionDataset(
            cut_transforms=transforms,
            input_transforms=input_transforms,
            return_cuts=self.args.return_cuts,
 )

train_sampler = DynamicBucketingSampler(
                cuts_train, #  cuts_train = CutSet.from_webdataset()
                max_duration=self.args.max_duration,
                shuffle=True,
                rank=0,
                world_size=1
)

train_iter_dataset = IterableDatasetWrapper(
            dataset=train,
            sampler=train_sampler,

)
train_dl = DataLoader(
            train_iter_dataset,
            batch_size=None,
            num_workers=self.args.num_workers,
            persistent_workers=False,
            worker_init_fn=make_worker_init_fn(
                rank=rank,
                world_size=world_size
            ),
)
```

**Comment by clockw** [comment]
Solve it by using torch.distributed.algorithms.join

**Comment by pzelasko** [comment]
Cool, that's the right solution. You can also call `.repeat()` on the cut set passed into the sampler, which would result in an infinite iterable (= no length issues but also no epochs).
