### ISSUE TITLE
KeyError when loading kaldi feature

### ISSUE THREAD

**Issue by ZihanLiao** [lhotse-speech/lhotse#1100]
When loading kaldi precomputed features, the following error occurred.
![image](https://github.com/lhotse-speech/lhotse/assets/54339989/799d5bb7-94be-460d-afe6-b381a1cc9f07)
The final line of the log is:
`KeyError: "'kaldi_native_io'\n[extra info] When calling: MixedCut.load_features(args=(MixedCut(id='125-121124-0044-1336', tracks=[MixTrack(cut=MonoCut(id='125-121124-0044-1336', start=0.0, duration=13.68, channel=0, supervisions=[SupervisionSegment(id='125-121124-0044', recording_id='125-121124-0044', start=0.0, duration=13.68, channel=0, text='IT IS INDEED SAID DANG LARS IT IS A FINE THING TO HAVE SUCH CREDIT REALLY IT IS ONLY IN FRANCE THESE THINGS ARE DONE FIVE MILLIONS ON FIVE LITTLE SCRAPS OF PAPER IT MUST BE SEEN TO BE BELIEVED', language=None, speaker='125-121124-0044', gender=None, custom=None, alignment=None)], features=Features(type='kaldi_native_io', num_frames=1368, num_features=80, frame_shift=0.01, sampling_rate=16000, start=0, duration=13.68, storage_type='kaldiio', storage_path='/home/share_ssd_data/env/data/cn/feats/cn-pinyin_en-grapheme/librispeech-100h/train/fbank/raw_fbank_train.2.ark:40729385', storage_key='125-121124-0044', recording_id='125-121124-0044', channels=0), recording=None, custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='noise-sound-bible-0084-926', start=0.0, duration=8.045, channel=0, supervisions=[], features=Features(type='kaldi-fbank', num_frames=805, num_features=80, frame_shift=0.01, sampling_rate=16000, start=0, duration=8.045, storage_type='lilcom_chunky', storage_path='data/fbank/musan_feats.lca', storage_key='191570266,42344,25512', recording_id='noise-sound-bible-0084', channels=0), recording=Recording(id='noise-sound-bible-0084', sources=[AudioSource(type='file', channels=[0], source='/home/share_ssd_data/env/data/cn/musan/noise/sound-bible/noise-sound-bible-0084.wav')], sampling_rate=16000, num_samples=128720, duration=8.045, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=10.25010755222667), MixTrack(cut=MonoCut(id='noise-free-sound-0749-749', start=0.0, duration=1.0, channel=0, supervisions=[], features=Features(type='kaldi-fbank', num_frames=100, num_features=80, frame_shift=0.01, sampling_rate=16000, start=0, duration=1.0, storage_type='lilcom_chunky', storage_path='data/fbank/musan_feats.lca', storage_key='163779086,9084', recording_id='noise-free-sound-0749', channels=0), recording=Recording(id='noise-free-sound-0749', sources=[AudioSource(type='file', channels=[0], source='/home/share_ssd_data/env/data/cn/musan/noise/free-sound/noise-free-sound-0749.wav')], sampling_rate=16000, num_samples=16000, duration=1.0, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=8.045, snr=10.25010755222667), MixTrack(cut=MonoCut(id='noise-free-sound-0008-7', start=0.0, duration=4.635, channel=0, supervisions=[], features=Features(type='kaldi-fbank', num_frames=2081, num_features=80, frame_shift=0.01, sampling_rate=16000, start=0, duration=20.8050625, storage_type='lilcom_chunky', storage_path='data/fbank/musan_feats.lca', storage_key='1405746,46667,46520,46695,46719,7634', recording_id='noise-free-sound-0008', channels=0), recording=Recording(id='noise-free-sound-0008', sources=[AudioSource(type='file', channels=[0], source='/home/share_ssd_data/env/data/cn/musan/noise/free-sound/noise-free-sound-0008.wav')], sampling_rate=16000, num_samples=332881, duration=20.8050625, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=9.045, snr=10.25010755222667)], transforms=None),) kwargs={})"`

Personally fixed this issue by changing these two parts. https://github.com/lhotse-speech/lhotse/blob/master/lhotse/cut/mixed.py#L966 and https://github.com/lhotse-speech/lhotse/blob/master/lhotse/cut/mixed.py#L975
Change `reference_cut.features.type` to `reference_cut.features.type if reference_cut.features.type != "kaldi_native_io" else "kaldifeat-fbank"`
See if these changes are ample to fix this issue meanwhile run other parts fluently.

**Comment by pzelasko** [comment]
I see. I think the best solution is to modify the `load_kaldi_data_dir` function to assign either `kaldi-fbank` or `kaldi-mfcc` feature type instead of `kaldi_native_io` in the following line:

https://github.com/lhotse-speech/lhotse/blob/cb0b7d341fa348063c6925e5e2512a65c33206a4/lhotse/kaldi.py#L242C38-L242C38

I'm not sure if we'd be able to auto-detect which feature type it is; we can just assume `kaldi-fbank`, or make it default and let the user override. Could you make a PR?

**Comment by ZihanLiao** [comment]
https://github.com/lhotse-speech/lhotse/pull/1101
See if this PR is qualified.
