### ISSUE TITLE
AssertionError: Supervision exceeded the bounds of its corresponding recording

### ISSUE THREAD

**Issue by RuslanSel** [lhotse-speech/lhotse#1107]
I have a dataset segmented with Kaldi.
I can load it with 
recordings, supervisions, _ = load_kaldi_data_dir(
    data_dir, sampling_rate=16000
)
But validate_recordings_and_supervisions(recordings, supervisions) gives
AssertionError: Supervision 40743833-00005000-00007337-4: exceeded the bounds of its corresponding recording (supervision spans [63.66, 73.37]; recording spans [0, 73.365])

Thanks in advance.

**Comment by desh2608** [comment]
You can fix it using:
```python
from lhotse.qa import fix_manifests

r, s = fix_manifests(recordings=r, supervisions=s)
```

See: https://github.com/lhotse-speech/lhotse/blob/e094aa6eea35021f79724a88b73e0a9f68f7557b/lhotse/qa.py#L46

**Comment by RuslanSel** [comment]
Thank you! It helped.
