### ISSUE TITLE
Why can't the custom attributes in custom field of SupervisionSegment be removed like that in Cut?

### ISSUE THREAD

**Issue by yfyeung** [lhotse-speech/lhotse#1111]
SupervisionSegment: https://github.com/lhotse-speech/lhotse/blob/eb212985fee8fa5165e24a2b45fdac9a43f6e54d/lhotse/supervision.py#L459-L470
Cut: https://github.com/lhotse-speech/lhotse/blob/eb212985fee8fa5165e24a2b45fdac9a43f6e54d/lhotse/cut/data.py#L73-L89

**Comment by pzelasko** [comment]
I didn't understand your question; can you elaborate?

**Comment by danpovey** [comment]
I think he is pointing out that one of them has a mechanism where you can
assign a None to remove the entry.
(Although I suppose the usual python mechanism for that is __del__ ?)

**Comment by yfyeung** [comment]
> 

Yes.
