### ISSUE TITLE
Error when downloading `libricss` and `rirs_noises` recipes

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1141]
The LibriCSS recipe icefall using requires downloading `libricss`.

While downloading `libricss`, current script yields this error:
```
sed: -e expression #1, char 31: unterminated `s' command
```

**Comment by pzelasko** [comment]
@desh2608 I think you contributed this recipe, could you take a look?

**Comment by desh2608** [comment]
You also mention something about the `rirs_noises` recipe. Could you elaborate? I just checked and confirmed that download works fine for that recipe.

**Comment by JinZr** [comment]
Dear Desh,

I figure it might be related to a typo in the `prepare.sh`
https://github.com/k2-fsa/icefall/blob/fba17106228badbc77c5aa75c1a1263877067906/egs/libricss/SURT/prepare.sh#L82C5-L82C32

The script should work well if this is fixed.

Best
