### ISSUE TITLE
The training process got stuck when saving checkpoint

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1146]
I'm training a zipformer recipe for the swbd PR https://github.com/k2-fsa/icefall/pull/1146.

The training process gets stuck at exactly the end of the 4th epoch.

The saving process goes well when the line below is commented, 
https://github.com/k2-fsa/icefall/blob/fba17106228badbc77c5aa75c1a1263877067906/icefall/checkpoint.py#L85,
so I suspect this might be an issue related to the lhotse sampler.

**Comment by JinZr** [comment]
Dear Piotr,

This is what I got from py-spy
```
(dev_swbd) jinzengrui@de-74279-k2-train-7-1218101249-5d97868c7c-98fdf:~/dev_swbd/icefall$ py-spy dump -p 3740553
Process 3740553: /star-home/jinzengrui/lib/miniconda3/envs/dev_swbd/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=8) --multiprocessing-fork
Python v3.9.17 (/star-home/jinzengrui/lib/miniconda3/envs/dev_swbd/bin/python3.9)

Thread 3740553 (idle): "MainThread"
    select (selectors.py:416)
    wait (multiprocessing/connection.py:931)
    _poll (multiprocessing/connection.py:424)
    poll (multiprocessing/connection.py:257)
    get (multiprocessing/queues.py:113)
    _try_get_data (torch/utils/data/dataloader.py:1120)
    _get_data (torch/utils/data/dataloader.py:1282)
    _next_data (torch/utils/data/dataloader.py:1316)
    __next__ (torch/utils/data/dataloader.py:628)
    train_one_epoch (train.py:939)
    run (train.py:1254)
    _wrap (torch/multiprocessing/spawn.py:69)
    run (multiprocessing/process.py:108)
    _bootstrap (multiprocessing/process.py:315)
    _main (multiprocessing/spawn.py:129)
    spawn_main (multiprocessing/spawn.py:116)
    <module> (<string>:1)
Thread 3740863 (idle): "Thread-1"    wait (threading.py:316)
    get (queue.py:180)
    _run (tensorboard/summary/writer/event_file_writer.py:269)    
    run (tensorboard/summary/writer/event_file_writer.py:244)    
    _bootstrap_inner (threading.py:980)    
    _bootstrap (threading.py:937)
Thread 3740960 (idle): "Dummy-2"
Thread 3740961 (idle)
Thread 3916528 (idle): "QueueFeederThread"
    wait (threading.py:312)
    _feed (multiprocessing/queues.py:231)
    run (threading.py:917)
    _bootstrap_inner (threading.py:980)
    _bootstrap (threading.py:937)
Thread 3916529 (idle): "QueueFeederThread"
    wait (threading.py:312)
    _feed (multiprocessing/queues.py:231)
    run (threading.py:917)
    _bootstrap_inner (threading.py:980)
    _bootstrap (threading.py:937)
```

**Comment by pzelasko** [comment]
Is it multi GPU training? If yes, can you specify drop_last=True in the sampler and try again?

**Comment by JinZr** [comment]
Dear Piotr,

The recipe is currently using SingleCutSampler, let me switch to
DynamicBucketSampler and see if drop_last=True works.

Best

**Comment by JinZr** [comment]
It's multi-GPU trained, fyi.

**Comment by JinZr** [comment]
Dear Piotr,

Switching to DynamicBucketSampler with drop_last=True solves the issue.

Do you think this might be related to SingleCutSampler?

Best Regards


Piotr Żelasko ***@***.***>于2023年9月15日 周五01:59写道：

**Comment by pzelasko** [comment]
Both of these samplers support `drop_last` argument. It seems that in epoch 4 you ran into a situation that some GPUs had one less mini-batch than the others which causes torch DDP to hang. An alternative to `drop_last` is described here: https://pytorch.org/tutorials/advanced/generic_join.html

**Comment by JinZr** [comment]
OK, I guess I’ll have to make drop_last=True a default.

Thanks!

Best Regards
