### ISSUE TITLE
Padding in librispeech example

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#115]
Piotr, in here
https://github.com/lhotse-speech/lhotse/blob/master/examples/librispeech/librispeech.ipynb
there is a call to .pad(), which I think pads all cuts to the longest utterance there- I assume that would be quite
inefficient when it comes time to train?
Is it possible to delay padding until after we form minibatches, and form minibatches in a more efficient way so that
things of a like size go together?

**Comment by pzelasko** [comment]
I'll move the discussion to issue #113 as it's related to it. I expect to provide some solutions in the next few days.
