### ISSUE TITLE
The mismatch between split and split-lazy, specifically counting from 0 or 1

### ISSUE THREAD

**Issue by yfyeung** [lhotse-speech/lhotse#1152]
I note that `lhotse split` will generate splits that counting from 1, while `lhotse split-lazy` will generate splits that counting from 0.
In some icefall recipes like gigaspeech, we initially use `lhotse split` and then change to use `lhotse split-lazy`. However, we didn't consider this mismatch, resulting in some bugs.

**Comment by yfyeung** [comment]
For `lhotse split`: https://github.com/lhotse-speech/lhotse/blob/567ba2941bb4dca4bf293d052ea7ae8ab8a590ef/lhotse/utils.py#L336
For `lhotse split-lazy`: https://github.com/lhotse-speech/lhotse/blob/567ba2941bb4dca4bf293d052ea7ae8ab8a590ef/lhotse/utils.py#L277

**Comment by pzelasko** [comment]
Sorry for that, I think initially I wanted to be compatible with Kaldi's convention of 1-based splits for data directories, and later I didn't remember that when introducing the lazy thing. We should fix that. I probably prefer to adopt 0-based counting everywhere, seems more consistent with the rest of the and library and Python in general. WDYT @yfyeung @csukuangfj @desh2608 @danpovey?

**Comment by yfyeung** [comment]
Thanks. I agree with adhering to a 0-based counting system. 

Best regards.

**Comment by desh2608** [comment]
Submitting jobs on an SGE cluster requires indices starting at 1, which I suppose is why 1-based indexing is used in Kaldi. I would suggest adding a "start_index" option to those functions, which defaults to 0.

**Comment by desh2608** [comment]
The above is also why we added the `num_digits` option in the lazy version. In the original implementation, I think padding was by default, but this made it hard to use the split manifests in array job submissions.

**Comment by pzelasko** [comment]
Thanks, should be fixed now.
