### ISSUE TITLE
AudioLoadingError when using relative paths in manifest

### ISSUE THREAD

**Issue by rilshok** [lhotse-speech/lhotse#1163]
An `AudioLoadingError` error occurs when I try to load an audio file using a relative path in the manifest, and execute code not from the root directory for that relative path.  

An easy way to reproduce the problem:
```python
import lhotse
from pathlib import Path

ljspeech_path = str(Path(lhotse.__file__).parent.parent / "test" / "fixtures"/ "ljspeech" / "cuts.json")
cutset = lhotse.CutSet.from_file(ljspeech_path)
cutset[0].recording.load_audio()
```
```bash
AudioLoadingError: Reading audio from 'test/fixtures/ljspeech/storage/LJ002-0020.wav' failed. Details:
Exception #0 (<class 'lhotse.audio.backend.TorchaudioDefaultBackend'>): <class 'RuntimeError'>: Failed to open the input "test/fixtures/ljspeech/storage/LJ002-0020.wav" (No such file or directory).
Exception #1 (<class 'lhotse.audio.backend.AudioreadBackend'>): <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'test/fixtures/ljspeech/storage/LJ002-0020.wav'
Set LHOTSE_AUDIO_LOADING_EXCEPTION_VERBOSE=1 environment variable for full stack traces.
[extra info] When calling: Recording.load_audio(args=(Recording(id='LJ002-0020', sources=[AudioSource(type='file', channels=[0], source='test/fixtures/ljspeech/storage/LJ002-0020.wav')], sampling_rate=22050, num_samples=33949, duration=1.5396371882086168, channel_ids=[0], transforms=None),) kwargs={})
```

My guess is that Lhotse is currently dereferencing the paths in the manifest to be relative to `pwd`, which can cause problems when executing a script from another directory. I suggest changing the design so that Lhotse resolves paths in the manifest relative to the directory from which the manifest was loaded. For example, when saving the manifest, you can continue to use relative paths, but relative to the place where the manifest itself is saved. And when loading content, determine the actual path to the file based on the information from where the manifest was loaded.

**Comment by pzelasko** [comment]
You can use `cuts = cuts.with_recording_path_prefix(root)` to achieve the behavior you're expecting, see:

https://github.com/lhotse-speech/lhotse/blob/5c617ee800376418c9c40acbf24db70540882266/lhotse/cut/set.py#L2532-L2536

**Comment by rilshok** [comment]
Thank you so much, it really works!

```python
import lhotse
from pathlib import Path

lhotse_root = Path(lhotse.__file__).parent.parent
ljspeech_path = str(lhotse_root / "test" / "fixtures"/ "ljspeech" / "cuts.json")
cutset = lhotse.CutSet.from_file(ljspeech_path).with_recording_path_prefix(str(lhotse_root))
cutset[0].recording.load_audio()
```

```
array([[0.00027466, 0.00076294, 0.00054932, ..., 0.00064087, 0.0007019 ,
        0.00061035]], dtype=float32)
```
