### ISSUE TITLE
Slow `CutSet.describe()`

### ISSUE THREAD

**Issue by zbiglatka** [lhotse-speech/lhotse#1167]
Hello. I love the `CutSet.describe()` feature. I use it a lot to analyze my datasets, especially to see how various filters (applied in `DynamicBucketingSampler` during training) affect the size and statistics of the dataset.

Unfortunately, with large cutsets (I'm talking 10M+ cuts), `cuts.describe()` is way too slow to be useful. I would really like `CutSet.describe()` to have an additional argument `num_jobs` (similar to `CuSet.trim_to_supervisions()` or `CutSet.cut_into_windows()`) to set the number of parallel workers to process the cuts. Thanks!

**Comment by pzelasko** [comment]
If the cut set is contained in a single file, I think that parallelization won't help. I quickly profiled `describe` with py-spy (see snippet below) and the majority of the time was spent in deserialization and cut iteration, and only a tiny fraction (~10%) on computation inside describe. That means with a single manifest file, you'd still spend the 90% of the time to describe iterating.

However, if you had multiple manifests, it'd be possible iterate + accumulate the stats for each partition in parallel and then reduce and display them.
