### ISSUE TITLE
Number of declared samples in the recording diverged from the one obtained when loading audio

### ISSUE THREAD

**Issue by JuanPZuluaga** [lhotse-speech/lhotse#1180]
Hello, 

I'm getting the following error while trying to train a model with Commonvoice and Icefall. I've gotten into the same problem for different languages of CommonVoice.

```
ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=0.0, duration=6.594). This could be internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=1014, audio.shape=(1, 104490), recording=Recording(id='common_voice_es_23747196', sources=[AudioSource(type='file', channels=[0], source='/idiap/resource/database/common_voice_11_0/audio/es/dev/es_dev_0/common_voice_es_23747196.mp3')], sampling_rate=16000, num_samples=105504, duration=6.594, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 44100, 'target_sampling_rate': 16000}}])
[extra info] When calling: Recording.load_audio(args=(Recording(id='common_voice_es_23747196', sources=[AudioSource(type='file', channels=[0], source='/idiap/resource/database/common_voice_11_0/audio/es/dev/es_dev_0/common_voice_es_23747196.mp3')], sampling_rate=16000, num_samples=105504, duration=6.594, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 44100, 'target_sampling_rate': 16000}}]),) kwargs={'channels': 0, 'offset': 0.0, 'duration': 6.594})
```

Is there a way to fix this? 

I've tried to modify this: https://github.com/k2-fsa/icefall/blob/eeeeef390b2d7f1aefe742ac069565d5f8eb8a38/egs/commonvoice/ASR/local/compute_fbank_commonvoice_dev_test.py#L88

by the following instead (to resample the audio to 16kHz): 
```
        cut_set = cut_set.resample(16000).compute_and_store_features_batch(
```

I also guess that in CV we have audios with different sampling rates, could that be the issue? (similar to https://github.com/k2-fsa/icefall/issues/1196) 
thank you.

**Comment by pzelasko** [comment]
The diff is slightly over 50ms which I think is the default tolerance. These things happen when audio files have incorrect metadata in the header or a different audio decoder (or its version) is used for loading and manifest creation. You can run lhotse.set_audio_duration_mismatch_tolerance(0.1) to get rid of the issue. Resampling should just work.

**Comment by JuanPZuluaga** [comment]
Thank you! 

That did solve the issue.
