### ISSUE TITLE
LilcomChunkyWriter replaces storage_path if it contains "."

### ISSUE THREAD

**Issue by chiiyeh** [lhotse-speech/lhotse#1183]
Hi! I realize that when i use storage_path with . like "gigaspeech_overlap_0.3_TRAIN" it will end up becoming saving to the file "gigaspeech_overlap_0.lca" instead of "gigaspeech_overlap_0.3_TRAIN.lca" as expected. 
It seems to be due to this line:
https://github.com/lhotse-speech/lhotse/blob/afc8eff1d1eaeeae42e0a628e1981bb231527340/lhotse/features/io.py#L829
which replaces the words after "." with lca instead of appending. 
I saw quite a few other places using `.with_suffix` as well so will have the same issue as well.

**Comment by desh2608** [comment]
Good catch. We should probably change those to:
```python
p = Path(storage_path)
self.storage_path_ = p.with_suffix(p.suffix + ".lca")
```

**Comment by pzelasko** [comment]
+1, could you submit a PR? Thanks!
