### ISSUE TITLE
why transforming from kaldi data to manifests is slow?

### ISSUE THREAD

**Issue by Eric-Chen-007** [lhotse-speech/lhotse#1184]
I try to transform from kaldi data to manifests, it's very slow for large data, for example 2.6 million waves in wav.scp.

train data i have: 
```
wav.scp
text
utt2spk
spk2utt
```

the command i use is :
``` shell
lhotse kaldi import -j 40 data/train 16000 data/manifests"
```

Why it's so slow? 
For 0.1 million data, it is fast.
And i set number of jobs == 40.
But does it work? I check in 'htop' and find most of the CPU is in idle state.

**Comment by desh2608** [comment]
I think part of the reason is that it reads all the audio files to compute the recording durations. It would be much faster if you have existing `reco2dur` and `utt2dur` in the directory.

**Comment by Eric-Chen-007** [comment]
> I think part of the reason is that it reads all the audio files to compute the recording durations. It would be much faster if you have existing `reco2dur` and `utt2dur` in the directory.

Thanks for your reply, that's the reason.
