### ISSUE TITLE
`trim-to-alignments` produces negative utterance duration on libriheavy

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1186]
Trimming the CutSet `libriheavy_cuts_small_ali_proc.jsonl.gz` would produce `libriheavy_cuts_small_ali_proc_trimmed.jsonl.gz` containing utterances with negative duration, attachments can be found [here](https://drive.google.com/drive/folders/1Aq1qHtfpQszTZpGhAXo8CMJPC7PZsyQB?usp=sharing).

Command I used:
```
lhotse cut trim-to-alignments --keep-all-channels --type word --max-pause 0.2 libriheavy_cuts_small_ali_proc.jsonl.gz libriheavy_cuts_small_ali_proc_trimmed.jsonl.gz
```

**Comment by pzelasko** [comment]
@desh2608 could you take a look?
