### ISSUE TITLE
Feature extraction got stuck when both augmenter and executor is not None

### ISSUE THREAD

**Issue by freewym** [lhotse-speech/lhotse#121]
When `augmenter` is not None, the feature extraction seems to get stuck (meaning that it never enters into `_extract_and_store_features_helper_fn`) at the line below

https://github.com/lhotse-speech/lhotse/blob/master/lhotse/cut.py#L1263

There is no problems if `augmenter` is None, or `executor ` is None

**Comment by pzelasko** [comment]
Thanks I'll check it out tomorrow. Might have to wait a bit as our grid
will be under maintenance till 3pm.

pon., 9 lis 2020, 18:55 użytkownik Yiming Wang <notifications@github.com>
napisał:
