### ISSUE TITLE
RFC - Python 3.7 end of life and Python 3.8 new syntax features

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#1217]
I'm considering stopping supporting Python 3.7 in the next Lhotse release (or one after), since [Python 3.7 has reached end of life recently](https://devguide.python.org/versions/). That'd mean Lhotse library code could start using new syntax features from Python 3.8. This issue is an RFC to check with the community if this is problematic and to what extent. Please share your feedback.

CC @danpovey @csukuangfj @desh2608

**Comment by desh2608** [comment]
Cool! We can start using the walrus operator now :)

**Comment by csukuangfj** [comment]
+1

PyTorch has already dropped support for Python 3.7 since torch 2.0.0.

We can use new features as described in https://docs.python.org/3/whatsnew/3.8.html
if we target at only Python >=3.8.

**Comment by pzelasko** [comment]
It's merged. Feel free to use the "walrus", `match`, etc. going forward :)
