### ISSUE TITLE
Query on Extracting Features for Specific Intervals from Recordings

### ISSUE THREAD

**Issue by sangeet2020** [lhotse-speech/lhotse#1218]
Hello Lhotse/icefall team,

Is there an example that shows how to read features for given recordings within a specific start and end time? I understand that this can be done in the pre-processing step itself when creating the long-recording cut-manifests (by combining the `supervisions` and `recordings`).
```python
cut_set = CutSet.from_manifests(
    recordings=m["recordings"],
    supervisions=m["supervisions"],
).resample(16000)
```
Here we can supply an optional argument `features` which will be used to determine cut boundaries based on the given start and end time. This will probably ensure that when saving the long cut recordings in `data/fbank/cv_cuts_train_raw.jsonl.gz` to have the custom start time and end time as we specified in the first place.

If perhabs, there is another way or better way to do this, please let me know.

When saving the fbank features on the disk, my goal is to only save the features corresponding to the interval I specified and not the whole audio. Why? because the transcript for that audio only corresponds to the interval.

Thank You

**Comment by desh2608** [comment]
Once you create your cut_set as per above, you can do the following:
```python
cut_set = cut_set.trim_to_supervisions(keep_overlapping=False)
```

The resulting cuts will then be trimmed to the duration of your supervisions. You can then extract features on this new cut set.

**Comment by sangeet2020** [comment]
Thank you @desh2608 . It worked.
