### ISSUE TITLE
Computing features on truncated files

### ISSUE THREAD

**Issue by ezerhouni** [lhotse-speech/lhotse#1228]
Hi !

I am trying to compute features on a set of audio files and some of them are truncated (i.e the metadata for the duration is different than the actual length when reading the file). When computing features, it throw an error (I can re-find it if needed). I was wondering if we could discard the audio if truncated while computing the features (basically, instead of crashing, we just don't compute features for this audio).

Thanks

**Comment by pzelasko** [comment]
Try setting env var `LHOTSE_AUDIO_DURATION_MISMATCH_TOLERANCE=0.1` (or even as high as 0.3) and see if you keep hitting the same issue. Some codec implementations can differ in as much as ~300ms of extra padding when decoding audio, although it's rare.

**Comment by ezerhouni** [comment]
It turns out that ```read_audio``` does not return the same audio length than ```librosa```
