### ISSUE TITLE
Does lhotse support chunk-wise dataset/dataloader?

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1233]
Hi all, I'm wondering if lhotse supports chunk-wise dataset/dataloader, which is more frequently used in speech separation or enhancement.

**Comment by pzelasko** [comment]
Yes it’s possible to do. Try applying CutSet.cut_into_windows() to your data before passing it to the sampler for on the fly chunking.

**Comment by JinZr** [comment]
Thank you!
