### ISSUE TITLE
Sometimes start_frame + num_frames > T in K2SpeechRecognitionIterableDataset

### ISSUE THREAD

**Issue by qindazhu** [lhotse-speech/lhotse#125]
Here is a failure example :

```
feature shape (B,T,F) : torch.Size([10, 3017, 40])
start_frame + num_frames: tensor([1460, 3018, 1476, 2968, 1472, 2968, 1532, 2836, 1491, 2809, 1536, 2688,
        1545, 2681, 1557, 2593, 1594, 2085, 2580, 1640], dtype=torch.int32)
```
As you can see, there is `3018 > T = 3017`

I comput (and save) feature with
 https://github.com/k2-fsa/snowfall/blob/811e5333281a279e27e3008f5d025111d19cc487/egs/librispeech/asr/simple_v1/prepare.py#L42-L48,
then load `train-clean-100` with https://github.com/k2-fsa/snowfall/blob/811e5333281a279e27e3008f5d025111d19cc487/egs/librispeech/asr/simple_v1/train.py#L177-L181

Noted here is a warning about torch version, should I upgrade PyTorch version?
```
/ceph-hw/lhotse/lhotse/augmentation/torchaudio.py:13: UserWarning: Torchaudio SoX effects chains are only introduced in version 0.7 - please upgrade your PyTorch to 1.7+ and torchaudio to 0.7+ to use them.
  warnings.warn('Torchaudio SoX effects chains are only introduced in version 0.7 - '
```

**Comment by pzelasko** [comment]
Thanks for reporting, I will look into it today.

You don't have to update unless you plan to use torchaudio instead of
WavAugment for data augmentation. I'd suggest to make this transition when
the recipe is otherwise working and you start tuning which augmentations to
use.

pt., 13 lis 2020, 04:36 użytkownik Haowen Qiu <notifications@github.com>
napisał:

**Comment by qindazhu** [comment]
thanks!

**Comment by pzelasko** [comment]
Please check out if this PR fixes it for you - I ran it with LibriSpeech for some time and it seemed to not have triggered the new assert after the fix.

https://github.com/lhotse-speech/lhotse/pull/127

**Comment by qindazhu** [comment]
I have checked https://github.com/lhotse-speech/lhotse/pull/127 and run locally, it has run 300+ batches without crash, seems it works well! Many thanks!
