### ISSUE TITLE
The number of declared samples in the recording diverged from the one obtained when loading audio

### ISSUE THREAD

**Issue by wwwei1997** [lhotse-speech/lhotse#1250]
I encountered this error while processing the commonvoice data

ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=0, duration=7.737755102040817). This could be internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=1386, audio.shape=(1, 184320), recording=Recording(id='common_voice_de_23820106', sources=[AudioSource(type='file', channels=[0], source='/home/jovyan/workspace-0/projects/vall-e/egs/commonvoice/download/commonvoice/cv-corpus-16.0-2023-12-06/de/clips/common_voice_de_23820106.mp3')], sampling_rate=24000, num_samples=185706, duration=7.73775, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 44100, 'target_sampling_rate': 24000}}])
[extra info] When calling: Recording.load_audio(args=(Recording(id='common_voice_de_23820106', sources=[AudioSource(type='file', channels=[0], source='/home/jovyan/workspace-0/projects/vall-e/egs/commonvoice/download/commonvoice/cv-corpus-16.0-2023-12-06/de/clips/common_voice_de_23820106.mp3')], sampling_rate=24000, num_samples=185706, duration=7.73775, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 44100, 'target_sampling_rate': 24000}}]),) kwargs={'channels': 0, 'offset': 0, 'duration': 7.737755102040817})
[extra info] When calling: MonoCut.load_audio(args=(MonoCut(id='common_voice_de_23820106-57', start=0, duration=7.737755102040817, channel=0, supervisions=[SupervisionSegment(id='common_voice_de_23820106', recording_id='common_voice_de_23820106', start=0.0, duration=7.737755102040817, channel=0, text='Ähnlich gefärbte Ziegen kommen auch im Piemont und im Hochsavoyen der französischen Alpen vor.', language='de', speaker='1dce350b26cb3de2ba072f99dc71b042556caad9cf0540043c94eb9b4c6edcde31783289c9a2147ee743dcf59833d2d3d84af070c86154b599917178227b3fe3', gender='', custom={'age': '', 'accents': ''}, alignment=None)], features=None, recording=Recording(id='common_voice_de_23820106', sources=[AudioSource(type='file', channels=[0], source='/home/jovyan/workspace-0/projects/vall-e/egs/commonvoice/download/commonvoice/cv-corpus-16.0-2023-12-06/de/clips/common_voice_de_23820106.mp3')], sampling_rate=24000, num_samples=185706, duration=7.73775, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 44100, 'target_sampling_rate': 24000}}]), custom=None),) kwargs={})

**Comment by pzelasko** [comment]
Set env var LHOTSE_AUDIO_DURATION_MISMATCH_TOLERANCE=0.2 and it should work.

**Comment by wwwei1997** [comment]
> Set env var LHOTSE_AUDIO_DURATION_MISMATCH_TOLERANCE=0.2 and it should work.

Thanks, it works.
