### ISSUE TITLE
how to delete some monocuts in cutsets?

### ISSUE THREAD

**Issue by Mahaotian1** [lhotse-speech/lhotse#1256]
when i am training, i found some monocuts can not work out because of my mistake. My question is : how can i delete these monocuts which is in a cutset. I do not want to use "lhotse subset" to avoid these monocuts , it is too inconvenient to work.

**Comment by pzelasko** [comment]
you can use e.g. `cuts = cuts.filter(lambda c: c.id not in FORBIDDEN_IDS_SET)`

**Comment by Mahaotian1** [comment]
> you can use e.g. `cuts = cuts.filter(lambda c: c.id not in FORBIDDEN_IDS_SET)`

thanks a lot！
