### ISSUE TITLE
Directory structure of features

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#130]
I notice that by default lhotse seems to put all the .llc files in one directory.
On many (maybe even most) file systems this scales very poorly because you spend too much time manipulating the meta-info of the directory- particularly when writing.
I think a better default would be to use the first few characters of the hash as a sub-directory name.
Was thinking of making this dependent on how much data there is to process, but I'm concerned people will write their own scripts that assume a certain directory structure, and then get surprised when things are not as they expect.

**Comment by pzelasko** [comment]
Yeah, that sounds like a good addition. I'm less concerned about the directory structure assumption because we store paths in the manifests anyway (i.e. I don't see the reason to assume a specific structure when working with the manifests).
