### ISSUE TITLE
extract feature failed

### ISSUE THREAD

**Issue by zhazhuanling12** [lhotse-speech/lhotse#1311]
hello, I have met this problem when extracting features with timestamp (offset=1564.4397083333333, duration=1.1402916666666667) from a long wav (test.wav, duration=1566.6619). The specific information is as follows
``` 
WARNING:root:[Suppressed AudioLoadingError] Error message: The number of declared samples in the recording diverged 
from the one obtained when loading audio (offset=1564.4397083333333, duration=1.1402916666666667). This could be
internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=13683, audio.shape=(1, 13684), recording=Recording(id='test', sources=[AudioSource(type='file', channels=[0], 
source='test.wav')], sampling_rate=24000, num_samples=37599887, duration=1566.6619583333334, channel_ids=[0], 
transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 48000, 'target_sampling_rate': 24000}}])
```
Can I solve this problem without splitting the long audio into audio clips?

**Comment by zhazhuanling12** [comment]
hello, I have met this problem when extracting features with timestamp (offset=1564.4397083333333, duration=1.1402916666666667) from a long wav (test.wav, duration=1566.6619). 
Can I solve this problem without splitting the long audio into audio clips?

**Comment by zhazhuanling12** [comment]
I find when I del transforms, it works. But I don't know why

**Comment by pzelasko** [comment]
If it works after deleting the transform, then that suggests you have corrupted metadata. You can try recreating the manifests from scratch.

**Comment by zhazhuanling12** [comment]
Ok. But I wonder is there a problem with the transform module
