### ISSUE TITLE
AttributeError: No such attribute: to_eager

### ISSUE THREAD

**Issue by TinaChen95** [lhotse-speech/lhotse#1321]
Hi there,

Thank you for your excellent work. I've found the tool extremely helpful for data filtering and analysis. I am attempting to merge consecutive segments into one long segment to perform further statistics, but I encountered an error. Here's the situation:

This code works fine:
`cuts.filter_supervisions(lambda sup: sup.duration > 10).describe()`

However, when I try to merge segments using the following code, I run into an issue:
`cuts.filter_supervisions(lambda sup: sup.duration > 10).trim_to_supervision_groups(max_pause=100).describe()`

Below is the error trace screenshot:
![截屏2024-04-15 16 29 06](https://github.com/lhotse-speech/lhotse/assets/24587336/f94fac27-8dcb-40e7-abb4-ea731620f9a5)

Could you please advise on how I can successfully merge these segments and proceed with the data analysis? Thank you for your assistance!

**Comment by pzelasko** [comment]
Glad it's useful! I managed to reproduce it. Try this PR and let me know if it helped: https://github.com/lhotse-speech/lhotse/pull/1322
