### ISSUE TITLE
Bug: broken import from augmentations

### ISSUE THREAD

**Issue by LordOfLuck** [lhotse-speech/lhotse#137]
Hi I installed the latest pip version of lhotse and I am getting an import error when using the lhotse CLI:

Setup:
```
python3.7.0 
lhotse==0.2.0
```

To reproduce, try either from the following lines:
```
lhotse convert-kaldi <data-dir> 16000 <other-data-dir>
python -c "from lhotse.augmentation import available_wav_augmentations"
```

**Comment by pzelasko** [comment]
Sorry for that! Can you confirm if the PR #138 solves that for you? 

CLI has become somewhat of a second-class citizen lately, I'll have to add some tests for it to avoid breaking again in the future (#27).

**Comment by LordOfLuck** [comment]
hi, Thanks for fast response and fix!! I like this repo very much already :). The fix seems to work fine. How does the process of pushing to pip work? Is it scheduled regularly or so?

**Comment by pzelasko** [comment]
I need to figure out how to publish some kind of nightly build. For now, I'm doing it manually (so trying not do it too frequently).

Anyway it's also possible to install the latest version with `pip install git+https://github.com/lhotse-speech/lhotse`

**Comment by LordOfLuck** [comment]
Clear, thanks for the latest version install code.
