### ISSUE TITLE
How to load parquet file effectively with Lhotse?

### ISSUE THREAD

**Issue by kobenaxie** [lhotse-speech/lhotse#1374]
```
import torchaudio
import pandas as pd

data = [
    {'audio_path': 'path_to_audio_file_1.wav', 'text': 'This is the first text.'},
    {'audio_path': 'path_to_audio_file_2.wav', 'text': 'This is the second text.'},
    ....
]

audio_data = []
sample_rates = []
texts = []

for item in data:
    audio_path = item['audio_path']
    text = item['text']
    
    y, sr = torchaudio.load(audio_path, sr=None)
    
    audio_data.append(y)
    sample_rates.append(sr)
    texts.append(text)

df = pd.DataFrame({
    'audio_data': audio_data,
    'sample_rate': sample_rates,
    'text': texts
})

df.to_parquet("output_parquet.parquet")

```

Using this script, I prepared multiple parquet format files for our internal large dataset. Each *.parquet file contains 1000 wav-txt pairs for ASR task,  Any suggestions on how to build an efficient dataloader with Lhotse ?

**Comment by pzelasko** [comment]
Implement a similar wrapper to 

https://github.com/lhotse-speech/lhotse/blob/6a177213b1ad7e1d6b8233aa3db0d86cba3cdff4/lhotse/dataset/webdataset.py#L295

or

https://github.com/lhotse-speech/lhotse/blob/6a177213b1ad7e1d6b8233aa3db0d86cba3cdff4/lhotse/shar/readers/lazy.py#L29
