### ISSUE TITLE
Installation problem python 3.8 and sphinx==7.2.6;

### ISSUE THREAD

**Issue by npovey** [lhotse-speech/lhotse#1405]
I have lhotse installed on my new machine with python 3.10.
Today wanted to install lhotse on my old machine that has python3.8. 
But getting this error: ERROR: No matching distribution found for sphinx==7.2.6; extra == "dev"

Should I create a new python environment with python 3.10 and then install lhotse in that environment?
With python3.8 the latest sphinx that I can install is 7.1.2.

**Comment by pzelasko** [comment]
I don’t think we really need that version of sphinx, could you try to downgrade it in requirements file and retry? Can you also make a PR with this change if it helps?

**Comment by npovey** [comment]
aff1188f9a8ae1bc47304e9cdd46a74a5320ee86
Installation should now work with Python 3.8. Tested and confirmed."
