### ISSUE TITLE
Features not including original recording_id when computing

### ISSUE THREAD

**Issue by njellinas** [lhotse-speech/lhotse#1411]
I run the command: compute_and_store_features on a CutSet and the resulting cuts contain features that do not include the corresponding recording_id and thus I cannot decompose them and save them separately because they do not contain recording information.

**Comment by pzelasko** [comment]
Since you know that cut == recording in your case, you can fix that manually before decomposition with

```python
for cut in cuts:
  cut.features.recording_id = cut.recording.id
```

**Comment by njellinas** [comment]
Ok, I thought that something like this would be automatic but it's OK.
