### ISSUE TITLE
Which feature extractor is equal to torchaudio.transforms.MelSpectrogram() in lhotse ?

### ISSUE THREAD

**Issue by kobenaxie** [lhotse-speech/lhotse#1425]

**Comment by csukuangfj** [comment]
I suggest that you have a look at the fbank features (without `log`).

Also, please list the detailed arguments to invoke `torchaudio.transforms.MelSpectrogram()`.

Not all arguments for `torchaudio.transforms.MelSpectrogram()` are supported in lhotse.

**Comment by kobenaxie** [comment]
> I suggest that you have a look at the fbank features (without `log`).
> 
> Also, please list the detailed arguments to invoke `torchaudio.transforms.MelSpectrogram()`.
> 
> Not all arguments for `torchaudio.transforms.MelSpectrogram()` are supported in lhotse.

@csukuangfj , Thank you for your suggestion, I'll take a look the details of fbank. And I used like this
```
torchaudio.transforms.MelSpectrogram(
        sample_rate=16000,
        n_fft=1024,
        hop_length=256,
        n_mels=80,
        center=True,
        power=1,
    )
```

**Comment by csukuangfj** [comment]
arw you doing tts?

**Comment by kobenaxie** [comment]
I am using Lhotse to try to reproduce the results of Vocos
