### ISSUE TITLE
Size of initial minibatch

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#146]
Piotr, in our snowfall eg with mini_librispeech, the 1st minibatch is 16 seconds long which seems on the long side.
Is that typical of the data, or are they arranged from longest to shortest?
.. because if we want them in a nonrandom order we probably want shortest to longest, which would be better for convergence.

**Comment by pzelasko** [comment]
They are randomly shuffled. There are also multiple cuts packed into a single batch example which might make the duration excessive. Do you think some curriculum learning like option would be useful (sorting by length, possibly for a number of first epochs)?

**Comment by danpovey** [comment]
I assume the length of the example is the length of the longest individual
cut?

**Comment by pzelasko** [comment]
By default it's twice of that (it helps the heuristic pack cuts better), but can be adjusted; see: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/speech_recognition.py#L136

**Comment by danpovey** [comment]
I think we should make it that by default, not twice of that, because for
many model types the time taken could be much more sensitive to the
sequence length than to the total number of frames in the sequence.
For attention models it can even take time quadratic in the num-frames.

**Comment by pzelasko** [comment]
Ok, will do. I wonder though, if it makes sense to concatenate the cuts for the attention models at all (unless these are subsequent utterances from the same recording/conversation).
