### ISSUE TITLE
Feature: CMVN

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#151]
It would be useful to have CMVN for feature transformation, including offline and online CMVN (per speaker or per utterance) as in Kaldi, and a simple sliding window CMVN (which can be just a wrapper around https://pytorch.org/audio/stable/transforms.html#slidingwindowcmn).

**Comment by pzelasko** [comment]
@desh2608 can you take a look at PR #159 ?

**Comment by desh2608** [comment]
@pzelasko LGTM.
