### ISSUE TITLE
"Executor" concept documentation

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#152]
Might be nice to have one place where "executor" is documented in full, and
have the documentation for individual uses explain it very briefly and
refer to that.
Possibly the same for other concepts.  Just an idea.

_Originally posted by @danpovey in https://github.com/lhotse-speech/lhotse/issues/150#issuecomment-733462813_

**Comment by pzelasko** [comment]
I accidentally pushed it to master, but it's a commit with just the docs, so I'll leave it be. @danpovey please check out if this description is clear https://lhotse.readthedocs.io/en/latest/parallelism.html

**Comment by danpovey** [comment]
Looks great!
There is a stray backtick.
