### ISSUE TITLE
Consistent use of torchaudio backend

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#153]
Currently, data preparation recipes seem to be mostly using the `sox` backend with the old metadata interface, which will be [deprecated soon](https://pytorch.org/audio/stable/backend.html#changes-in-default-backend-and-deprecation). Also, this may be incompatible sometimes with the `soundfile` based audio reader in the feature extraction (https://github.com/lhotse-speech/lhotse/blob/21ee3792cd7deb60f61164aac650c6dd7bc3a05d/lhotse/audio.py#L80). Perhaps we should use `sox_io` backend throughout?

**Comment by pzelasko** [comment]
Yeah we'll have to update some time soon, I'll do it once I have some more time (see also issue #79)

**Comment by desh2608** [comment]
Oh sorry I should have searched before creating a duplicate issue. Feel free to close this one since the older one is already active.
