### ISSUE TITLE
Speed perturbation (sp < 1) cuts out speech

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#166]
Since we're using "sox speed" and then "sox resample" with end up with a signal of a different duration than the original one. So far we've adopted WavAugment's default behavior of padding it with zeros (sp > 1) or truncating (sp < 1), but the latter can hurt ASR training. Example:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/15930688/102548502-c339b100-4088-11eb-9d96-61ae1b7a23a1.png">

I think the right way to go forward could be to make "perturb_speed" a method on `Recording`, and possibly `Cut` and `CutSet`. It will have to adjust the duration/num_samples attributes, and when applied on `Cut` it should also adjust the supervisions' duration.  The transform should be applied lazily during audio loading to avoid excessive storage. We'd probably have to store the transform information in the Recording object itself. If we choose to do it, this opens the door to eventually performing all time-domain data augmentation in the same manner (e.g. reverb can also make the signal longer).

We should also validate that the Cut does not contain any pre-computed features (or warn that we are "detaching" them from Cut). I guess it's okay to apply this transform to each track independently in MixedCuts. If a user calls this method twice, it would probably make sense to apply it twice (or raise an exception that don't support it which is easier at this point). 

@danpovey WDYT?

**Comment by danpovey** [comment]
Definitely agreed.. I assumed that was what  you were doing originally (i.e. also changing the with the supervision times).
