### ISSUE TITLE
Trasformation - reverberation + noise

### ISSUE THREAD

**Issue by cyrta** [lhotse-speech/lhotse#169]
Hi, 
I would like to help with the project and post pr with some code to simulate room, as a data augmentation. 
RIR generated on fly created with some predefined distribution and source-sink position.
I've seen [lazy loading audio transformation code](https://github.com/lhotse-speech/lhotse/pull/167). 
However, I would like to ask you Piotr and Dan how you see this type of augmentation inside lhotse.

**Comment by danpovey** [comment]
Sounds interesting but well have.to.decide.whether it makes more sense to
dump them to disk from a.separate.repo,to avoid excess dependencies.
My feeling is the fine detail in the RIR may not matter so much.  could
maybe start with code to apply RIRs?

**Comment by pzelasko** [comment]
Sounds good. Keep in mind that we'll need to be able to estimate how many samples are added due to reverberation to update the num_samples and duration in Recording/Cut manifests (without actually running it). I don't think we need to update the supervisions start/duration.

We could start with [torchaudio's libsox bindings for reverb](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/augmentation/torchaudio.py#L158) unless you had a more refined method in mind?

**Comment by pzelasko** [comment]
BTW there are 3 ways to perform data augmentation in Lhotse right now (WavAugment,  torchaudio's SoxEffectTransform via `augment_fn` API, and the newly introduced lazy mechanism). I will deprecate the first two in favor of the lazy mechanism, so going forward we'll probably be adding new augmentations as methods on `Recording`/`Cut`/`CutSet`. It's more work, but it seems the API is much more user friendly and bug-free (e.g. [see the diff here](https://github.com/k2-fsa/snowfall/pull/54/files)).

**Comment by desh2608** [comment]
@cyrta is there any update on this?

@pzelasko I see that there is a recipe available for MUSAN. Would it make sense to add a recipe for preparation of the [RIR corpus](https://www.openslr.org/28/) and then add a Cut method to convolve it with a selected RIR as lazy augmentation? For isotropic noises I suppose the `cut.mix()` method should work?

**Comment by pzelasko** [comment]
Thanks @desh2608, that makes sense to me. Note that we might want to eventually support multiple types of reverb methods: RIR-based, geometric-based (like pyroomacoustic), effect-based (like SOX), etc. so it makes sense to name it explicitly like `reverb_rir()`.

**Comment by cyrta** [comment]
I pause it some time ago. Potently I will have time in december to finish it up . 

having multiple will give people ways to select what they've been using. 
for me, recipe for RIR should be ok,  imho it needs to be precomputed before. However, using some methods you can even generate them on the fly. 

reverb_rir, reverb_pyroomacoustic, reverb_sox, reverb_vst  - those are good explicit names.

btw do you Piotr use torch_augmentation or pytorch audio  augmentation functions ? 
is there a way to just give callback to some custom private augmentation operation function ?

**Comment by pzelasko** [comment]
> btw do you Piotr use torch_augmentation or pytorch audio augmentation functions ?
> is there a way to just give callback to some custom private augmentation operation function ?

Yes, I do, and yes, there is. 

## If your augmentation doesn't affect supervision/recording/cut start/duration

1) You can use any torch transform/module or any third-party method by adding it into your task-specific dataset and simply applying it on examples in a batch.

2) If you're precomputing features and want to augment in time domain, there is `augment_fn` parameter to `cut_set.compute_and_store_features[_batch]` method.

## If the augmentation affects supervision/recording/cut start/duration

(e.g. speed perturb shrinks/stretches speech segments as well)

3) you have to integrate deeper with Lhotse -- follow examples of how `perturb_speed`, `perturb_tempo`, or `resample` are implemented. [This PR implemented `perturb_volume`](https://github.com/lhotse-speech/lhotse/pull/382) in a similar way and is a pretty good reference for where modifications are needed (and what should be tested).

**Comment by desh2608** [comment]
I am implementing reverberation with impulse responses, and the key step is block-wise convolution (between signal and IR) with overlap-add. It seems scipy has an implementation [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.oaconvolve.html) but considering that scipt isn't one of Lhotse's dependencies, perhaps I should adapt that implementation in Lhotse? Thoughts?

**Comment by pzelasko** [comment]
That's a good idea. We could add scipy as an optional dependency but having a dependency-free implementation would be cool. Especially if you can leverage PyTorch for batching, autograd, and CUDA acceleration (not sure if viable / too much work).
