### ISSUE TITLE
Why Lhotse support min pytorch=1.5.1?

### ISSUE THREAD

**Issue by shanguanma** [lhotse-speech/lhotse#177]
Why does lhotse limit such a high pytorch? I think it support  more pytorch version, it will be more helpful for user

**Comment by pzelasko** [comment]
I think some code might be relying on features introduced in a later version. E.g. speed perturbation requires 1.7, and I was going to bump even higher - but I can also remove the requirement in case some users only require partial functionality of Lhotse that would work anyway. 

I don’t know what is the right call, any thoughts?

**Comment by shanguanma** [comment]
Thanks for your reply.
Keep up with the latest pytorch version, there is nothing wrong, but there are too many hardware not so fast to follow up the pytorch version.
Because as a tool, I still hope to support not to raise the minimum version too high, which is not user-friendly

**Comment by shanguanma** [comment]
Yes,I see.
