### ISSUE TITLE
install error include <vector>          ^~~~~~~~ 1 error generated. error: Setup script exited with error: command 'gcc' failed with exit stat

### ISSUE THREAD

**Issue by wuxiaobo** [lhotse-speech/lhotse#179]
python3 setup.py install
Installed /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphfile-1.0.3-py3.7.egg
Searching for lilcom>=1.1.0
Reading https://pypi.org/simple/lilcom/
Downloading https://files.pythonhosted.org/packages/46/78/9605e17af46a789747544c66f69bcfba17d43ae12f7caeb82f10bbd3fbd5/lilcom-1.1.1.tar.gz#sha256=c0f114658d6408fd45267ca466fe1a5b09a3e4f0b5f902ef0ab6835bd98c3b01
Best match: lilcom 1.1.1
Processing lilcom-1.1.1.tar.gz
Writing /var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/easy_install-mygaf2wv/lilcom-1.1.1/setup.cfg
Running lilcom-1.1.1/setup.py -q bdist_egg --dist-dir /var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/easy_install-mygaf2wv/lilcom-1.1.1/egg-dist-tmp-8hkh083v
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from lilcom/lilcom_extension.cc:15:
In file included from lilcom/compression.h:6:
lilcom/int_stream.h:6:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by csukuangfj** [comment]
You are encountering the same problem for lilcom
 https://github.com/danpovey/lilcom/issues/29#issuecomment-755159377

Please find someone to help repair your compiler tools on your macOS.

**Comment by wuxiaobo** [comment]
g++ helloworld.cpp -o helloworld
./helloworld 
Hello, world!

**Comment by pzelasko** [comment]
I’m closing as it seems related to your machine rather than Lhotse (I saw there was more discussion in snowfall or k2)
