### ISSUE TITLE
High IO performance storage for features

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#18]
I'm putting this so that I don't forget - I have some reservations about storing a huge amount of feature files on the disk, the IO might get slow on network disks. We might want to look into some kind of storage format that's optimized for random access. Maybe [Apache Arrow](https://arrow.apache.org/) is a promising choice. I recall a project called [petastorm](https://github.com/uber/petastorm) developed by Uber for high data loading scalability (including distributed), but I'm not sure if it's usable for non-tabular data formats. There's also HDF5 which I think [can be tuned for the chunked storage layout](https://h5py.readthedocs.io/en/stable/high/file.html#chunk-cache).

**Comment by danpovey** [comment]
The problem, for me, is that that space is too fragmented.  Each big company has their own custom blob storage solution.  IMO the best way is to make the internal code 'separable' enough from the file I/O that it's easy to support arbitrary storage mechanisms.  Or have a text field that dictates the storage type and have separate backends.

**Comment by jtrmal** [comment]
I heard good feedback on HDF5, including the python bindings...
The positive part is, there are a lot of different tools and stuff like
that to work with it.
And it's been developed for scientific computing, IIRC
y.

**Comment by danpovey** [comment]
But isn't hdf5 more for structured data?  I don't know what it does when
you just have a bunch of blobs that are sequences of bytes.
And I thought it sat on top of a POSIX file system?  But I may be wrong now.

**Comment by jtrmal** [comment]
yes, it's a structured file -- can store matrices and other objects. Blobs
probably as well...
y.

**Comment by LordOfLuck** [comment]
There is an interesting [discussion on pytorch forums](https://discuss.pytorch.org/t/how-to-prefetch-data-when-processing-with-gpu/548/19) regarding data prefetching and sequential access to data blobs. An  interesting direction could be to use something like tf.Records. There is a [pytorch port](https://github.com/vahidk/tfrecord) for it too. It could also be useful to be compatible with [NVIDIA DALI](https://github.com/NVIDIA/DALI) project in the future. Just suggestions ;)

**Comment by jtrmal** [comment]
you probably don't want to base it on Tensorflow technology.
There's been a lot of work invested in HDF5 performance, which is data
storage format independent on vendor, AFAIK (albeit I don't know much more).
y.

**Comment by danpovey** [comment]
My feeling is it might make more sense to do it in Lhotse, e.g. enable some
kind of multi-threaded prefetch in a way that doesn't
depend on the storage format.

**Comment by pzelasko** [comment]
My guess is we'll just have to try a few things before we converge on something. Probably the key points to remember are:
- minimize the number of IO syscalls (less files),
- enable sequential (or block-sequential) reading of the data,
- since we can do on-the-fly feature-domain mixing (noise augmentation), maybe we don't need to fully randomize for each epoch,
- preferably the backend should be able to store raw bytes sequences (lilcom compressed arrays) which will significantly decrease the amount of data needed to read.

**Comment by pzelasko** [comment]
We merged initial HDF5 support #92, looking forward to feedback and contributions on this (we can easily add more backends or further optimize this stuff).
