### ISSUE TITLE
I/O speed comparison between kaldi orginal and lhotse

### ISSUE THREAD

**Issue by EyonJoshua91** [lhotse-speech/lhotse#183]
I was playing with lhotse recently. I have seen that the feature loading using lhotse is much slower than from original kaldi archive. I want to check whether this performance is expected or there is a better way to load features using lhotse.

Below is the designed experiment to show the speed comparison:
This small experiment is to extract fbank features from eval1 dataset of csj corpus, store it in the local drive, then load it from the local drive using combination. Different library and different storage types are used and compared. 

Related code block inside experiment notebook is shown below:

```
def collate_features_kaldiio(df):
    """
    Load features from a table where each entry records the feat_path
    """
    features = []
    indices = range(len(df))
    features = [kaldiio.load_mat(df['feat_path'][i]) for i in indices]
    return features

%%time
Load_from_kaldiio = collate_features_kaldiio(df_kaldi)
print("%i features are collacted"%(len(Load_from_kaldiio)))
print("Size to store lhotse features in Lilcom: %.2f MB"%(get_size("data_ori/dump/eval1_sp_all")))

##Output
##1272 features are collacted
##Size to store lhotse features in Lilcom: 51.34 MB
##CPU times: user 681 ms, sys: 104 ms, total: 785 ms
##Wall time: 790 ms
```

```
def collate_features_lhotse(cuts: CutSet):
    """
    Load features for all the cuts and return them in a list.
    """
    assert all(cut.has_features for cut in cuts)
    first_cut = next(iter(cuts))
    features = []
    for idx, cut in enumerate(cuts):
        features.append(cut.load_features())
    return features

%%time
Load_from_numpy_lhotse = collate_features_lhotse(cut_set_numpy)
print("%i features are collacted"%(len(Load_from_numpy_lhotse)))
print("Size to store lhotse features in numpy: %.2f MB"%(get_size("temp/numpy")))

##OutPut
##1272 features are collacted
##Size to store lhotse features in numpy: 379.73 MB
##CPU times: user 417 ms, sys: 5.58 s, total: 6 s
##Wall time: 6 s

%%time
Load_from_llc_lhotse = collate_features_lhotse(cut_set_llc)
print("%i features are collacted"%(len(Load_from_llc_lhotse)))
print("Size to store lhotse features in Lilcom: %.2f MB"%(get_size("temp/llc")))
print("Size to store lhotse features in numpy: %.2f MB"%(get_size("temp/numpy")))

##OutPut
##1272 features are collacted
##Size to store lhotse features in Lilcom: 108.10 MB
##CPU times: user 53.5 s, sys: 6.3 s, total: 59.8 s
##Wall time: 59.8 s
```

Result is summarized below:

| eval1 loading method          | number of features | storage size | process speed |
|--------------------------------------|--------------------|--------------|---------------|
| kaldi + Kaldiio                      | 1272               | 51.34 MB     | 764 ms        |
| lhotse  + CutSet + Lilicom   | 1272               | 36.03 MB     | 59.8 s      |
| lhotse + CutSet + numpy    | 1272               | 126.58 MB    | 6 s           |

Does the above storage size and speed look correctly? Is there any suggestion or plan on speed up the loading process?

**Comment by danpovey** [comment]
Mm, what kind of computer do you have?
It's possible that the lilcom decompression is slower than the Kaldi
decompression (since lilcom uses more complicated
and compute-heavy compression methods), that would add overhead, although
I'd be surprised if it was 80 times slower.

Kaldi tends to store files in large archives and it can avoid closing and
re-opening files; that can reduce the `sys` time,
although I'm surprised how much time it takes.  In the case of lilcom
compression, though, that part doesn't seem to dominate the
total time taken.

On the server-type machines where people tend to train, there tends to be a
lot of compute available relative to network bandwidth
(or disk bandwidth), which can mean the savings in network/disk bandwidth
and disk space might make sense.

**Comment by pzelasko** [comment]
Thanks, this is very interesting! Can you specify whether it used the default Lhotses storage backend (files in a directory tree) or HDF5? I second Dan’s question about the machine too (and is the disk HDD or SSD). 

I remember doing some benchmarks when implementing the HDF5 backend, which maybe favored it a bit, but they were not conclusive. Lilcom did indeed introduce a significant overhead in decompression, but I don’t think it was as large as the one you have observed. When I compared the two backends recently in Snowfall recipes, they seemed to perform mostly the same (typically the wait time for a batch is in the order of 1-3ms if you use 2 or more jobs for the dataloader). 

When I find some more time I’ll try to replicate your benchmark.
