### ISSUE TITLE
LJspeech recipe error: exceeded the bounds of its corresponding recording 

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#205]
The `prepare_ljspeech` recipe on version `lhotse==0.4.0` fails with the following error:
```
Traceback (most recent call last):
  File "examples/prepare_ljspeech.py", line 9, in <module>
    ljspeech = prepare_ljspeech("LJSpeech-1.1", "manifests")
  File "/home/jan/aligntts/venv/lib/python3.8/site-packages/lhotse/recipes/ljspeech.py", line 96, in prepare_ljspeech
    validate_recordings_and_supervisions(recording_set, supervision_set)
  File "/home/jan/aligntts/venv/lib/python3.8/site-packages/lhotse/qa.py", line 52, in validate_recordings_and_supervisions
    assert 0 <= s.start <= s.end <= r.duration, \
AssertionError: Supervision LJ001-0001: exceeded the bounds of its corresponding recording (supervision spans [0.0, 9.65501134]; recording spans [0, 9.65501133786848])
```
It runs fine on `lhotse==0.3.0`. There seems to be related a issue #201 - there is also **a rounding problem**.
I am looking into it now, but not sure where is the problem.

Edit:
 It seems like the duration of a [Recording](https://github.com/lhotse-speech/lhotse/blob/cd8ed4d2057f8d90da0362dd79331b6777af0086/lhotse/audio.py#L132) does not do the same rounding that [happens in Supervision](https://github.com/lhotse-speech/lhotse/blob/cd8ed4d2057f8d90da0362dd79331b6777af0086/lhotse/supervision.py#L25).

Supervision:
 ```
    @property
    def end(self) -> Seconds:
        return round(self.start + self.duration, ndigits=8)
```
Recording:
```
Recording(
            id=recording_id if recording_id is not None else sph_path.stem,
            sampling_rate=sphf.format['sample_rate'],
            num_samples=sphf.format['sample_count'],
            duration=sphf.format['sample_count'] / sphf.format['sample_rate'],
            sources=[
                AudioSource(
                    type='file',
                    channels=list(range(sphf.format['channel_count'])),
                    source=(
                        '/'.join(sph_path.parts[-relative_path_depth:])
                        if relative_path_depth is not None and relative_path_depth > 0
                        else str(sph_path)
                    )
                )
            ]
        )
```
Is it possible that there should also be rounding in the Recording? I cam make a PR for this :)

**Comment by pzelasko** [comment]
Thanks, that's a good catch. The issue is not present in Lhotse 0.3 because we didn't have the strict validation code then. I am pretty sure that we don't want to do rounding for Recording's duration - it is fairly accurate since it's computed from the number of samples. I think the supervision rounding was a half-measure to prevent `end` values such as 0.499999999999998, but I think there's really no good way to avoid that with floating-point numbers. 

Would you mind removing the rounding in supervision and adding a tolarenace of 1ms to that assertion (i.e. `-1e-3 <= s.start <= s.end <= r.duration +1e-3`)?

**Comment by janvainer** [comment]
Sure :) will make a PR today

**Comment by janvainer** [comment]
@pzelasko I added the changes, but it broke multiple tests for Cuts. The main problem is with the IntervalTree that is used to compute overlaps. The rounding errors cause some intervals to be dropped, while they should be included. This was not happenning before, because the rounding ensured that the values of edge interval points are exactly the same. I suspect that the rounding was added to ensure that the intervaltree works correctly.

How about adding the tolerance to assertion but keep rounding the numbers? I checked that the LJSpeech recipe works (after adjusting the frame_shift - the new checks do not allow it to use the default Fbank config.).

**Comment by pzelasko** [comment]
Yeah, as you can see this float rounding stuff is really delicate. Your suggestion sounds good to me.

**Comment by janvainer** [comment]
Yup, there seem to be some attempts to use the Decimal package for certain cases. Are there plans to support the `Decimal` solution globally?

**Comment by pzelasko** [comment]
I thought about it but I haven't analyzed yet how that would impact serialization/deserialization, overall speed and memory load (especially with a lot of objects around), and user experience. It could be a long-term solution though.
