### ISSUE TITLE
avoid duplicated computation of features

### ISSUE THREAD

**Issue by JerryPeng21cuhk** [lhotse-speech/lhotse#215]
Is it possible to skip the computation of features if it already exists just like: 
*read_manifests_if_cached* in dataset preparation ?

I am trying to figure out how to get FeatureSet after executing CutSet.compute_and_store_features so that I can store it as json(aka. feats.scp).

I am new to this excellent tool and still learning from it.

**Comment by JerryPeng21cuhk** [comment]
solved.

**Comment by pzelasko** [comment]
If you can think of some examples that would make it easier to get started with it, let me know. I'm going to prepare more tutorial material eventually and it'll be helpful.
