### ISSUE TITLE
Tool for batch visualisation

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#219]
I think it'd be good to have a tool/function (possibly jupyter-notebook exclusive to make things simpler) that can visualize the batches - display the spectrogram, mark the start/end of cuts, tracks in mixed cuts, and supervision segments. It will help with debugging/double-checking that the data is correctly prepared, collated, padded, and augmented. I don't think it's a lot of work with matplotlib to build, the biggest challenge is probably making it readable/informative for long cuts. Any suggestions are welcome.

**Comment by danpovey** [comment]
Agreed!
RE long cuts, one possibility would be to limit how many seconds it will display at one time, e.g. to 30 sec, and if it truncates, have it print a message saying how you could visualize the next piece.
