### ISSUE TITLE
Utility: "pessimistic" batch finder

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#231]
In training seq2seq models with a dynamic batch size, it can be sometimes difficult to ensure that there is not a single batch that will blow up GPU memory. It could be useful to add a utility to samplers to find the "most pessimistic" batch (I think that corresponds to the batch containing the longest utterances that can be formed given the max_frames constraint). Before the training, we could ran a forward + backward pass with that batch to get a fast fail in case it exceeds the GPU memory. Then, an easy fix for the user is either decreasing max_frames, or filtering out cuts that are too long.

**Comment by danpovey** [comment]
Good idea!

**Comment by danpovey** [comment]
... in some setups it might be the batches with the shortest utterances
that are problematic, might be a good idea to just schedule the longest and
shortest batches
right at the beginning.
