### ISSUE TITLE
GlobalMVN.from_cuts() fails with max_cuts option

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#244]
https://github.com/lhotse-speech/lhotse/blob/7fd0e70947fe35774763812f8438086b41afd4e6/lhotse/dataset/signal_transforms.py#L20

It should use a keyword arg in `compute_global_feature_stats(max_cuts=max_cuts)`, otherwise it assigns to `storage_path`. @janvainer do you mind fixing it and adding a test?

**Comment by janvainer** [comment]
Yes, I'll look into it.
