### ISSUE TITLE
Cannot import 'WavAugmenter'

### ISSUE THREAD

**Issue by jimbozhang** [lhotse-speech/lhotse#257]
Importing `WavAugmenter` fails in the latest version's Lhotse:

```
(venv) zhangjunbo@lhotse$ git log | head
commit 274cf876ee1e31ec8a837cbd5dc3b6f6bfdf2b79
Author: Jan Vainer <31015638+janvainer@users.noreply.github.com>
Date:   Mon Apr 5 19:42:19 2021 +0200
    Add LIbrosaFbank consistent with various TTS applications (#252)
    * Add LIbrosaFbank consistent with various TTS applications
    * Add mix and compute energy to LibrosaFbank and allow small frame difference
```

```
(venv) zhangjunbo@lhotse$ pip list | grep lhotse
lhotse                        0.6.0.dev0   /Users/zhangjunbo/src/lhotse
```

```
(venv) zhangjunbo@lhotse$ python
Python 3.9.2 (default, Feb 19 2021, 17:43:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

>>> from lhotse import CutSet

>>> from lhotse import WavAugmenter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'WavAugmenter' from 'lhotse' (/Users/zhangjunbo/src/lhotse/lhotse/__init__.py)
```

**Comment by pzelasko** [comment]
That’s correct - it was deprecated for some time now and I recently removed it. You can get identical functionality through `torchaudio.sox_effects`, see e.g. here: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/augmentation/torchaudio.py#L34

Just for my information - what kind of effects are you trying to use?

**Comment by jimbozhang** [comment]
I just noticed that the examples (librispeech, ami, ...) haven't been updated. I'll update them if needed.

> Just for my information - what kind of effects are you trying to use?

**Comment by pzelasko** [comment]
Oh yeah, the notebooks are a bit rotten by now. If you could update them based on how we use Lhotse in Snowfall, that would be awesome!
