### ISSUE TITLE
Traceability

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#260]
I think we need to add something to lhotse that will enable traceability of utterances.
The kinds of issues I am thinking about are:
 - If we want to transcribe a dataset for some downstream purpose, we'll typically want to preserve the relationship  between utterance-ids and the text.
 - For debugging, it's good to be able to look up the original utterance.
Right now, for instance, our lattices are getting very big for one particular utterance and it would be nice to be able to listen to it, but the data-loader doesn't come with that kind of info.  In this case we could figure it out from the transcript, but for very large datasets  or with short utterances, that wouldn't be possible.

**Comment by pzelasko** [comment]
Add `return_cuts=True` to the Dataset class arguments and it will return an additonal field called `cuts` indexed by `sequence_idx`.

**Comment by danpovey** [comment]
Great, thanks!
