### ISSUE TITLE
Loading CutSet from manifest may drop supervisions

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#263]
Calling `CutSet.from_manifests()` on pre-computed manifests may result in dopping supervisions. 
Steps to reproduce:

```
ROOT = "."
MANIFESTS = $(ROOT)/LJSpeech-1.1/lhotse_manifests
FEATS = $(ROOT)/LJSpeech-1.1/feats

lhotse obtain ljspeech $(ROOT)
lhotse prepare ljspeech $(ROOT)/LJSpeech-1.1/ $(MANIFESTS)

# Extract LibrosaFbank features
lhotse feat write-default-config $(MANIFESTS)/librosa_config.yaml -f librosa-fbank
lhotse feat extract \
$(MANIFESTS)/recordings.json \
$(FEATS) \
-f $(MANIFESTS)/librosa_config.yaml

# store cuts
lhotse cut simple $(MANIFESTS)/cuts.json \
-r $(MANIFESTS)/recordings.json \
-f $(FEATS)/feature_manifest.json.gz \
-s $(MANIFESTS)/supervisions.json
```
The stored cuts don't have supervisions. The problem is that the ends of the feature segments and ends of the supervision segments do not match, because Supervision.end [rounds to 8 digits](https://github.com/lhotse-speech/lhotse/blob/61177e48cbc2e53f83541ed8b301d4d4ab1b54da/lhotse/supervision.py#L27), but the Features.end does not.

The SupervisionSegment.find then does not match features with supervisions correctly in [SupervisionSet.find()](https://github.com/lhotse-speech/lhotse/blob/61177e48cbc2e53f83541ed8b301d4d4ab1b54da/lhotse/cut.py#L1286). 

I tried to disable the rounding, but it triggers the `test/cut/test_cut_truncate.py` test. Quick fix would be to round digits inside the find function or use some tolerance, but I am not sure if this would not break something else. WYT @pzelasko ?

**Comment by pzelasko** [comment]
I’ll look into it. Recently I’ve been able to overcome many such rounding issues, but probably haven’t updated all parts of the library.

**Comment by janvainer** [comment]
Thanks! LMK If I can help.
