### ISSUE TITLE
Features after SpecAugment go outside of supervisions

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#271]
Example:

![image](https://user-images.githubusercontent.com/15930688/114607995-320bcd00-9c6b-11eb-87c6-73744ef922db.png)

This is due to the "time warping" component of SpecAugment. I think we'll need to apply it before the padding instead. Interestingly, it improves the results on the 100h subset of LibriSpeech nevertheless.

**Comment by danpovey** [comment]
Cool!
