### ISSUE TITLE
compute_num_frames() seems to not return correct numbers

### ISSUE THREAD

**Issue by freewym** [lhotse-speech/lhotse#277]
I was following most of the  steps in compute_num_frames() to compute number of frames from raw audio. The only difference is that I obtain `num_samples`  directly from soundfile rather than by `round(duration * sampling_rate)`. But it looks like the value is consistently larger by 2 than the actual number of frames extracted from either Kaldi or `torchaudio.compliance.kaldi.fbank()`i.e.,  https://github.com/lhotse-speech/lhotse/blob/877f6dc0aa1fad7e40fc2e52fd579d26e66d6b8d/lhotse/utils.py#L204 
should be 
```python
 num_frames = int((num_samples + window_hop // 2) // window_hop) - 2
```
I was testing on LibriSpeech, frame_shift=0.01 and sampling_rate=16000

**Comment by pzelasko** [comment]
Did you specify `snip_edges=False`? I think it makes the number of frames independent on frame length/window size and simplifies the relationship between num frames and num samples. We decided to hard-code that setting in Lhotse early in its development.

**Comment by csukuangfj** [comment]
> But it looks like the value is consistently larger by 2 than the actual number of frames extracted from either Kaldi 

Kaldi uses `snip_edge==true` by default.

Lhotse is using snip_edge == False, like kaldi. See
https://github.com/kaldi-asr/kaldi/blob/cbed4ff688a172a7f765493d24771c1bd57dcd20/src/feat/feature-window.cc#L69

```cpp
    int32 num_frames = (num_samples + (frame_shift / 2)) / frame_shift;
```
