### ISSUE TITLE
Example data preparation recipes

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#28]
We should start creating example recipes for some data sets and tasks. I'll post an initial list here, and we can modify or extend it based on discussions. I'll sort it by the level of implementation difficulty.

## Source separation
- [x] (mini) LibriMix 

## Speech enhancement
_Should be fairly simple to achieve with source separation in place, maybe it's even already possible._
- [ ] (mini) LibriMix 

## Speaker identification 
_Could be simpler to build the first Dataset with supervision provided by SupervisionSegment than ASR._
- [ ] ? VoxCeleb 1/2 _(widely studied dataset)_

## TTS
- [x] LJSpeech

## ASR
- [x] (mini) Librispeech _(widely studied dataset)_
- [ ] ? Wall Street Journal _(widely studied dataset)_
- [x] 1997 Broadcast News
- [x] TED-LIUM v3
- [x] Switchboard _(conversational, two-channel)_
- [x] AMI _(conversational, multi-channel)_
- [ ] ? CHiME 6 _(conversational, multi-channel)_

## Wake word detection

- [x] Mobvoi HotWords

Feel free to propose any other tasks and datasets.

**Comment by danpovey** [comment]
This is great!  I think we should start with mini_librispeech for the ASR one (but the order of doing ASR vs. other things is up to you guys.)  @jimbozhang do you think you could commit to doing one of these?

**Comment by jimbozhang** [comment]
> This is great! I think we should start with mini_librispeech for the ASR one (but the order of doing ASR vs. other things is up to you guys.) @jimbozhang do you think you could commit to doing one of these?

I think I can make the recipe of (mini) Librispeech, as a start.

**Comment by danpovey** [comment]
Thanks!!

**Comment by judyfong** [comment]
@pzelasko I am interested in making a data preparation example for speaker diarization. Would that fall under both source separation and speaker identification? Within kaldi the diarization recipes use a combination of VAD and speaker identification essentially.

**Comment by judyfong** [comment]
Oh. I hadn't read that paper yet. It looks promising. 

It would still be nice to have the "classical" pipeline implemented for comparison purposes and as an example of how to change one's kaldi speaker diarization datasets/recipes to lhotse + k2/nn architectures. I'll await the contribution guide.

**Comment by pzelasko** [comment]
I'm closing this since we're tracking the corpora in the codebase and docs already. If anybody wants a new one added, please open a separate issue or submit a PR.
