### ISSUE TITLE
CLI command: dump truncated features from a truncated cut set

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#30]
Just curious about something... what would it take to re-dump the features from such a manifest?  E.g. suppose you were planning to train for many epochs and did not want to incur repeated extra I/O?

_Originally posted by @danpovey in https://github.com/pzelasko/lhotse/pull/24_

**Comment by pzelasko** [comment]
Clarification: a `Cut` may have a narrower [start, end] range than the `Features` object it points to. If we load, trim and dump the features to match the `Cut` range, we might get some I/O usage optimization during training by loading smaller feature matrices.

**Comment by pzelasko** [comment]
While doing this, we should (perhaps as an option) "resolve" the `MixedCuts` by loading, mixing, truncating, padding etc. as prescribed (simply call `mixed_cut.load_features()`), dump the resolved feature matrix, and dump a new CutSet that only contains "simple" (as in not mixed) cuts.

**Comment by danpovey** [comment]
Good idea.

**Comment by pzelasko** [comment]
I missed this issue when implementing this - it's already possible to do - call `cut_set = cut_set.compute_and_store_features(..., mix_eagerly=True)` (mix_eagerly is actually the default) and then `cut_set.to_json(...)`.
