### ISSUE TITLE
Save augmented/mixed audio

### ISSUE THREAD

**Issue by entn-at** [lhotse-speech/lhotse#314]
Hi,
I was wondering if there is currently a way to

1. Create a CutSet
2. Augment it and mix it with noise (CutSet of MixedCut, I guess)
3. Store the transformed audio to disk (and the CutSet with appropriate metadata)

Thus far, it seems the only way would be to create a custom `FeatureExtractor` that just stores the audio samples, but it wouldn't be possible to extract features from the resulting `FeatureSet`.

If it is currently not possible, would this be seen as a welcome enhancement?

Thanks,
Ewald

**Comment by pzelasko** [comment]
Hi Ewald,

Yes, it’s a welcome contribution. I believe this is exactly the same as https://github.com/lhotse-speech/lhotse/issues/150 — if that looks interesting to you, please submit a PR.

**Comment by entn-at** [comment]
Hi Piotr,
thanks, you're right, that issue is exactly the same. I will look into this!
