### ISSUE TITLE
Streaming feature extraction

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#338]
The current feature extraction methods in Lhotse are scaling poorly to long (~1h) inputs and eat up a lot of memory when processing them. The natural solution seems to be "streaming" / "chunking" extraction. Ideally, it would produce identical outputs as the "offline" one. Some thoughts:

- I don't think it's possible to have a truly generic wrapper for chunking the inputs that will work with arbitrary feature extractor (like librosa), sampling rates, and frame shifts -- external libraries might be doing the windowing differently than Kaldi's "snip_edges=False". 
- I really like how Kaldi designed the online feature pipelines, but it's a considerable effort to mirror that in Lhotse and I'm not sure there is real benefit from that (at least at this stage of k2 and snowfall); anyway, this should be designed to work well across all our libraries
- we might end up building a half-baked solution just to overcome these issues for specific sampling rates, frame shifts, and extractors to enable experimenting on large quantities of long recordings (e.g. GigaSpeech XL); I might have a prototype although it feels a bit too hacky to push into the codebase...

@danpovey @csukuangfj any thoughts?

**Comment by pzelasko** [comment]
... also I noticed that the torchaudio sox augmentation such as speed perturbation consumes a lot of memory for longer recordings, not sure if there's anything we can do about it though.

**Comment by sw005320** [comment]
Is there any situation that we need to process the long recording in the training stage (I'm expecting that speed perturbation is only performed in the training stage)?

**Comment by pzelasko** [comment]
I think even Kaldi (as an example of very efficient implementation) has to process the whole recording through sox for speed perturbation (unless you cut the recording explicitly into short audio files for each utterance); although that seems to be done in a streaming/memory-friendly way as I have not experienced OOM with it yet. Consider:

```bash
sp0.9-AUD0000000015 ffmpeg -i /export/corpora5/gigaspeech/audio/audiobook/P0001/AUD0000000015.opus -ar 16000 -f wav pipe:1 \
| sox -t wav - -t wav - speed 0.9 \
| sox --vol 1.98800028353 -t wav - -t wav - |
```

The reason why I want to extract the features for the whole recording (rather than utterances) is that I'd like to experiment with extending the acoustic context next to the utterances for training. It is much more convenient to read chunks of features extracted for the whole recording, than to re-compute them for each context size separately. On-the-fly extraction fails completely so far -- I am not aware of an off-the-shelf Python OPUS decoder that will let you read the audio in selected timestamps ([audioread uses ffmpeg which seems to read the whole thing](https://github.com/beetbox/audioread/blob/master/audioread/ffdec.py#L147)). OPUS can be converted to FLAC/sth else to amend this at the cost of storage but ideally it wouldn't be needed.

... upon some duckduckgo-ing, actually it seems that ffmpeg allows reading audio with offsets -- maybe that would enable the on-the-fly path, assuming it works for OPUS https://unix.stackexchange.com/a/1675

(anyway it is possible to extract the feats with augmentation with not-too-many-workers / some workarounds, it just takes a very long time and I'm looking to make this less painful for myself and others)

**Comment by csukuangfj** [comment]
>  it just takes a very long time and I'm looking to make this less painful for myself and others

How long does it take to compute fbank features of  a 1-hour sound file at present?

**Comment by pzelasko** [comment]
I think it is fairly quick at about 5 seconds on the CPIU -- it just takes ~4-5GB of memory in the process, so when you want to run 40 jobs like that it's 160-200GB and it scales quite poorly.

**Comment by csukuangfj** [comment]
@pzelasko 

Could you try https://github.com/csukuangfj/kaldifeat

It is compatible with kaldi's `compute-fbank-feats`, supports CUDA, batch processing, chunk processing, and autograd.

---

I just tested it to process a 1-hour sound file with chunks (chunk size 10 second). It consumes only several hundred MB.
The test code is at https://github.com/csukuangfj/kaldifeat/blob/master/kaldifeat/python/tests/test_fbank.py#L71

For easy reference, I post the code below:

```python
def test_benchmark():
    # You have to run ./test_data/run.sh to generate test_data/test-1hour.wav
    device = torch.device("cpu")
    #  device = torch.device('cuda:0')
    wave = read_wave("test_data/test-1hour.wav").to(device)
    opts = kaldifeat.FbankOptions()
    opts.frame_opts.dither = 0
    opts.device = device
    opts.mel_opts.num_bins = 80

    fbank = kaldifeat.Fbank(opts)

    # 1 seconds has 100 frames
    chunk_size = 100 * 10  # 10 seconds
    audio_frames = fbank.convert_samples_to_frames(wave)
    num_chunks = audio_frames.size(0) // chunk_size

    features = []
    for i in range(num_chunks):
        start = i * chunk_size
        end = start + chunk_size
        this_chunk = fbank.compute(audio_frames[start:end])
        features.append(this_chunk)

    if end < audio_frames.size(0):
        last_chunk = fbank.compute(audio_frames[end:])
        features.append(last_chunk)

    features = torch.cat(features, dim=0)

    # watch -n 0.2 free -m
    #  features2 = fbank(wave)
    #  assert torch.allclose(features, features2)
```

**Comment by pzelasko** [comment]
Thanks! I will test it and if it works well, I might add that to Lhotse as a permanent thing.

**Comment by pzelasko** [comment]
I made PR #339 that attacks the long-recording problem for OPUS with efficient chunk reads, enabling on-the-fly feature extraction without excessive I/O. I am still interested to look into pre-computing features on long recordings efficiently, will check it out later.

**Comment by csukuangfj** [comment]
> I really like how Kaldi designed the online feature pipelines, but it's a considerable effort to mirror that in Lhotse and I'm not sure there is real benefit from that (at least at this stage of k2 and snowfall); anyway, this should be designed to work well across all our libraries

I have wrapped it into kaldifeat. Please see <https://github.com/csukuangfj/kaldifeat/blob/master/kaldifeat/python/kaldifeat/online_feature.py>, which has the same interface as kaldi's online feature interface.

You can find its usage in the tests: https://github.com/csukuangfj/kaldifeat/blob/master/kaldifeat/python/tests/test_fbank.py#L16

**Comment by pzelasko** [comment]
Cool! I also added streaming feature extraction a while ago but with a different API that is stateless. I don’t think it would be possible to export kaldifeat as a part of a torchscripted model?

**Comment by danpovey** [comment]
I think we probably wouldn't use torchscript to export kaldifeat, we'd do it manually in the C++ code.
