### ISSUE TITLE
Unnecessary padding to audio samples in OnTheFlyFeatures

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#349]
See the code below
https://github.com/lhotse-speech/lhotse/blob/81b3a0d842787ec476ead2c255e5be0ee89eb0cb/lhotse/dataset/input_strategies.py#L233

https://github.com/lhotse-speech/lhotse/blob/81b3a0d842787ec476ead2c255e5be0ee89eb0cb/lhotse/dataset/input_strategies.py#L239-L242

The extra padding has the following side effects:
 - (1) Waste CPU during feature extraction.
 - (2) It affects the result of the last feature frame. That means the features of an utterance vary
with respect to the batch size (`--max-duration`).

**Comment by pzelasko** [comment]
Good catch, I guess it makes sense to first extract the features and then pad them. I'll make the relevant changes later (if you need it sooner feel free to do it).
