### ISSUE TITLE
Lhotse can not handle English Fisher sphere files

### ISSUE THREAD

**Issue by videodanchik** [lhotse-speech/lhotse#362]
Hi, recently I was trying to work around English Fisher (LDC2004S13, LDC2005S13) preprocessing scripts and faced with the problem that `audioread`  (which is used when `lhotse` forced to load sphere files) fails to load the sphere files from these corpora (actually both `torchaudio` and `lhotse` are failing). I would like to make a PR with English and Spanish (LDC2010S01) recepies. Is there any documentation on how to contribute?

**Comment by pzelasko** [comment]
Thanks, it would be great to have these recipes!

You are right about Fisher sphere files. They are compressed using an old codec called „shorten” that is not widely supported. There is a tool called `sph2pipe` (incidentally, released by the LDC) that knows how to decompress that. You can look up English CallHome recipe in Lhotse (link below) to see how to create Recording manifests that will use sph2pipe. Note that sph2pipe has to be separately installed and registered in the system’s PATH variable (e.g. like Kaldi is doing it). 

https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/callhome_english.py#L84

**Comment by pzelasko** [comment]
For contributing recipes, it’s generally best to start by copying a similar recipe and modifying it. We also have some pointers here: https://lhotse.readthedocs.io/en/latest/corpus.html#adding-new-corpora

**Comment by videodanchik** [comment]
> Thanks, it would be great to have these recipes!
> 
> You are right about Fisher sphere files. They are compressed using an old codec called „shorten” that is not widely supported. There is a tool called `sph2pipe` (incidentally, released by the LDC) that knows how to decompress that. You can look up English CallHome recipe in Lhotse (link below) to see how to create Recording manifests that will use sph2pipe. Note that sph2pipe has to be separately installed and registered in the system’s PATH variable (e.g. like Kaldi is doing it).
> 
> https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/callhome_english.py#L84

**Comment by videodanchik** [comment]
> For contributing recipes, it’s generally best to start by copying a similar recipe and modifying it. We also have some pointers here: https://lhotse.readthedocs.io/en/latest/corpus.html#adding-new-corpora

Thanks for the reply, but correct me if I'm wrong, In this case, I will wait for ages to compute features as for each `Cut` in a `CutSet` asmIt will load the whole audio first and apply offset later with `SoundFile`, this is going to be very inefficient especially if someone (like me) working with S3. I have a suggestion to modify your audio loader a little bit, in particular, I can add another `elif` statement to `lhotse.audio.read_audio()` (something like` if isinstance(path_or_fd, (str, Path)) and str(path_or_fd).lower().endswith('.sph'):`) and then pass offset duration and channel directly to `sph2pipe` command (according to sph2pipe documentation it is possible to specify start end and channel using `-s` and `-c` options). This will at least solve IO overhead for `.sph` files, but in general, the problem will remain for 'command' type sources.

**Comment by videodanchik** [comment]
> Thanks, it would be great to have these recipes!
> 
> You are right about Fisher sphere files. They are compressed using an old codec called „shorten” that is not widely supported. There is a tool called `sph2pipe` (incidentally, released by the LDC) that knows how to decompress that. You can look up English CallHome recipe in Lhotse (link below) to see how to create Recording manifests that will use sph2pipe. Note that sph2pipe has to be separately installed and registered in the system’s PATH variable (e.g. like Kaldi is doing it).
> 
> https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/callhome_english.py#L84

Thanks for the reply, but correct me if I'm wrong, In this case, I will wait for ages to compute features as for each `Cut` in a `CutSet` asmIt will load the whole audio first and apply offset later with `SoundFile`, this is going to be very inefficient especially if someone (like me) working with S3. I have a suggestion to modify your audio loader a little bit, in particular, I can add another `elif` statement to `lhotse.audio.read_audio()` (something like` if isinstance(path_or_fd, (str, Path)) and str(path_or_fd).lower().endswith('.sph'):`) and then pass offset duration and channel directly to `sph2pipe` command (according to sph2pipe documentation it is possible to specify start end and channel using `-s` and `-c` options). This will at least solve IO overhead for `.sph` files, but in general, the problem will remain for 'command' type sources.

**Comment by pzelasko** [comment]
Yeah, you are correct. You can look at how we handle chunked reads from OPUS, it also has a „special” treatment where it pretends to be a „file” source but actually spawns an ffmpeg subprocess with offset+duration args. I am OK with treating SPH files similarly. 

I think the only other solution is building a Python wrapper for sph2pipe — I looked into it, but their C code doesn’t clearly separate the CLI stuff from the actual functionality.

In general I am not sure what is the right solution for „command” and „url” type sources to support chunked reads. If you have any ideas feel free to suggest!
