### ISSUE TITLE
dev dependencies didn't get installed

### ISSUE THREAD

**Issue by songmeixu** [lhotse-speech/lhotse#368]
Install the development environment via `pip install -e '. [dev]'`, but when running librispeech.ipynb, errors are reported, e.g. "ipythoncore is not found" "matplotlib is not found", and I have to run the installation of the three dependencies again.

https://github.com/lhotse-speech/lhotse/blob/61375dc5d300c05e4c609a4682fdb7e8650747c9/setup.py#L55-L55

**Comment by pzelasko** [comment]
I think the issue could be in the whitespace between `.` and `[dev]`: could you try `pip install -e '.[dev]'`?
