### ISSUE TITLE
Samplers len() might need to be removed

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#373]
When working on #372, I noticed that there is an issue in calling `len(sampler)`. We currently compute len by iterating the sampler and caching the number of batches. However, the number of batches (i.e., len) may change when we shuffle the cuts. I don't think there is a really elegant way to provide len (we can't recompute it at the start of an iteration, because len itself calls `iter(sampler)`...). Unless anybody has some idea, I'll remove len from samplers.

CC @janvainer @danpovey @csukuangfj

**Comment by danpovey** [comment]
I agree that removing len() is probably the best option.
If an approximate length is really needed for something, perhaps we could
add a function that returns an approximated length.
