### ISSUE TITLE
RecordingSet.from_youtube_urls

### ISSUE THREAD

**Issue by oplatek** [lhotse-speech/lhotse#389]
Things to consider:
 - store license of youtube video - to be able to filter out recordings based on license
 - filter-out - live stream - we want to know the length of audio in advance - not to wait for the live videos to finish
 - support storage format parameters
 - timeout etc - connection parameters.

Note: That the list of URLs can be represented as RecordingSet with `AudioSource.type = "url"`and from_youtube_urls would just fetch the metadata

Consider using https://github.com/ytdl-org/youtube-dl/ 

Consider also a legal issue - good source is the [youtube-dl page itself](https://youtube-dl.org/)

CC: @ondrejklejch

**Comment by jtrmal** [comment]
I'd be very worried about making this thing (public) api due to licensing
and other issues.
y.

**Comment by pzelasko** [comment]
This sort of project could easily be set up as an external repo -- as @jtrmal notes I don't think Lhotse is a good place for this.
