### ISSUE TITLE
Supporting custom data (array/tensor) fields in cuts

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#393]
The main idea is that we want to be able to attach things like fbank, pitch, posteriors, alignments, etc. to the cuts in the same way we currently support `.features` and `.load_features`. This means a user could have a single cut object with multiple types of data. But we don't want to define all the possible attributes ahead of time.

The proposed syntax is inspired by pandas and k2 and would look like this:

```python
# attach feature manifest for fbank
cut.fbank = Features(...)
feats = cut.load_fbank()

# attach feature manifest for pitch
cut.pitch = Features(...)
pitch_feats = cut.load_pitch()

# attach a more generic array manifest
cut.posteriors = Array(...)
posts = cut.load_posteriors()

# and so on...
cut.alignment = Array(...)
ali = cut.load_alignment()

cut.ivector = Array(...)
ivec = cut.load_ivector()
```

This can be achieved with a little metaprogramming by overriding `setattr` like this (it's just pseudo-code):

```python
def __setattr__(self, key, value):
  self.key = value
  if isinstance(value, Array):
    method_key = f'load_{key}'
    self.method_key = ...  # assings a method that does the right thing
```

It'd also support serialization + deserialization to restore these attributes correctly. 

To support truncation, the `Array` manifest type would have a `shape` and `temporal_dim` attribute; if `temporal_dim` is None it means it's sth like an i-vector, otherwise we would use the `temporal_dim` to truncate that dimension.

For padding, it'd accept a user defined value. For mixing, `Features` support it already, and `Array` would raise an exception or a warning and strip out the attribute from the cut.

**Comment by danpovey** [comment]
Hm, interesting.
So if there is a `temporal_dim` I assume that means it has a frame rate (is this worked out implicitly from the
number of features?)

**Comment by pzelasko** [comment]
Yeah there needs to be a frame rate / frame shift

**Comment by csukuangfj** [comment]
```python3
def __setattr__(self, key, value):
  self.key = value
  if isinstance(value, Array):
    method_key = f'load_{key}'
    self.method_key = ...  # assings a method that does the right thing
```

Could you explain how the following statement works?
> elf.method_key = ...  # assings a method that does the right thing

---

> It'd also support serialization + deserialization to restore these attributes correctly.

Also, how would it support serialization and deserialization?

**Comment by pzelasko** [comment]
It's pseudo-code, it would do sth like calling the original `__setattr__` to add a member attribute/method to the object. The deserialization would find all the non-standard keys, and if their values are of type `Array`, it'd apply the same special logic to restore the added object attributes/methods.

The alternative is to have a field called `custom` or `attachments` of type `Dict[str, Array]` to which the "extra" manifests are added, and a `load(key: str)` function to read them (e.g. `cut.load('alignment')`, `cut.load('ivector')`). It's easier to implement but I think I like the former API more. WDYT?

**Comment by csukuangfj** [comment]
Can we do the following:

```python3
cut.xxx = Array(...)
cut.yyy = Array(...)
```

where `xxx` and `yyy` are arbitrary attributes. `Array` contains some meta data and an optional tensor.
The `meta data` can be the path to the actual data, while the tensor contains the actual value. It is optional
so that when the cut is serialized, the tensor won't be saved into the manifests, but it is saved into a separate file, like how features are saved.

If we want to access the tensor of `cut.xxx`, we just use `cut.xxx.data`. If `data` is currently None, we can
load it from disk by using the meta data contained in `Array`.

**Comment by pzelasko** [comment]
> Can we do the following:
> 
> ```python
> cut.xxx = Array(...)
> cut.yyy = Array(...)
> ```
> 
> where `xxx` and `yyy` are arbitrary attributes. 

👍🏻 up to this point

> `Array` contains some meta data and an optional tensor.
> The `meta data` can be the path to the actual data, while the tensor contains the actual value. It is optional
> so that when the cut is serialized, the tensor won't be saved into the manifests, but it is saved into a separate file, like how features are saved.

> If we want to access the tensor of `cut.xxx`, we just use `cut.xxx.data`. If `data` is currently None, we can
> load it from disk by using the meta data contained in `Array`.

The `cut.xxx.data` part is problematic; `Array` can span more data than the Cut, e.g. Array is posteriors for 0 - 300 seconds, and Cut refers to 15 - 25 seconds. In these cases, we want to do `cut.load_posteriors()` or `cut.load('posteriors')` so that cut auto-loads the right amount of data. On the other hand, calling `cut.posteriors.load()` would return the whole data. This behaviour is consistent with how cuts handle `load_features()` and `load_audio()` so far.

I think it's better to do `cut.load_xxx()` for this reason; as a separate feature of Lhotse we can think if it makes sense to cache the loaded tensors within the manifest objects, but I think of it as an orthogonal issue. 

I also think it's better to stick to explicit storage of data right now, i.e. explicitly using a `FeatureWriter`, with 

```python
array_manifest = writer.write(key, data)
cut.xxx = array_manifest
```
