### ISSUE TITLE
some error of converting the kaldi feats.scp to FeatureSet 

### ISSUE THREAD

**Issue by cdxie** [lhotse-speech/lhotse#402]
hi, when I use the command line to convert kaldi file to Lhotse manifests,I met a error:

/opt/conda/lib/python3.8/site-packages/lhotse/kaldi.py:132: UserWarning: Failed to import Kaldi 'feats.scp' to Lhotse: frame_shift must be not None. Feature import omitted.
  warnings.warn(f"Failed to import Kaldi 'feats.scp' to Lhotse: "

I want to know why limit the file "frame_shift"?

**Comment by pzelasko** [comment]
I think when I was writing the import I didn't realize that sometimes there exists a file called `frame_shift` (was it added in Kaldi recently?). Would you be interested in making a PR that checks if the file is present and only raises the warning otherwise?

**Comment by cdxie** [comment]
> I think when I was writing the import I didn't realize that sometimes there exists a file called `frame_shift` (was it added in Kaldi recently?). Would you be interested in making a PR that checks if the file is present and only raises the warning otherwise?

Thanks，the frame_shift is always in  Kaldi data dir. I am a newer to use lhotse，and I read the code carefully, I find you use " -f " to replace the file called "frame_shift".  It is work

Another iusse: i find use "lhotse kaldi import data/train 16000 train_manifests" to convert kaldi file to Lhotse manifests is very slow(20000 sentences test), so how to speed up?

**Comment by pzelasko** [comment]
Sorry, I missed your message before. It is probably slow because it's reading wav.scp entries to find out the num samples and duration. I think a `num_jobs` options could be added to the script to process wav.scp in parallel.

**Comment by pzelasko** [comment]
The `num_jobs` option was added in https://github.com/lhotse-speech/lhotse/commit/2ed46106eb5d877404022a73cc9391b9ff43b9d6
