### ISSUE TITLE
cut_transforms changes cut.id

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#404]
`cut_transforms`, e.g., `mix`, will assign a new, randomly generated, id to the resulting cut.

The issue is that I am using `cut.id` to identify the alignment of a cut. Alignments are pre-generated and
during training, they are read from the disk. But `cut.id` is changed due to `cut_transforms`, which makes
it impossible to associate a cut with its alignment.

Is it possible to use the id of the reference cut as the resulting cut while performing `cut_transforms`?

**Comment by pzelasko** [comment]
Good point the ID thing also bothered me. I’ll scan the code base and try to add a preserve_id option where applicable.

**Comment by csukuangfj** [comment]
icefall is using only `CutMix` transform if we disable `--concatenate-cut`.
Wondering if you are working on this? If you don't have time, I would like to add `preserve_id` to the `mix` operation
so that I can use pre-computed alignments in LF-MMI training.

**Comment by pzelasko** [comment]
I can do it tomorrow, if you need it sooner then feel free to make a PR.

**Comment by csukuangfj** [comment]
> I can do it tomorrow, if you need it sooner then feel free to make a PR. 

Thanks, I will wait.

**Comment by pzelasko** [comment]
I merged it in Lhotse https://github.com/lhotse-speech/lhotse/pull/405

and released a new version to pypi
