### ISSUE TITLE
encoding of Chinese character

### ISSUE THREAD

**Issue by cdxie** [lhotse-speech/lhotse#409]
Hi,I am learning to use the lhotse to process my own data, the text of my data is Chinese character. I often use kaldi, so I use the command line to convert kaldi file to Lhotse manifests, in the process of converting,I find the Chinese character was encoded like "\u542c\u5230", this is not what I want. I give some example:

kaldi text:
20040527_210939_A901153_B901154-A-000281-000641	喂 你好 能 听到
20040527_210939_A901153_B901154-A-000974-001262	呃 可以 呀
Lhotse manifests supervisions.jsonl
{"id": "20040527_210939_A901153_B901154-A-000281-000641", "recording_id": "20040527_210939_A901153_B901154-A", "start": 2.81, "duration": 3.6, "channel": 0, "text": "\u5582 \u4f60\u597d \u80fd \u542c\u5230", "speaker": "20040527_210939_A901153_B901154-A"}
{"id": "20040527_210939_A901153_B901154-A-000974-001262", "recording_id": "20040527_210939_A901153_B901154-A", "start": 9.74, "duration": 2.879999999999999, "channel": 0, "text": "\u5443 \u53ef\u4ee5 \u5440", "speaker": "20040527_210939_A901153_B901154-A"}

So, how to make the Chinese character display like the kaldi text character ?

**Comment by pzelasko** [comment]
How did you display the contents of Lhotse manifest (ie what editor / command)? It seems to me the data is OK, just rendered in a different way.

**Comment by pzelasko** [comment]
Please re-open if the issue persists.
