### ISSUE TITLE
tensor device type incompatibility in Kaldifeat

### ISSUE THREAD

**Issue by EmreOzkose** [lhotse-speech/lhotse#451]
Hi,

I run [compute_fbank.py](https://github.com/k2-fsa/icefall/blob/810b193dcc3ad3f7a65bc3def63493711c9a084e/egs/librispeech/ASR/local/compute_fbank_librispeech.py#L82) and specified extractor as

`KaldifeatFbankConfig(device='cuda:0')`

But, I got below error. 

```
Traceback (most recent call last):
  File "extract_feature.py", line 15, in <module>
    features = fbank(wave)
  File "/path/to/anaconda3/envs/general/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/anaconda3/envs/general/lib/python3.8/site-packages/kaldifeat-1.10-py3.8-linux-x86_64.egg/kaldifeat/offline_feature.py", line 75, in forward
    features = self.compute(strided, vtln_warp)
  File "/path/to/anaconda3/envs/general/lib/python3.8/site-packages/kaldifeat-1.10-py3.8-linux-x86_64.egg/kaldifeat/offline_feature.py", line 111, in compute
    features = self.computer.compute_features(x, vtln_warp)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

One solution could be adding [`to(device)`](https://github.com/csukuangfj/kaldifeat/blob/632098e0c1fbbae04bbb7d593c2ba1cdbf9b00a7/kaldifeat/python/kaldifeat/offline_feature.py#L72), but it requires changing this [line](https://github.com/lhotse-speech/lhotse/blob/9b6e3e454667c067a2de70721cb771b02d1ae3b2/lhotse/features/kaldifeat.py#L119) as well (adding .cpu()).

**Comment by pzelasko** [comment]
The method you’re using to compute features doesn’t support CUDA — replace the method you’re using here: 

https://github.com/k2-fsa/icefall/blob/810b193dcc3ad3f7a65bc3def63493711c9a084e/egs/librispeech/ASR/local/compute_fbank_librispeech.py#L82

with `cuts.compute_and_store_features_batch`

https://github.com/lhotse-speech/lhotse/blob/9b6e3e454667c067a2de70721cb771b02d1ae3b2/lhotse/cut.py#L3358-L3390

**Comment by EmreOzkose** [comment]
Thank you :).
