### ISSUE TITLE
Add debug log for `setup.py` to track torch/torchaudio versions

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#465]
Hmm, managing the right torchaudio version definitely seems tricky..

I don't understand why it selected `torchaudio==0.9.0` out of all versions; if it went for the latest, it'd install 0.10.0 instead. This is the relevant `setup.py` code in latest pip released version (0.11); I can't see what's going wrong. 

https://github.com/lhotse-speech/lhotse/blob/6d60f333da89abc3c2836f395f95ae9d53ca5cd0/setup.py#L150-L171

Maybe I can add some logging utils for this controlled via env var (`LHOTSE_DEBUG_INSTALL=1 pip install lhotse`) so that we can debug it more easily after the next release..

_Originally posted by @pzelasko in https://github.com/lhotse-speech/lhotse/issues/399#issuecomment-966363101_

**Comment by mthrok** [comment]
(If this turns out to be an issue on torchaudio packaging / publishing, feel free to file an issue on torchaudio.)

**Comment by pzelasko** [comment]
I don't think it is. TBH I think it was a mistake to try to install torchaudio for the users, if they already have PyTorch. In #466 I'm changing setup.py to only allow installation if both torch and torchaudio are present, or none of them are present. If there is only torch, we'll raise an informative error.
