### ISSUE TITLE
size mismatch when using `collate_custom_field`.

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#478]
In `icefall`, when we say `subsampling_factor` is 4, we mean
```
num_output_frames = ((num_input_frames - 1 ) // 2) - 1) // 2
```

But in `lhotse`, I think it assumes
```
num_output_frames = round(num_input_frames / 4)
```

I just encountered the following problem. Suppose a `CusSet` has 2 cuts:
- cut 1:
  - duration: 4.9 seconds, num_frames: 490, after subsampling by a factor of 4 in `icefall`, it has 121 frames
  - A custom field is attached to it, named `label_alignment`, which has 121 frames
  
- cut 2:
  - It has two cuts, a MonoCut and a PaddingCut
  - The MonoCut has duration: 4.895 seconds, num_frames 490, after subsampling by a factor of 4 in `icefall`, it has 121 frames
  - A custom field is attached to it, named `label_alignment`, which has 121 frames
  - There is a PaddingCut with a duration 0.005 seconds

While loading `cut 1`, it returns an array of shape `(121,)`, see the code below
https://github.com/lhotse-speech/lhotse/blob/7c1e3bd33f3b1ef23b67ee3c2e70443bf302e655/lhotse/cut.py#L835-L837

While loading `cut 2`, it will pad 2 extra frames, which returns an array of shape `(123,)`, see the code below
https://github.com/lhotse-speech/lhotse/blob/7c1e3bd33f3b1ef23b67ee3c2e70443bf302e655/lhotse/cut.py#L1849-L1861
https://github.com/lhotse-speech/lhotse/blob/7c1e3bd33f3b1ef23b67ee3c2e70443bf302e655/lhotse/array.py#L285-L287

The consequence is that it throws in the following code while trying to stack the above arrays.
https://github.com/lhotse-speech/lhotse/blob/7c1e3bd33f3b1ef23b67ee3c2e70443bf302e655/lhotse/dataset/collation.py#L227-L228

```
    tensors = torch.stack([torch.from_numpy(c.load_custom(field)) for c in cuts])
RuntimeError: stack expects each tensor to be equal size, but got [121] at entry 0 and [123] at entry 1
```

**Comment by csukuangfj** [comment]
Can we just return a list of arrays and let the user do the padding?

**Comment by pzelasko** [comment]
I knew it! It was going too easy so far. I'll need some time to think how to address this properly; for now, instead of using `collate_custom_field`, you can do sth like `arrs = [cut.load_xxx() for cut in cuts]` and collate yourself.
