### ISSUE TITLE
Save audio function

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#485]
I wonder if it would be useful to have a `save_audio()` method for the cuts and recordings? Currently I just use torchaudio, but perhaps we can just have a wrapper around the torchaudio function.

**Comment by jtrmal** [comment]
sounds useful to me
y.

**Comment by pzelasko** [comment]
It’s called “compute_and_store_recording” but maybe it’s not the best name. It’s because it triggers all the computation from lazy transforms.. do you think we should rename it?

**Comment by jtrmal** [comment]
how about save_computed_audio or save_transformed_audio?
I do not have strong opinion, just slacking around, but "store" wouldn't
exactly make me believe that is the function I want to save something to
disk :)
y.

**Comment by pzelasko** [comment]
It's not necessarily computed or transformed, could be the same as the original one. `save_audio` makes sense to me, but I think the "old" name should not be removed but just deprecated with a warning, as some people are using it. If any of you would like to go for it, please make a PR.

**Comment by desh2608** [comment]
Closing since this is now added in https://github.com/lhotse-speech/lhotse/pull/486.
