### ISSUE TITLE
Support speed perturbing in a parallelized way

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#488]
The XL subset of GigaSpeech contains 10k hours of data. Doing speed perturb on it sequentially is really time-demanding.

**Comment by pzelasko** [comment]
I am going to look again broadly into GigaSpeech audio/feature handling because multiple people ran into issues recently. 

Do you mean speed perturbation implemented as a torch.nn.Module? I can check if it’s possible to do that with torchaudio, otherwise we might need sth custom.

**Comment by csukuangfj** [comment]
It turns out the speed perturb part takes about 30 minutes for the XL subset.

However, `trim_to_supervisions()` takes more time, which is about 42 minutes. Also, the resident memory goes up from 20 GB to 36 GB after this operation.

I am using 10 workers in the dataloader and don't have OOM so far.
(Note: I have removed `-threads 1` from ffmpeg that you added some time ago)

![Screen Shot 2021-11-27 at 12 28 42](https://user-images.githubusercontent.com/5284924/143667998-7e1d6269-3659-499c-82df-10ebe2a68a17.png)
![Screen Shot 2021-11-27 at 12 29 08](https://user-images.githubusercontent.com/5284924/143668007-33671499-3f79-48b1-bac8-2dd4b5b0fa83.png)


I am using https://github.com/k2-fsa/icefall/pull/120

The GPU is idle most of the time. I think the bottleneck is decoding the opus files.

**Comment by csukuangfj** [comment]
The memory consumed so far is rather stable.
![Screen Shot 2021-11-27 at 12 49 32](https://user-images.githubusercontent.com/5284924/143668410-9ab524d8-f2e6-4d07-9b0b-1355e6e09bbc.png)
![Screen Shot 2021-11-27 at 12 50 21](https://user-images.githubusercontent.com/5284924/143668412-721c07e1-837b-4284-994e-0f5e60be3b1f.png)
![Screen Shot 2021-11-27 at 12 51 22](https://user-images.githubusercontent.com/5284924/143668429-147cd000-c62a-485b-85e4-c7aaf36ffd41.png)

**Comment by pzelasko** [comment]
So everything seems to work? Even if that's true, if you can tell me what were the "rough edges" you went through with GigaSpeech, I can try to improve the handling of this data.

**Comment by pzelasko** [comment]
Is this resolved (i.e., did it turn out the inefficiencies were elsewhere)?

**Comment by csukuangfj** [comment]
> Is this resolved (i.e., did it turn out the inefficiencies were elsewhere)?

I didn't re-test the time for speed perturbing as it needs to run only once.

---

> So everything seems to work? Even if that's true, if you can tell me what were the "rough edges" you went through with GigaSpeech, I can try to improve the handling of this data.

Yes, everything works fine so far. The two key points I have found are that:

1. Split the manifest into smaller pieces. Otherwise, it is easy to get OOM on CPU as the manifest itself occupies too much RAM.
2. Disable caching for reading audios.  Otherwise, if a piece has many long utterances, it is also easy to get OOM on CPU.

**Comment by pzelasko** [comment]
Thanks. I disabled the cache by default, after some time and battle-testing I don't think it makes sense to keep it on, otherwise it can overwhelm training memory without a good reason. It can still be explicitly enabled though.
