### ISSUE TITLE
Bug: Computing features with LibrosaFbank fails because lhotse reads audio into torch tensors

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#490]
Hi, LibrosaFbank fails when computing features.

```
from lhotse.dataset import OnTheFlyFeatures
from lhotse.features.librosa_fbank import LibrosaFbank, LibrosaFbankConfig


ext = LibrosaFbank(LibrosaFbankConfig(
    sampling_rate=24000,
    fft_size=2048,
    hop_size=300,
    win_length=1200,
    window="hann",
    num_mel_bins=80,
    fmin=80,
    fmax=7600,
))
strat = OnTheFlyFeatures(ext)
```

And extracting for some cuts:
```
feats, lens = strat(cuts.resample(24000))
```

The function that loads audio under the hood casts numpy arrays to tensors: https://github.com/lhotse-speech/lhotse/blob/a6c393602469e96f4255347b6c19fd34b2d2dbe7/lhotse/dataset/collation.py#L411
I can make a fix to convert to numpy for this particular case. :)

Other feature types probably have wrong type annotations - expecting numpy arrays while in fact working with torch tensors. See eg this https://github.com/lhotse-speech/lhotse/blob/a6c393602469e96f4255347b6c19fd34b2d2dbe7/lhotse/features/fbank.py#L59. Should I fix those too?

**Comment by pzelasko** [comment]
As a temporary fix set this flag use_batch_extract=False in OnTheFlyFeatures, I’ll try to think of a clean solution.

**Comment by pzelasko** [comment]
@janvainer see if this PR fixes it for you https://github.com/lhotse-speech/lhotse/pull/492
