### ISSUE TITLE
Split manifest into pieces with equal durations

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#500]
I find that `lhotse split` splits a manifest into a given number of splits and each split contains as many utterances as others.

One issue is that utterances are of different durations. Utterances in some split are all long utterances, while utterances
in some other splits are all short utterances. 

This makes the feature extraction time for different splits varies significantly.

Is it possible to add an option to balance the duration of utterances in different splits?

**Comment by pzelasko** [comment]
How about shuffling the cuts before splitting, like `cuts.shuffle().split()`?

**Comment by csukuangfj** [comment]
Yes, I think that would make the distribution of duration more uniform.
