### ISSUE TITLE
Concatenate supervisions, + expand supervision to cut

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#502]
Can we add a feature to Lhotse to concatenate all supervisions in a cut, so that the text is concatenated
and the time is just the minimum enclosing interval?   I assume this would be a member of Cut, and also
a transform.  I think this might lead to better generalization.
Also, as it is, if we use transformer models, we can't really deal with multiple supervision segments in an utterance
due to issues with masks.

Could we also have a feature/transform to expand the supervision to cover the entire cut it belongs to.

To one of these, it would be nice to have an option to create an empty supervision if there were no supervisions
 in the cut.  (Or this could be a separate function/transform).

**Comment by pzelasko** [comment]
For the first part, see https://github.com/lhotse-speech/lhotse/pull/503 -- there's a lot of cases where merging supervisions is not well defined (different speakers, languages, overlapping transcripts, etc.) so this is a best-effort approach to make it work.

I'll add the expanding and empty supervision options later.

**Comment by pzelasko** [comment]
See https://github.com/lhotse-speech/lhotse/pull/505 for "filling" cuts with supervision. It allows both expanding and shrinking (but by default will raise an exception for the latter).

**Comment by danpovey** [comment]
Great!
@csukuangfj When these are done, would you mind running an experiment on Librispeech where we try to enable cut concatenation with concatenation of supervisions?
I am not sure whether the part about "filling" the cut with supervision will make a difference on Librispeech since the cuts may be the entire recordings(??)

**Comment by csukuangfj** [comment]
Yes, sure.

**Comment by pzelasko** [comment]
Both PRs have review addressed and are merged now; feel free to give it a go. You are right that you likely won't need to "fill" the cuts for LibriSpeech, unless you want to explicitly include the padding / MUSAN noise in the loss computation.

Also note you may want to try smaller `gap_duration` values for cut concatenation; I made it 1 second (100 frames) by default to be on the "safe" side, but now it seems excessive to me. I would expect ~300ms should be just fine or maybe even less?
