### ISSUE TITLE
Ignore_id with encodings

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#506]
I'm no sure if this is an issue, but creating one just in case:
Our plan with the encodings is to save them as byte arrays.
I just want to make sure this doesn't cause an issue with the ignore_id, assuming we
use a negative value for positions that correspond to padding.  (I assume such things happen
when collating the batch).
It might be necessary to convert to a different integer type at some point, e.g. to long,
which we'll eventually need in any case for indexing purposes.

**Comment by pzelasko** [comment]
Since `custom_collate_field` returns a tuple of `(collated_tensors, collated_tensor_lengths)`, it should be OK to ignore the padding values completely by using the length tensor e.g. to construct a mask, or replace with a different value later after casting to a larger dtype. Would that solve the issue?

**Comment by pzelasko** [comment]
See: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/collation.py#L266

**Comment by danpovey** [comment]
I think it would be best to detect cases where the padding value does not fit in the dtype (e.g. if dtype is unsigned, e.g. torch.uint8), and promote to a type that will fit the padding value.  In fact I think it would be reasonable to just promote all integer types that are not torch.long, to torch.long, since that is the type that can be used in torch indexing.

**Comment by pzelasko** [comment]
See https://github.com/lhotse-speech/lhotse/pull/507
