### ISSUE TITLE
ICSI Recipe - Missing channels? 

### ISSUE THREAD

**Issue by LasseWolter** [lhotse-speech/lhotse#551]
I was wondering why channels `A-D` aren't included in the channel mappings:
https://github.com/lhotse-speech/lhotse/blob/bbad9b82a1e9b7f45b234ae0eacec60b3c6bd8ee/lhotse/recipes/icsi.py#L128-L133

This causes the download script to not download these channels even though they are used by participants: 
e.g. the last participant in `Bdb001.mrt`
```
    <Participants DB="icsi1.spk">
      <Participant Name="mn017" Channel="chan1"/>
      <Participant Name="me001" Channel="chan2"/>
      <Participant Name="me011" Channel="chan3"/>
      <Participant Name="me018" Channel="chan4"/>
      <Participant Name="fe008" Channel="chan8"/>
      <Participant Name="fe016" Channel="chanB"/>
    </Participants>
``` 

Is there a specific reason why you left out those channels?

**Comment by desh2608** [comment]
Thanks for pointing out. This is definitely an oversight. I have mainly been working with the SDM and MDM settings recently, so I didn't notice that some IHM recordings may be missing in the recipe. Could you create a PR to fix this? If not, I'll do it next week.

**Comment by LasseWolter** [comment]
Yes, I'm looking into it now because I'm working with IHM settings.

**Comment by LasseWolter** [comment]
Check  #555

**Comment by LasseWolter** [comment]
thanks to the `download_icsi` function you can just rerun the function and the missing channels will be downloaded. 
Thanks for this ease of use @pzelasko ! :clap:
