### ISSUE TITLE
duration param in extract_from_recording_and_store

### ISSUE THREAD

**Issue by armusc** [lhotse-speech/lhotse#567]
Hi

in extract_from_recording_and_store in base.py
shouldn't be better to have

duration=duration if duration is not None else recording.duration

rather than
duration=recording.duration

otherwise why are we giving the duration as an argument (I actually needed that for my experiment but maybe it's not intended to be used that way)

**Comment by pzelasko** [comment]
It looks like a bug, what you're suggesting seems correct. Do you mind making a PR with your fix and a unit test to check that it's doing the right thing?

**Comment by desh2608** [comment]
Closed via https://github.com/lhotse-speech/lhotse/pull/572.
