### ISSUE TITLE
Why doesn't Fbank-extractor use GPU? 

### ISSUE THREAD

**Issue by LasseWolter** [lhotse-speech/lhotse#575]
Is there a way to use the GPU for Fbank-Feature-extraction by passing any parameters? 

From looking at it, I think I'd have to change the code itself. E.g. this file:
https://github.com/lhotse-speech/lhotse/blob/master/lhotse/features/kaldi/extractors.py

What's your opinion about this? Did you not allow this on purpose?

**Comment by pzelasko** [comment]
Yes, if you use kaldifeat library (`KaldifeatFbank` class in Lhotse) and `CutSet.compute_and_store_features_batch`.
