### ISSUE TITLE
Bug in `CutSet.sample()`

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#588]
Currently, the random ids are generated by calling `randint()` for `n_cuts` times, and then these ids are selected from the cuts. There are 2 possible issues here:

1. When `n_cuts` is larger than `len(cuts)`, this will definitely produce repeated cut ids, which leads to an `AssertionError` in `index_by_id_and_check` at the time of `CutSet` creation.
2. Even when `n_cuts` is smaller than `len(cuts)` but sufficiently large, repeated ids are very likely to be produced.

I think this line 
https://github.com/lhotse-speech/lhotse/blob/1e06fffec2ed5a023c524347a2d5486a20e27df5/lhotse/cut.py#L3939
should be changed to
```python
cut_indices = random.sample(range(len(self)), min(n_cuts, len(self)))
```
to fix this.

If you agree, I will make a PR with this change. (I am not sure how this would affect the samplers etc.)

**Comment by pzelasko** [comment]
Thanks, I think you're right. It won't affect the samplers, they do not use this method, instead they iterate over the whole cutset.
