### ISSUE TITLE
Bug in `MonoCut::from_dict`

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#590]
Currently, if we have a `MonoCut` named `cut`, the following code:
```python
data = cut.to_dict()
cut2 = MonoCut.from_dict(data)
```
results in `TypeError: __init__() got an unexpected keyword argument 'type'`. This is because `to_dict()` saves the class type under `type`, but this field is not expected in `from_dict()` deserialization.

This can probably be fixed by adding
```python
data.pop("type", None)
```
in `from_dict`.

**Comment by pzelasko** [comment]
Good idea, can you add it?

**Comment by desh2608** [comment]
Fixed in https://github.com/lhotse-speech/lhotse/pull/591
