### ISSUE TITLE
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

### ISSUE THREAD

**Issue by eggplant95** [lhotse-speech/lhotse#594]
Hi, I met this error while using development installation
`pip install -e '.[dev]'`
my numpy version is 1.21.5 

> Requirement already satisfied: numpy>=1.18.1 in /mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages (from lhotse==1.0.0.dev0+git.c697a05.clean) (1.21.5)

but when I was importing lhotse

> \>>> import lhotse
> RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/__init__.py", line 4, in <module>
>     from .cut import CutSet, MonoCut
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 33, in <module>
>     from lhotse.features import (
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/__init__.py", line 1, in <module>
>     from .base import (
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/base.py", line 19, in <module>
>     from lhotse.features.io import FeaturesWriter, get_reader
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/io.py", line 7, in <module>
>     import lilcom
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lilcom/__init__.py", line 2, in <module>
>     from .lilcom_interface import compress, decompress, get_shape
>   File "/mypath/install_dir/anaconda3/envs/k2/lib/python3.8/site-packages/lilcom/lilcom_interface.py", line 3, in <module>
>     from . import lilcom_extension
> ImportError: numpy.core.multiarray failed to import

My other packages need numpy<1,22, Is there any way I can compile lhotse with a lower version of numpy?

**Comment by pzelasko** [comment]
Try replacing this line https://github.com/lhotse-speech/lhotse/blob/c697a05ed76b92e1357d69cf7ffc765722a40374/setup.py#L135 with just `"numpy",` then `pip uninstall lhotse`, `pip uninstall numpy`, install numpy with the version you need and install Lhotse again. Run all tests with `pytest .` If it works, LMK what is the min numpy version that works (you can make a PR).

**Comment by pzelasko** [comment]
BTW you might also need to uninstall `lilcom` because it seems to have been compiled against a specific numpy version.

**Comment by pzelasko** [comment]
You might want to try again in a fresh environment, sometimes these python packages leave artifacts behind or not everything uninstalls as you intended.

**Comment by eggplant95** [comment]
> BTW you might also need to uninstall `lilcom` because it seems to have been compiled against a specific numpy version.

I tried to install lilcom from the source code, and solve the problem.
Thanks for your reply :)
