### ISSUE TITLE
GPU/batch feature extraction

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#62]
As I notice, we are using torchaudio to extract features from raw waveform (according to here:https://github.com/pzelasko/lhotse/blob/master/lhotse/features.py#L122). 
But here are two potential issues with torchaudio, especially with torchaudio.compliance.kaldi:
- From my experiment, I found that these founctions can only work with CPU tensors (waveform). And in normal situations, we are most likely to put our data and model on GPUs and in that case this function will raise an error. (Haven't found any official document for this point and it would be great if someone can help me double check it).
- Waveform should be in shape (c, t) where c can only be in [0, 2) (https://pytorch.org/audio/compliance.kaldi.html#mfcc). In other words, it doesn't support batch level feature extraction and can only be used before you form a batch (e.g. in ```__getitem__```function). It would probably be OK in normal cases, but will make trouble if you'd like to do feature extraction outside dataset but in model forward instead.
As an alternative, ```torchaudio.transforms(torch.nn.Module)``` seems more flexible and we can even customize it as a normal ```nn.Module``` to fit with our user cases.
Please let me know how you think.
Thanks!

_Originally posted by @YiwenShaoStephen in https://github.com/pzelasko/lhotse/issues/44#issuecomment-667619856_

**Comment by pzelasko** [comment]
Dan's comments:

> Mm.
I wonder if it might make more sense to have the feature extraction as
python+PyTorch (or numpy?) code in lhotse itself?
The kaldi10feat project (on my github) may be something to refer to,
although it supports very little configuration.  It can't be made
compatible with current Kaldi features though, if that's a design criterion.
Dan

> ... conventionally, people do compute the features on CPU, and for the most
common use case we'll probably extract features and write them (compressed)
to disk.  But of course it would be nice to be able to do it on GPU, in
general.

**Comment by pzelasko** [comment]
AFAIK `torchaudio` "Kaldi compatibility" APIs indeed miss out on some features - I haven't tried to use the `torchaudio.transforms` yet, but maybe that would indeed solve both the GPU and batch feature extraction issues. I took a quick look at `kaldi10feat`, but it looks like it provides similar functionality as the current `torchaudio` based `fbank` extractor. I think we should consider our own implementation only if `torchaudio.transforms` turns out to be not good enough for some reason.

I think we already decided that we're not going to be fully compatible with Kaldi feature extractors so whatever we do, that should not be an issue.

**Comment by csukuangfj** [comment]
> But here are two potential issues with torchaudio, especially with torchaudio.compliance.kaldi:

> From my experiment, I found that these founctions can only work with CPU tensors (waveform). And in normal situations, we are most likely to put our data and model on GPUs and in that case this function will raise an error. (Haven't found any official document for this point and it would be great if someone can help me double check it).

When did you try this?

This pullrequest added GPU support to  `torchaudio.compliance.kaldi`

**Comment by pzelasko** [comment]
I'm closing this issue. At this time it falls out of Lhotse's scope, since we're using external libraries (currently, just Torchaudio) for feature extraction. We raised the issue about batch feature extraction with "Kaldi compliance" functions with the Torchaudio team and hopefully they'll address it. Anyway, it's possible to load the audio with Lhotse and use the external module of choice to extract features in a batch on the GPU.

**Comment by desh2608** [comment]
It seems that at the moment, if I want to perform batched feature extraction using GPUs, my only option is to use kaldifeat (or the S3PRL features, but that's a special case). Is this correct?

**Comment by pzelasko** [comment]
Yes. Although for some time I was thinking about adding the extract_batch support for Fbank and Mfcc (e.g., they could internally pad and unpad, or do whatever kaldifeat is doing).

**Comment by desh2608** [comment]
For Spectrogram and MFCC, it seems the corresponding [torchaudio.transforms](https://pytorch.org/audio/stable/transforms.html) support batched GPU-based extraction (since they are based on torch.nn.Module). Currently, the `Spectrogram` and `Mfcc` features in Lhotse use `torchaudio.compliance.kaldi`. One option would be to internally use the `torchaudio.transforms` if `extract_batch()` or `device="cuda"` is specified, else default to the Kaldi-compliant function. We can also completely switch to the transform version if no one complains.

**Comment by desh2608** [comment]
On looking around, I found some batch feature extractors defined in `lhotse/features/kaldi/layers.py` thanks to Jesus's implementation.
