### ISSUE TITLE
Probability for perturbs the speed of the recordings

### ISSUE THREAD

**Issue by drawfish** [lhotse-speech/lhotse#634]
If arguement of  `p`  is the  probability of perturbs the speed of the recordings, and as random.Random(None).random range from (0.0, 1.0), the code of this [line](https://github.com/lhotse-speech/lhotse/blob/04a288c9df1da31db5d1465f7ce71ec7f34705f9/lhotse/dataset/cut_transforms/perturb_speed.py#L35)
may need change from
```
   if self.random.random() >= self.p
```
to 
```
   if self.random.random() <= self.p
```

**Comment by csukuangfj** [comment]
Yes, I think your are correct.

**Comment by drawfish** [comment]
#635 Bug have fix in this PR.

**Comment by desh2608** [comment]
Good catch! It's funny how no one caught this before (perhaps because we were always just using `p=0.5`)!

**Comment by drawfish** [comment]
Bug had fixed and merged to master branch [here](https://github.com/lhotse-speech/lhotse/pull/635) , close this issue.
