### ISSUE TITLE
Duration in bucketing sampler

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#640]
We have a bucketing sampler like this:
```
            train_sampler = BucketingSampler(
                cuts_train,
                max_duration=300,
                shuffle=True,
                num_buckets=30,
                bucket_method="equal_duration",
                drop_last=True,
            )
```
and are getting OOM on a particular batch... printing out the batch details, it looks like the range of durations is particularly large, from 7.3 to 11.4.  This could be because it's in the right tail of the distribution of lengths of the dataset.  It seems the sum of durations is 299, but [longest-duration * num-cuts] is 399.
Perhaps it would make more sense to have the max-duration constraint apply to the longest-cut times max-duration?

**Comment by pzelasko** [comment]
Good idea. I’ll try to add it tomorrow.

**Comment by pzelasko** [comment]
Added in #653
