### ISSUE TITLE
Mismatch in number of samples between channels of `Recording`

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#671]
Currently, when creating a multi-channel`Recording` manually by specifying sources as different single-channel files (as is done in the AMI setup, for example), we do not strictly enforce the condition that all the channels must have the same number of samples. This can lead to errors later when calling `load_audio`:

```
Traceback (most recent call last):
  File "/export/c07/draj/lhotse/lhotse/utils.py", line 668, in wrapper
    return fn(*args, **kwargs)
  File "/export/c07/draj/lhotse/lhotse/audio.py", line 595, in load_audio
    audio = np.vstack(samples_per_source)
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/draj/anaconda3/envs/gss/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 28493142 and the array at index 8 has size 28491776
```

Perhaps we can add a `tolerance` parameter to `load_audio()` which would truncate all channels to the length of the shortest, provided they are not "too long" (as specified by the `tolerance` value, which can be set to 0 by default). If this sounds reasonable, I can create a PR with this addition.

**Comment by pzelasko** [comment]
I’d actually suggest the opposite — zero pad the shorter channels to the longest channel. You won’t lose data this way.

**Comment by desh2608** [comment]
Hmm, makes sense.

**Comment by desh2608** [comment]
Fixed in https://github.com/lhotse-speech/lhotse/pull/689.
