### ISSUE TITLE
Support ConcatDataset

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#674]
I am extracting the features for the GigaSpeech XL subset, which has 10k hours of data. After speed perturbing with factors 0.9 and 1.1, there are 30k hours of data. To avoid OOM during feature extraction, it is split into 2000 pieces.

The size of the manifest files after feature extraction is 42 GB
```
$ find data/fbank/XL_split_2000 -name "cuts_XL.*.jsonl.gz" -exec du -ch {}  + | grep total
42G     total
```

I am using `lhotse combine` to combine them into a single piece:
```
2022-04-16 11:07:25 (prepare_giga_speech.sh:144:main) Stage 6: Combine features for XL
```
It was started at 11:07. However, it is still not finished.
```
$ ls -lh data/fbank/cuts_XL.jsonl.gz
-rw-r--r-- 1 kuangfangjun root 27G Apr 16 21:40 data/fbank/cuts_XL.jsonl.gz
```

I am not sure hong long it will still take. 

There is a class `torch.utils.data.ConcatDataset` in PyTorch, is it possible to implement a similar one in lhotse so that
there is no need to combine them into a single manifest?

The following shows an exmaple of its usage in torchaudio:
https://github.com/pytorch/audio/blob/86100e387216227157598abc7ad5a28d63a7cf34/examples/asr/emformer_rnnt/librispeech/lightning.py#L181-L203
```python3
        dataset = torch.utils.data.ConcatDataset(
            [
                CustomDataset(
                    torchaudio.datasets.LIBRISPEECH(self.librispeech_path, url="train-clean-360"),
                    1000,
                ),
                CustomDataset(
                    torchaudio.datasets.LIBRISPEECH(self.librispeech_path, url="train-clean-100"),
                    1000,
                ),
                CustomDataset(
                    torchaudio.datasets.LIBRISPEECH(self.librispeech_path, url="train-other-500"),
                    1000,
                ),
            ]
        )
        dataloader = torch.utils.data.DataLoader(
            dataset,
            batch_size=None,
            collate_fn=self._train_collate_fn,
            num_workers=10,
            shuffle=True,
        )
```

**Comment by pzelasko** [comment]
Yeah, it's actually already there, all you need to do is use `lhotse.combine(load_manifest_lazy(p) for p in paths)`. You can also manually add them `cuts1 + cuts2`. It won't read them into memory. I was thinking about extending the existing methods to just accept a `Union[Pathlike, Sequence[Pathlike]]` for this to be more convenient.

**Comment by pzelasko** [comment]
.... you can also use `CutSet.mux(load_manifest_lazy(p) for p in paths)` if you want to randomize the examples a bit better (unless the shards already contain uniformly randomized data).

**Comment by csukuangfj** [comment]
> Yeah, it's actually already there, all you need to do is use `lhotse.combine(load_manifest_lazy(p) for p in paths)`. You can also manually add them `cuts1 + cuts2`. It won't read them into memory. I was thinking about extending the existing methods to just accept a `Union[Pathlike, Sequence[Pathlike]]` for this to be more convenient.

Thanks! This approach works very well.
