### ISSUE TITLE
Bug in assertion

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#676]
This syntax doesn't seem to do what is intended, it will always return true.
https://github.com/lhotse-speech/lhotse/blob/dc0c86bd498dd089b2165673d150b95bcbc0f768/lhotse/features/io.py#L827

**Comment by danpovey** [comment]
.. also I think "feats_mtx" should be "feats_mat" or feats_matrix.. .mtx is not obvious

**Comment by csukuangfj** [comment]
Perhaps it meant
```python3
assert mode in ("wb", "ab")
```

**Comment by pzelasko** [comment]
Thanks, fixed.
