### ISSUE TITLE
Error parsing position when calling feat extract-cuts

### ISSUE THREAD

**Issue by RuABraun** [lhotse-speech/lhotse#730]
So I think the slow training issue I have could be because I extracted features from the recordings, and the cuts (after trimming to supervision) actually only cover a significantly smaller subset of the recordings.

So I decided to re-extract the features with:
```
lhotse feat extract-cuts -f feat.config --storage-type lilcom_chunky -j 1 train.jsonl.gz train-feat.jsonl.gz feats
```
(on the side: setting `-j 1` results in a warning: "num_jobs is > 1 and torch's number of threads is > 1 as well [..] can result in a never ending computation [..] If this happens, use torch.set_num_threads(1)" which happens to me, not sure how im supposed to set the number of threads from the command line?)

This results in a repeated error:
```
trim: Error parsing position 1                                                                       
trim: usage: {position}
trim: Error parsing position 1                                                                       
trim: usage: {position}                                                                              
[...]
```

This output makes me think of sox, I did a grep in the codebase and found some usages via torchaudio but I'm confused why one would use sox here..

**Comment by pzelasko** [comment]
Can you post the full stack trace related to the trim error?

**Comment by pzelasko** [comment]
IIRC you mentioned importing a Kaldi data dir previously, right? Is it possible some cuts have recordings with audio sources of type `command` and `sox` is used inside a pipe (Kaldi-style)?

**Comment by pzelasko** [comment]
As a side note, when you use `lilcom_chunky` storage, it reads subsets of feature matrices corresponding to cut in a fairly efficient way (it stores blocks of ~6s worth of features next to each other, so for most utterances it's going to perform about two reads, instead of reading everything). So the previous approach should work OK for you with this storage backend.

**Comment by RuABraun** [comment]
re sox: thought that could be it but no, not the case, and I didn't have issues when extracting feats from the recordings

re lilcom: oooh okay. let me double check I was using the right feats during training

**Comment by RuABraun** [comment]
The error seems to be because of torchaudio, so I'm closing this (my version is nightly, I don't get the error when loading with an older version of torchaudio).
