### ISSUE TITLE
"'SupervisionSet' object has no attribute 'lazy'"

### ISSUE THREAD

**Issue by RuABraun** [lhotse-speech/lhotse#758]
When running `lhotse cut simple` I get the above error, which comes from [this line](https://github.com/lhotse-speech/lhotse/blob/f31aa5464c368d141a1ae57c1ba0aa5fe554c9ce/lhotse/bin/modes/cut.py#L56):
```
if all(m is None or m.lazy for m in (supervision_set, feature_set, recording_set)):
```

Looking at SupervisionSet I don't see an attribute `lazy`, so I guess there was a code change that removed it without also modifying the above code?

edit: I fixed it by putting `if False` so it goes into the non lazy branch and making `load_manifest_lazy_or_eager` always load non-lazily

**Comment by pzelasko** [comment]
Thanks, please check out https://github.com/lhotse-speech/lhotse/pull/759 for a fix.

**Comment by RuABraun** [comment]
nice, but without changing `load_manifest_lazy_or_eager` that still results in an error:
```
$ lhotse cut simple -r manifest_de_ch/mobi_test_import/recordings.jsonl.gz -f manifest_de_ch/mobi_test_import/feats/feature_manifest.json.gz -s manifest_de_ch/mobi_test_import/supervisions.jsonl.gz bla.jsonl.gz
[...]
  File "/home/rudolf/git/lhotse/lhotse/bin/modes/cut.py", line 68, in simple
    cut_set = CutSet.from_manifests(
  File "/home/rudolf/git/lhotse/lhotse/cut.py", line 3599, in from_manifests
    return create_cut_set_eager(
  File "/home/rudolf/git/lhotse/lhotse/cut.py", line 5589, in create_cut_set_eager
    cuts = CutSet.from_cuts(
  File "/home/rudolf/git/lhotse/lhotse/cut.py", line 3557, in from_cuts
    return CutSet(cuts=index_by_id_and_check(cuts))
  File "/home/rudolf/git/lhotse/lhotse/utils.py", line 566, in index_by_id_and_check
    for m in manifests:
  File "/home/rudolf/git/lhotse/lhotse/cut.py", line 5598, in <genexpr>
    recording=recordings[feats.recording_id] if rec_ok else None,
  File "/home/rudolf/git/lhotse/lhotse/audio.py", line 1149, in __getitem__
    return self.recordings[recording_id_or_index]
TypeError: 'LazyJsonlIterator' object is not subscriptable
```

**Comment by pzelasko** [comment]
I haven't tested it with a feature manifest input, I'll follow up on this.

**Comment by armusc** [comment]
same problem here, for the moment I just putting recordings=None when importing features from Kaldi
i don't understand because the type of recording is definitely "lhotse.audio.RecordingSet" which can be certainly accessed like a dict

**Comment by pzelasko** [comment]
Please check out https://github.com/lhotse-speech/lhotse/pull/763 and let me know if it helps.

**Comment by armusc** [comment]
it works, thanks
