### ISSUE TITLE
lhotse will download a new pytorch after I installed k2 by compilling with pytorch1.8.1

### ISSUE THREAD

**Issue by ahban** [lhotse-speech/lhotse#777]
I follow the steps in [icefall install page](https://icefall.readthedocs.io/en/latest/installation/index.html) to install k2 first (by compiling). When I move to install Lhotse by the recommend command as follows. However, the output of the install command tells me it is downloading a new version of PyTorch. Is this normal? Do we have to avoid this?
```
pip install git+https://github.com/lhotse-speech/lhotse
```

**Comment by csukuangfj** [comment]
Can you show the complete logs?

**Comment by ahban** [comment]
after i install LHotse by
```
pip install lhotse
``
and then run the following command, it will not remove my PyTorch anymore.

```
pip install git+https://github.com/lhotse-speech/lhotse
```
I also checked the version of PyTorch and Lhotse, they all are OK now.

**Comment by pzelasko** [comment]
If you’re still encountering any issues please post the full log. I’ll close the issue for now.
