### ISSUE TITLE
mismatched declared duration error when preparing AMI dataset

### ISSUE THREAD

**Issue by shaynemei** [lhotse-speech/lhotse#780]
Recordings and Supervisions files are generated using `load_kaldi_data_dir()`. The durations seem to be calculated [here](https://github.com/lhotse-speech/lhotse/blob/172e9f7a09e70cee4ee977fa9d288f96616cf7ec/lhotse/kaldi.py#L84) whereas the num_samples is calculated [here](https://github.com/lhotse-speech/lhotse/blob/172e9f7a09e70cee4ee977fa9d288f96616cf7ec/lhotse/kaldi.py#L100)

![snap 2022-07-25 at 6 12 37 PM](https://user-images.githubusercontent.com/31003116/181341777-67a5c574-9ee3-4c52-95ca-8ef27cdeb2f3.png)

OS: Ubuntu 20.04.3
lhotse: 1.4.0
python: 3.8.10

**Comment by pzelasko** [comment]
Hmmm a mismatch this small should be tolerated with the default threshold. Would you be willing to make a PR that uses this variable

https://github.com/lhotse-speech/lhotse/blob/dc5aa88b53adb73c20e3bf7210742ec3a25c809c/lhotse/audio.py#L68

as a threshold of tolerance in the following check (and maybe others in the same file):

https://github.com/lhotse-speech/lhotse/blob/dc5aa88b53adb73c20e3bf7210742ec3a25c809c/lhotse/qa.py#L213-L216

generally the check would be of the form `assert abs(duration1 - duration2) < LHOTSE_AUDIO_DURATION_MISMATCH_TOLERANCE`

**Comment by shaynemei** [comment]
PR opened here: https://github.com/lhotse-speech/lhotse/pull/781
