### ISSUE TITLE
torchaudio.sox_signalinfo_t is going to be deprecated.

### ISSUE THREAD

**Issue by mthrok** [lhotse-speech/lhotse#79]
Hi

torchaudio is perfoming overhaul on I/O and libsox binding. The detail is found [here](https://github.com/pytorch/audio/issues/903).
As part of this plan, in 0.9.0 release we plan to remove libsox class from API.

I looked at `lhoste` and it refers to `torchaudio. sox_signalinfo_t`. for example [here](https://github.com/pzelasko/lhotse/blob/3a34a9d34615a82913d24f9728cf33dae4a93032/lhotse/recipes/mini_librispeech.py#L42)
It is not immediately clear to me how this can be migrated, but torchaudio team is eager to help this project.
Please let us know what you think of torchaudio.

cc @dongreenberg @astaff @cpuhrsch @vincentqb

**Comment by pzelasko** [comment]
Thanks for the heads up! 

AFAIK the code you pointed to is currently the only usage of torchaudio to read audio/obtain audio file metadata in our codebase. We mostly rely on libsndfile (and python `SoundFile` wrapper) for loading audio otherwise. We'll update this recipe to do so as well.

@jimbozhang since you contributed the recipe, could you look into it?

Otherwise, we're using torchaudio for Kaldi-style feature extraction and so far it's working well for us.

**Comment by jimbozhang** [comment]
Thanks @mthrok's remainder. I think we need to update `torchaudio` to `>=0.9.0` and make `lhotse` compatible with it. I'll do this soon. @pzelasko

**Comment by pzelasko** [comment]
I don't think we actually need to bump the version - let our users have their choice if they want to use the older one. If we replace this usage of `sox_signalinfo_t` with `SoundFile` to read the audio metadata, it should work with any torchaudio version.

**Comment by mthrok** [comment]
> I don't think we actually need to bump the version - let our users have their choice if they want to use the older one. If we replace this usage of `sox_signalinfo_t` with `SoundFile` to read the audio metadata, it should work with any torchaudio version.

I looked at the code and sadly (for us), it seems that the right way is to replace `torchaudio` with `soundfile`. If you are going to create a recipe for a dataset with formats which `soundfile` does not support (such as `mp3` and `opus`), `torchaudio` supports it so let us know and we can help you.

**Comment by pzelasko** [comment]
I replaced the `torchaudio.info` use with `soundfile.info`. Thanks again for letting us know @mthrok!
