### ISSUE TITLE
.

### ISSUE THREAD

**Issue by yuyhee** [lhotse-speech/lhotse#796]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_xruhpqz/lilcom_b5ed43d70cbf49b9b0431692220d56e4/setup.py", line 15, in <module>
          from cmake.cmake_extension import BuildExtension, bdist_wheel, cmake_extension
      ModuleNotFoundError: No module named 'cmake.cmake_extension'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by csukuangfj** [comment]
What is your lilcom version?
