### ISSUE TITLE
Can we use lhotse on windows?

### ISSUE THREAD

**Issue by zw76859420** [lhotse-speech/lhotse#798]
Can we use lhotse on windows?

**Comment by pzelasko** [comment]
Yes.

**Comment by zw76859420** [comment]
Dear Pzelasko：
  When I use the command like 'pip install lhotse', the following error will appear:
------------------------
 LINK : fatal error LNK1104: 无法打开文件“build\temp.win-amd64-cpython-38\Release\Users\wzhangs\AppData\Local\Temp\pip-install-vrb8bum1\cython_b9e1ce40606543f286cf4f1e90c87c90\Cython\Plex\Scanners.cp38-win_amd64.exp”
        error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104
        [end of output]
-------------------------

Thanks,
Looking forward to your kindly reply

**Comment by csukuangfj** [comment]
From https://github.com/cython/cython/issues/3941

I think you can try
```bash
pip install --install-option="--no-cython-compile" lhotse
```

**Comment by zw76859420** [comment]
> From [cython/cython#3941](https://github.com/cython/cython/issues/3941)
> 
> I think you can try
> 
> ```shell
> pip install --install-option="--no-cython-compile" lhotse
> ```

Thanks Fangjun,
  We have successfully import lhotse, in which reference from https://zhuanlan.zhihu.com/p/302587005.

**Comment by pzelasko** [comment]
Great!
