### ISSUE TITLE
Split cuts to same duration

### ISSUE THREAD

**Issue by zeynepgulhanuslu** [lhotse-speech/lhotse#801]
Hi,

I want to split my dataset to equal durations and add custom noise. I plan to use it for speech enhancement task. Can I do that in lhotse? I tried to use BucketingSampler with equal duration but not seem to working for me. Also can we save cutset as a one audio file? 

`    sampler = BucketingSampler(cuts, max_duration=10, sampler_type=SimpleCutSampler,
                               bucket_method="equal_duration", drop_last=False)`

Thanks in advance

**Comment by pzelasko** [comment]
Welcome to Lhotse! 

> I want to split my dataset to equal durations and add custom noise. I plan to use it for speech enhancement task. Can I do that in lhotse? 

Yes, Lhotse should be useful for this. I would like to understand what do you exactly mean by "split my dataset to equal durations"?

> I tried to use BucketingSampler with equal duration but not seem to working for me. 

Please clarify: what was the result and what was the expected outcome?

> Also can we save cutset as a one audio file?

A CutSet is supposed to represent the full dataset, did you mean saving a mixed cut into a single audio file? It should be as easy as `cut.save_audio`; you can also do it for the full dataset using `cuts.save_audios`, e.g. 

```python
cuts = CutSet.from_file("clean_cuts.jsonl.gz").mix(noise_cuts).save_audios("mixed_audio")
cuts.to_file("noisy_cuts.jsonl.gz")
```

**Comment by zeynepgulhanuslu** [comment]
Thank you:) I will try to explain more.

I have a dataset of multiple files of 3-9 seconds. I want to split the data into equal parts of 10 seconds by combining them. Then I want to save those files as one wav file. After that, I will add some custom noise to clean audio files. As a result, 10 seconds of both noisy and clean data will be obtained.

I thought bucketingSampler will do the trick but it doesn't split data equal duration, for example one of the cutset is 6 seconds the other one is 8. Is it possible to divide the data into equal times?(even if it means we add to silence to end of the file.)

With BucketingSampler I divided commonvoice turkish data with max_duration 10. results are like below:

`--------------------

CutSet(len=2) [underlying data type: <class 'dict'>] 2
total duration: 9.432
--------------------

CutSet(len=2) [underlying data type: <class 'dict'>] 2
total duration: 7.392
--------------------
CutSet(len=1) [underlying data type: <class 'dict'>] 1
total duration: 5.208
--------------------`

I can use it like this but I need to complete it in 10 seconds by adding silence to the end. Also, I want to save the cutset of length 2 as an audio file. I think `cut.save_audio` method saves the audio files separately.

Thank you!

**Comment by pzelasko** [comment]
I see, I think I understand what you're trying to do. Can you try using `concat_cuts` transform on your full dataset CutSet with settings `cuts2 = concat_cuts(cuts, gap=0, max_duration=10)` and then use `cuts2.pad(duration=10).save_audios("mydata")`?

**Comment by zeynepgulhanuslu** [comment]
Thank you so much, it work like a charm:)

**Comment by RuABraun** [comment]
It would be nice for CutSet.split to have this feature, otherwise processing jobs will have very different processing times because the split cutsets can be very different in size.
