### ISSUE TITLE
Upsampling and mixed sampling rates

### ISSUE THREAD

**Issue by RuABraun** [lhotse-speech/lhotse#812]
It seems to me at the moment lhotse expects all samples to have the same sampling rate, and there is no capability for upsampling?

This breaks the earnings{21,22} datasets (they have files with different sampling rates), and seems to not make it possible for example upsample and extract 16k data from switchboard.

This could all be fixed with up/downsampling as necessary (as is possible in kaldi). Is this possible? I have searched around for upsampling in the issues and the code but have not found something.

**Comment by pzelasko** [comment]
You can call cuts = cuts.resample(16000), same with recordings. Ill try to think how to improve docs to make this easier to find, any suggestions?

**Comment by RuABraun** [comment]
Aaah that's my bad, I should have thought to search for resample in the code!

I guess one could add that info (that Cuts.resample exists) to the assertion error message [here](https://github.com/lhotse-speech/lhotse/blob/4a0436098291d9aa5243a053199738c1908ae90b/lhotse/features/kaldi/extractors.py#L68), not sure if that's the best approach though, I think one would have to copy that message to all the other feature extractors (so one gets the message with all feature types).

**Comment by pzelasko** [comment]
Yeah I guess it makes sense. A bit of copying probably doesn't hurt here. Do you mind contributing these messages?

**Comment by RuABraun** [comment]
Yup will do :)

**Comment by RuABraun** [comment]
made a PR #815
