### ISSUE TITLE
CutSet.trim_to_supervisions changes the start of all Supervisions to 0

### ISSUE THREAD

**Issue by teowenshen** [lhotse-speech/lhotse#813]
I am trying my luck on the csj corpus. It has a structure of multiple supervision segments corresponding to one long recording. I used the [CutSet.trim_to_supervisions](https://lhotse.readthedocs.io/en/latest/api.html#lhotse.cut.Cut.trim_to_supervisions) function so that one cut has exactly one supervision and one recording. 

So far, I managed to compute fbanks for this cutset, but I noticed that the `start` of all supervisions have been changed to `0` while the `start` of the cut object itself is inherited correctly from the supervision. This was a problem when I ran validate_manifest.py on my cut_set. 

Am I doing something wrong? I tried to find the implementation of trim_to_supervisions, but somehow in cut.py the _trim_to_supervisions_single and CutSet.trim_to_supervisions seem to point to each other for implementation. 

code: 
```python
cut_set = CutSet.from_manifests(
    recordings=manifest["recordings"],
    supervisions=manifest["supervisions"]
)

cut_set = cut_set.trim_to_supervisions(keep_overlapping=False)
```

cut_set before trimming: 
```json
  {
    "id": "S00M0079-0-0",
    "start": 0,
    "duration": 592.936375,
    "channel": 0,
    "supervisions": [
      {
        "id": "S00M0079_0001",
        "recording_id": "S00M0079",
        "start": 0.621,
        "duration": 5.763,
        "channel": 0,
        "text": "テーマ は です ね あまり 考える 時間 が なく 私 の 私 生活 と いう こと で",
        "language": "Japanese",
        "speaker": "S00M0079",
        "custom": {
      },
      {
        "id": "S00M0079_0002",
        "recording_id": "S00M0079",
        "start": 7.597,
        "duration": 2.665,
        "channel": 0,
        "text": "普段 何 を し てる か と いう の を 話そ う と 思い ます",
        "language": "Japanese",
        "speaker": "S00M0079",
      },
      ...
  }
```

cut_set after trimming: 
```json
  {
    "id": "c9c8596d-032b-4618-8e7e-67785a561d4a",
    "start": 0.621,
    "duration": 5.763,
    "channel": 0,
    "supervisions": [
      {
        "id": "S00M0079_0001",
        "recording_id": "S00M0079",
        "start": 0.0,
        "duration": 5.763,
        "channel": 0,
        "text": "テーマ は です ね あまり 考える 時間 が なく 私 の 私 生活 と いう こと で",
        "language": "Japanese",
        "speaker": "S00M0079",
      }
    ],
    "recording": {
      "id": "S00M0079",
      "sources": [
        {
          "type": "file",
          "channels": [
            0
          ],
          "source": "/mnt/minami_data_server/xx/corpus/csj/WAV/noncore/S00M0079.wav"
        }
      ],
      "sampling_rate": 16000,
      "num_samples": 9486982,
      "duration": 592.936375
    },
    "type": "MonoCut"
  },
  {
    "id": "498e385b-15c0-4138-9eda-44d2db26f6d7",
    "start": 7.597,
    "duration": 2.665,
    "channel": 0,
    "supervisions": [
      {
        "id": "S00M0079_0002",
        "recording_id": "S00M0079",
        "start": 0.0,
        "duration": 2.665,
        "channel": 0,
        "text": "普段 何 を し てる か と いう の を 話そ う と 思い ます",
        "language": "Japanese",
        "speaker": "S00M0079",
      }
    ],
    "recording": {
      "id": "S00M0079",
      "sources": [
        {
          "type": "file",
          "channels": [
            0
          ],
          "source": "/mnt/minami_data_server/xx/corpus/csj/WAV/noncore/S00M0079.wav"
        }
      ],
      "sampling_rate": 16000,
      "num_samples": 9486982,
      "duration": 592.936375
    },
    "type": "MonoCut"
  },
```

**Comment by pzelasko** [comment]
Your manifests look correct to me, can you post what was the error message from validation?

**Comment by teowenshen** [comment]
This is the error message:

>   File "/mnt/minami_data_server/t2131178/icefall/egs/csj/ASR/local/validate_manifest.py", line 67, in validate_supervision_and_cut_time_bounds
>     f"{c.id}: Supervision start time {s.start} is less "
> ValueError: 64e31244-d2e7-4d65-aea7-397dda123f42: Supervision start time 0.0 is less than cut start time 0.621

**Comment by pzelasko** [comment]
It should be OK to extract the features both before and after.

I don't think that check is necessary in your script `validate_manifest.py` -- it is perfectly OK for supervision's start to be smaller than cut's start.

As a side note, I think your recipe is based on an older version of Icefall -- we recommend using the JSONL format now (you can replace the last line with `cut_set.to_file(fbank_dir / f"cuts_{partition}.jsonl")`, and adjust `read_manifests_if_cached(..., suffix=jsonl)` as well)

**Comment by teowenshen** [comment]
Thanks! Also, would you say that the other check for end time is necessary too? 

```python
    if s.end > c.end:
        raise ValueError(
            f"{c.id}: Supervision end time {s.end} is larger "
            f"than cut end time {c.end}"
        )
```

Actually, just curious, are the start and end times in the supervision dict used/checked when extracting features? Or, are they based fully on the cut's start and end time only?

>  As a side note, I think your recipe is based on an older version of Icefall -- we recommend using the JSONL format now (you can replace the last line with cut_set.to_file(fbank_dir / f"cuts_{partition}.jsonl"), and adjust read_manifests_if_cached(..., suffix=jsonl) as well)

Thanks for the advice! Actually I changed it to json so that I could understand (what went wrong with) the contents of the manifests. I mean to switch it back after everything and run again.

**Comment by pzelasko** [comment]
For ASR it might be good to keep the check for ends, and also you don't want to have negative supervision start time -- these things are allowed in Lhotse because they indicate that a cut is smaller than a supervision. It makes sense to have data like this for some non-ASR tasks but not for ASR.

For feature extraction, the supervision information is ignored. You will need it to be sane at a later stage in a torch Dataset object that converts metadata into supervision tensors.

**Comment by pzelasko** [comment]
> The times in supervisions are relative to the start of the cut, right?

Yes. 

A longer answer is that before creating cutset they are relative to the start of recording, and after creating cutset they are relative to the start of the cut. This is to support mixed cuts where there are possibly multiple recordings. 

It also means the supervision can have a negative start, and it means it started before the cut (but is probably overlapping with it). It’s primarily useful for VAD and other segmentation tasks, less so for ASR (unless one uses alignments).

**Comment by teowenshen** [comment]
I have another question about the relation between cutset and supervision. 

If I decide to change anything inside the supervision or recording, for example the tokenisation method of the transcript text, I understand that I will need to regenerate the cuts.jsonl.gz. In that case, do I need to compute the fbanks again too? Otherwise, is there any way to avoid recomputing the fbanks?

Technically, the feature-related details are the same, like the wav_path, start, and duration, but there seems to be a 'key' variable which I notice changes during each round of feature extraction. 

I understand that in Librispeech the tokenisation is performed on-the-fly during training, but in my scenario the tokenisation method is static but somewhat intensive.

**Comment by pzelasko** [comment]
Generally after you extracted the features, you can modify most of the properties of cuts / jsonl file records any way you like (e.g. speaker labels, transcripts, etc.) and it will work well. Even if you e.g. truncate the duration, the features will also get truncated during loading. The "storage key" is generated randomly every time you extract features, so that's why you see it is changing.

**Comment by teowenshen** [comment]
Great! Thanks for your confirmations. 
I will close this issue now.
