### ISSUE TITLE
Cuts.shuffle().subset(first=1000)

### ISSUE THREAD

**Issue by jiay7** [lhotse-speech/lhotse#826]
If I want to randomly select a CutSet with less data, I prefer to add the "shuffle" option in CutSet.subset, rather than using the shuffle method first and then the subset method.

**Comment by pzelasko** [comment]
If it is an eager cutset, you can do `subset = cuts.sample(1000)`; if it's lazy, `cuts.shuffle.subset(first=1000)` is your best option (alternatively you can pre-shuffle with sth like `shuf` for better randomness)

**Comment by jiay7** [comment]
I see. Thank you for your prompt reply
