### ISSUE TITLE
[feedback requested] Dropping support for Python 3.6

### ISSUE THREAD

**Issue by pzelasko** [lhotse-speech/lhotse#828]
> Python 3.6.0
> Release Date: Dec. 23, 2016
> Note: The release you are looking at is Python 3.6.0, the initial feature release for the legacy 3.6 series which has now reached end-of-life and is no longer supported. See the [downloads page](https://www.python.org/downloads/) for currently supported versions of Python. The final source-only security fix release for 3.6 was [3.6.15](https://www.python.org/downloads/release/python-3615/) and the final bugfix release was [3.6.8](https://www.python.org/downloads/release/python-368/).

Source: https://www.python.org/downloads/release/python-360/

It would make my life a bit simpler (and less work in CI) if we drop the support for Python 3.6 in Lhotse 1.8 and onwards. Before doing that, I'd like to see if anybody in the community really needs Python 3.6 to be supported for some reason.

**Comment by csukuangfj** [comment]
+1

We have already dropped Python 3.6 support in [sherpa](http://github.com/k2-fsa/sherpa).
