### ISSUE TITLE
Whisper workflow supervision `end` may be incorrect

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#839]
So I ran the model on one of the AMI headset recordings (~5000s) and it seems like the "end" actually shows the end of the segment, not the duration. Here is the JSON containing the `results["segments"]`: https://drive.google.com/file/d/169igkcDY2SmMs5k3hOhHip89T4MQDnKs/view?usp=sharing

_Originally posted by @desh2608 in https://github.com/lhotse-speech/lhotse/pull/834#discussion_r988376898_

**Comment by pzelasko** [comment]
That might explain why I was getting weird results that needed the truncation post processing step. Thanks for finding the issue! I'll fix it.
