### ISSUE TITLE
Supporting multiple transcripts

### ISSUE THREAD

**Issue by teowenshen** [lhotse-speech/lhotse#843]
I have a particular situation where there are multiple versions of the same transcripts for the same supervision. In my case, the transcripts vary in [disfluent](https://ieeexplore.ieee.org/document/9689539) [notation](https://arxiv.org/pdf/2012.06259.pdf), but I imagine this would be helpful for [pluricentric languages](https://en.wikipedia.org/wiki/Pluricentric_language) too. 

My supervision looks like this. 
```json
{
    "id": "A04M0051_0020",
    "recording_id": "A04M0051",
    "start": 45.953,
    "duration": 0.8979999999999961,
    "channel": 0,
    "text": "",
    "language": "Japanese",
    "speaker": "A04M0051",
    "custom": {
      "fluent": "で",
      "disfluent": "で えー",
      "number": "で",
      "symbol": "で ＃"
    }
} 
```

I introduced a `self.transcript_mode` attribute in `K2SpeechRecognitionDataset` that defaults to `None`. It changes the behaviour of `__getitem__` to retrieve the transcript in `custom` instead of `text`. In my codes, `transcript_mode` is exposed as an `argparse` argument and passed into the constructor of `K2SpeechRecognitionDataset`, both in `asr_datamodule.py`. 

From:
https://github.com/lhotse-speech/lhotse/blob/0577bb703a4508b4d680b67d197762d974f278b2/lhotse/dataset/speech_recognition.py#L133-L144

To:
```python
batch = {
    "inputs": inputs,
    "supervisions": default_collate(
        [
            {
                "text": supervision.custom[self.transcript_mode] if self.transcript_mode else supervision.text,
            }
            for sequence_idx, cut in enumerate(cuts)
            for supervision in cut.supervisions
        ]
    ),
}
```

In my case, it allows me to access the different transcripts in the same `cuts_XX.jsonl.gz` file without returning the entire cut during iteration or creating multiple `cuts_XX.jsonl.gz` for each transcript version. However, I understand that this function probably won't be useful in most other cases, since datasets seldom have more than one version of transcript.
 
What do you think?

**Comment by pzelasko** [comment]
Thanks for sharing! It looks like you were able to handle this case with only minor modifications to the torch Dataset class. This is a good example of how I intended cases like these to be handled. Since it's a feature that seems very specific to your use-case, I would rather not pull these modifications into Lhotse.

**Comment by teowenshen** [comment]
Okay sure, thanks for your consideration! I will put my modifications outside of the Lhotse core codes.
