### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#88]
Hi, we are very interested in this project (willing to contribute) as it aligns well with our own plans for ASR datapipelines. 
However, we do not want to start integrating Lhotse until there is a stable version.
Is there a firm release date for a stable version of this project, or at least a realistic timeline and when a stable api will be released?
What features need work so that this project can be released soon?

Regards
Jan Vainer

**Comment by pzelasko** [comment]
Hi Jan! I well understand the desire to wait for a stable version. This is somewhat dependent on:
- the K2 release date, as we want to make absolutely sure the two libraries play together very well;
- putting Lhotse to use in at least a couple of recipes to test it through in a full ML pipeline and polish the rough edges.

Dan is envisioning a very basic K2 version sometime by the end of October; a more feature-rich K2 version in the horizon of the next ~6 months. I expect Lhotse to become reasonably stable sometime between these to milestones.

Frankly, I don't expect major changes in `RecordingSet`, `SupervisionSet` and `CutSet` (other than new features and maybe minor renamings/refactorings). `FeatureSet` and feature extraction should be ok, might be extended at some point to support concatenation of multiple types of features (there's a chance the changes won't be breaking). The `Dataset` classes might undergo some transformations once we gather them for more types of tasks - that will put more things into perspective, like what are the common parts that it makes sense to abstract away (if any).

At this point, we could use some help with adding "recipes" for new corpora (either small or large) - the more we get, the clearer it becomes if we're missing any major features. I intend to create a guide for how to add new corpora sometime in the next few days.

@danpovey any thoughts?

**Comment by LordOfLuck** [comment]
Hi, thanks for the answer. Adding some guides for extending this project (also including directions of future functionality) would be veru useful to us. We might start working on additional corpora recipes in next two weeks or so. We are also going to be implementing blob storage option blockwise dataloading during training in the future. I saw several issues regarding this topic here - using petastorm or HDF5 and so on. What is the state and direction of this feature?

**Comment by danpovey** [comment]
Great!
Regarding additional protocols for data loading, yes, we want to implement
that.  the conditions are basically:
  - should be modular and should ideally not bulk up the library with
dependencies when they are not needed
    (e.g. could try dynamic loading of modules, and instruct the user how
to install the dependencies only when they are needed?)
 - each new protocol would be associated with a different identifier, Piotr
can give details but it's things like 'file', I think,
  that dictate the protocol.
Dan

**Comment by pzelasko** [comment]
Regarding blob storage - I don't think there is a single universal best solution, so we'll enable multiple storage backends, both for recordings and features. They will likely be optional dependencies, installable like `pip install lhotse[hdf]`, and imported locally in relevant functions. For `Recording`, the the protocol can be put in the `AudioSource.type` field; for `Features` in `Features.storage_type` field (then `AudioSource.source` and `Features.storage_path` can be used for protocol-specific keys, e.g. location/indices in hdf5 table). The code will need minor (?) extensions but I don't expect API changes because of that.

**Comment by pzelasko** [comment]
FYI There has been some progress lately, we merged initial HDF5 support today (#92) and I've added some general improvements + guide on adding new corpora (#95, soon to be merged). If you're looking to contribute something let me know.

**Comment by LordOfLuck** [comment]
@pzelasko Awesome, thank you! I will check out the HDF5 support and will discuss contributing to the corpora recipes with my co-workers.

**Comment by johnjosephmorgan** [comment]
> @pzelasko
I used the example mini_librispeech recipe to port the heroico data prep perl scripts from kaldi to lhotse python.

> I got it to run, but I don't have permission yet to make a pr and push it to the repo.
Should I look at a newer recipe to take advantage of recent updates?
Where is the contributor's guide?
Thanks,
John

**Comment by pzelasko** [comment]
Check out https://lhotse.readthedocs.io/en/latest/corpus.html#adding-new-corpora for a guide on adding new recipes.

**Comment by danpovey** [comment]
Regarding pull requests: you wouldn't push anything to the repo itself.
The way this is done on Github is, you fork the project
(using the button on github), then when you want to make a change you push
to a branch on your fork, and create the pull request
using that as the head.

**Comment by pzelasko** [comment]
The initial release is here 🎉
