### ISSUE TITLE
Default line-length of Lhotse and Icefall

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#890]
@pzelasko @csukuangfj 

This is more of an inconvenience than an issue. Lhotse uses a pre-commit hook with the default line length for Black (which is 88 characters), while Icefall uses a modified line length of 80. So simultaneously working on both can be a hassle (since I set Black format on auto-save settings in VSCode, for example). Would it make sense to perhaps decide on one setting?

Alternatively, do you know how to set different line-length configs for different projects?

**Comment by csukuangfj** [comment]
Please have a look at
https://github.com/k2-fsa/icefall/blob/master/.pre-commit-config.yaml#L6
and
https://github.com/k2-fsa/icefall/blob/master/pyproject.toml#L6

If you also change the above files in lhotse, it should work.

**Comment by pzelasko** [comment]
Is there a reason to use non default 80 characters per line? I thought it’s an artifact of the old days when terminal screens would not be able to physically display more. Multiple sources recommend 90-ish as the best number for Python due to its indentation requirements (see https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length and links there).

**Comment by csukuangfj** [comment]
The google python code style says:
https://google.github.io/styleguide/pyguide.html#32-line-length
<img width="1129" alt="Screen Shot 2022-11-14 at 12 39 48 PM" src="https://user-images.githubusercontent.com/5284924/201576575-31eeacb9-7272-4910-82d8-fdd9e044af3b.png">


Also, google c++ code style says:
https://google.github.io/styleguide/cppguide.html#Line_Length

>Each line of text in your code should be at most 80 characters long.

So we choose 80 for both C++ and Python.

**Comment by desh2608** [comment]
Let me clarify the problem a bit further. I use VSCode for development (as do many other people, I believe), and you can configure "workspace" level settings, for example, to apply Black formatting on save. This means that if I am working on something that involves both Lhotse and Icefall, I face the following problem:
* Setting Black formatter to 88 would cause icefall pre-commit conflict since lines would be longer than 80 characters.
* Setting it to 80 would re-format existing code in Lhotse (if I am making changes to an existing file), and introduce lots of unnecessary code changes in the PR.
I can think of 2 workarounds:
1. Develop with a line-length of 88, and then re-format icefall code to have line length 80 at the time of commit.
2. Put both Lhotse and icefall in different workspaces with separate config.
Both of these solutions are quite "clunky", though.

**Comment by danpovey** [comment]
If we change icefall to 88, will it reformat everything and ruin the history?

**Comment by desh2608** [comment]
It seems there's a way to avoid that: https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html

**Comment by pzelasko** [comment]
> It seems there's a way to avoid that: https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html

I did it once with lhotse when I first introduced black formatting (https://github.com/lhotse-speech/lhotse/blob/master/.git-blame-ignore-revs).

I agree we should have a common setting for these projects, and I'm hoping @danpovey and @csukuangfj can be convinced to adopt 88. I find black's motivation and research for this setting more convincing than Google's (they don't provide it?).

**Comment by csukuangfj** [comment]
> I'd be fine with 88, as I think 80 is a bit short. [I hope it doesn't reformat too much, though, because the ignore-revs solution seems a lot of effort.]

88 is also fine with me.

**Comment by desh2608** [comment]
Since I brought up the issue, I am willing to make a PR for the style change. @pzelasko could you point me to the corresponding Lhotse PR where you made the change, and anything specific that you remember I should be aware of?

**Comment by pzelasko** [comment]
This is the relevant PR: https://github.com/lhotse-speech/lhotse/pull/420

Basically follow the guide from `black` that you posted previously. Make sure not to squash the PR when merging because that would change git history and invalidate the commit hash in the `.git-blame-ignore-revs` file.

**Comment by desh2608** [comment]
Resolved by https://github.com/k2-fsa/icefall/pull/690.
