### ISSUE TITLE
Length mismatch between tensor batch['inputs'] and maximum of cut lengths in batch

### ISSUE THREAD

**Issue by kfmn** [lhotse-speech/lhotse#904]
Hi,

I am trying to use librispeech recipe for pruned_transducer_stateless for my dataset.
I have Kaldi data folder for my dataset with a segments file in which there are several segments per single recording.
I used `lhotse kaldi import` and made RecordingSet and SupervisionSet jsons, which then were used to compute fbanks and create CutSet for train, valid and test subsets.
First, I've found that script validate_manifest.py fails on my CutSets since it requires only a single supervision per cut which is not true for my data. I have manually splitted each of such "multiple" cuts into many "single" ones. I don't know if this requirement is substantial for training, please explain.

Then I tried to run training and found that it also fails, but the reason is different. When batch is created based on provided cuts, the length of tensor batch['inputs'] is a maximum of all cuts' durations, but lengths of segments themselves are got from supervisions' durations. And this is a mismatch since I have some supervisions which don't span a whole cut durations. As a result I have an Assertion failed: 
```

  File "./pruned_transducer_stateless4/conformer.py", line 162, in forward
    assert x.size(0) == lengths.max().item(), (x.size(0), lengths.max().item())

```
Indeed I have a cut of the duration 20 seconds with a short supervision of duration 3 seconds inside it, and several other cuts of lengths 19, 18 and 16 seconds. So the features tensor has lengths 2000 frames while lengths are [300, 1900, 1800, 1600] so 2000 != 1900 causes Assertion above failed.

Please explain what I do wrongly and advice how to overcome this issue

Thanks a lot, Maxim

**Comment by desh2608** [comment]
It may be better to start off from a recipe such as Tedlium which is similar to your dataset --- in the sense that there are multiple utterances per recording. The key here is to call `CutSet.trim_to_supervisions(keep_overlapping=False)` after creating cuts from the recordings and supervisions, so that you get 1 cut per supervision, which is required for training the ASR model.

**Comment by kfmn** [comment]
Hi, Desh

Thank you very much for your answer. This definitely solves my issue!

By the way, when using trim_to_supervisions to split multiple supervisions into separate cuts, these supervisions' start time is set to zero. And this causes assertion fail in librispeech's manifest validation script which checks that supervision start time is larger than that of cut itself. But this is just a remark...

Thanks again,
Maxim

**Comment by desh2608** [comment]
I'm not sure about the specifics of the librispeech recipe, but that assertion shouldn't be there I think. When a supervision is attached to a cut, the supervision's start time is changed to be w.r.t the cut start time.
