### ISSUE TITLE
Add type checking for dataset_parts param of recipes.utils.read_manifests_if_cached

### ISSUE THREAD

**Issue by trunglebka** [lhotse-speech/lhotse#910]
It look like the expected dataset_parts is a list/set... (a sequence).  However `str` is a sequence too and in case  that user pass a dataset part name (not in a list/set/... - by mistake) it is likely that the cache will be missed.
I've encountered this behavior when preparing gigaspeech (from huggingface) myself and try to find cached dataset by it name like `prepare_subset_manifest("XL"...)` - this take several hours to rebuild. So I think that it would be better if we add a check and if user pass dataset_parts as a string, we can raise an exception or convert it to a list. Something like:
```
def read_manifests_if_cached(
    dataset_parts: Optional[Sequence[str]],
    output_dir: Optional[Pathlike],
    prefix: str = "",
    suffix: Optional[str] = "jsonl.gz",
    types: Iterable[str] = DEFAULT_DETECTED_MANIFEST_TYPES,
    lazy: bool = False,
) -> Optional[Dict[str, Dict[str, Union[RecordingSet, SupervisionSet]]]]:
    if isinstance(dataset_parts, str):
        dataset_parts = [dataset_parts]
```

**Comment by pzelasko** [comment]
Sounds good! Can you make a PR with the relevant changes?

**Comment by trunglebka** [comment]
sorry for missing this, I have one question to make a PR.
Do I need to create test for this function since it is in recipe module?

**Comment by desh2608** [comment]
@trunglebka The "recipe" directory is expempt from codecov, but having unit tests for commonly used functions doesn't hurt, so would be great if you could add a test :)
