### ISSUE TITLE
Mismatch between number of samples and the actual length of my audio file

### ISSUE THREAD

**Issue by mrezasoltani** [lhotse-speech/lhotse#913]
Hi,

I am simply using recording = Recording.from_file("myaudiofile.wav") for myaudiofile.wav file, which has a 54.4 second duration with 8khz Samling rate. What I get from the recording is as follows:

recording.to_dict()
{'id': 'myaudiofile',
 'sources': [{'type': 'file',
   'channels': [0],
   'source': 'myaudiofile.wav'}],
 'sampling_rate': 8000,
 'num_samples': 2147483647,
 'duration': 268435.455875,
 'channel_ids': [0]}

Also, when I run samples = recording.load_audio(), I get the following error:

The number of declared samples in the recording diverged from the one obtained when loading audio (offset=0.0, duration=None). This could be internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=2147048447, audio.shape=(1, 435200), recording=Recording(id='myaudio', sources=[AudioSource(type='file', channels=[0], source='myaudiofile.wav')], sampling_rate=8000, num_samples=2147483647, duration=268435.455875, channel_ids=[0], transforms=None)
[extra info] When calling: Recording.load_audio(args=(Recording(id='myaudiofile', sources=[AudioSource(type='file', channels=[0], source='myaudiofile.wav')], sampling_rate=8000, num_samples=2147483647, duration=268435.455875, channel_ids=[0], transforms=None),) kwargs={})

What is going on here?

When I load my file using torchaudio, everything is as expected:
wav, sr = torchaudio.load("myaudiofile.wav")
wav.shape, sr

(torch.Size([1, 435200]), 8000)

**Comment by pzelasko** [comment]
Hmm, I wonder how did you get a duration of `268435.455875` seconds in your manifest. Can you print out the contents of `info` in `lhotse/audio.py` in line 1761 when calling `Recording.from_file`? It looks like it's getting this duration/num_samples directly from torchaudio.

**Comment by mrezasoltani** [comment]
Thanks for the reply. This is the info from the following:

info = torchaudio.info("myaudiofile.wav")
AudioMetaData(sample_rate=8000, num_frames=2147483647, num_channels=1, bits_per_sample=16, encoding=PCM_S)

**Comment by pzelasko** [comment]
Most likely your WAVE file has a corrupted header with wrong metadata. I don't think we can really support these cases, but actually you could get away with `Recording.from_file(path, force_read_audio=True)` which is going to read the whole file instead of querying the metadata. I would advise to figure out why the metadata is incorrect in the first place though.

**Comment by mrezasoltani** [comment]
> 
Thanks for your info. Does this not violate the lazy reading of the files? I mean since this reads the whole file, it may slow down the process of preparing datatset from a large set of audio file, am I right?

**Comment by pzelasko** [comment]
Yes, they would not be read lazily anymore.

**Comment by mrezasoltani** [comment]
> Yes, they would not be read lazily anymore.

Thanks for your help.
