### ISSUE TITLE
Kaldi data directory with feats.scp only

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#921]
Dear developers,

Is it possible for Lhotse to import Kaldi format data directory with feats.scp instead of wav.scp?

Best Regards,
Jin

**Comment by pzelasko** [comment]
Yes, use `lhotse kaldi import -f <frame-shift-in-seconds> DATA_DIR SAMPLING_RATE MANIFEST_DIR`. The `-f` argument is the key here.

**Comment by JinZr** [comment]
Thanks!
