### ISSUE TITLE
Using forced alignment for segmentation

### ISSUE THREAD

**Issue by lubacien** [lhotse-speech/lhotse#923]
Hello,

I have a dataset made of short utterances spaced with long silences, but no start and duration information about the segments. Therefore I create supervision segments which last the full duration of my recordings and with long transcriptions.

example:
audio: ----hello---(20s silence)---yes---(10s silence)---no---
transcription: HELLO YES NO
start: 0s
end: 35s

I can calculate the forced alignment, for example using the "align_with_torchaudio" workflow or adding an external ctm file, but is there a way to then use these alignments to create a segmented version of my data?
 
The goal would be to obtain 3 supervision segments, something like:
transcription: HELLO
start: 0s
end: 1s
transcription:YES
start: 21s
end: 22s
transcription: NO
start: 32s
end: 33s

 thanks

**Comment by desh2608** [comment]
I needed this function for my own work, so I went ahead and added it. It would be great if you could help test it out.

**Comment by lubacien** [comment]
thanks! i'll take a look
