### ISSUE TITLE
How does lhotse mix audios?

### ISSUE THREAD

**Issue by ncakhoa** [lhotse-speech/lhotse#931]
Hi.
When lhotse mixes two audios, could it load features which already computed and saved on disk, then mix them, or it **has to** mix two waveform, then compute feature of the mixed audio.

**Comment by desh2608** [comment]
This depends on the kind of features used. Lhotse features are derived from a base `FeatureExtractor` class (see [here](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/features/base.py)) that defines a `mix()` method. This method implements how feature-level mixing is supposed to be performed for this feature type. If you want to mix audios with their features, this method needs to be implemented for your feature type.

In the icefall ASR recipes, for example, we use fbank features, for which the mix() method is implemented [here](https://github.com/lhotse-speech/lhotse/blob/891bad12f88f3f6cb666fdad83233008da61084c/lhotse/features/kaldifeat.py#L192). As such, you would find in the recipes that we often extract features for the dataset and for MUSAN noises separately, and then mix them on-the-fly [during training](https://github.com/k2-fsa/icefall/blob/65d7192dca03ba21bff4270add3891c9730491a7/egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py#L223).

**Comment by desh2608** [comment]
I'm closing this issue. Please let us know if this didn't answer your question.
