### ISSUE TITLE
Create new cuts for overlapped supervisions in  `trim_to_supervisions` 

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#949]
When calling `cuts.trim_to_supervisions(keep_overlapping=False)`, the result is that overlaps are discarded. When calling 
`cuts.trim_to_supervisions(keep_overlapping=True)`, all is preserved, but a cut can have more supervisions.
Could we have an option that would create new cuts for the overlapped supervisions that would otherwise be discarded? This way we would end up with possibly overlapping cuts with single supervision each. It can be super useful for MultiCuts, where some crosstalk happens. If the supervisions are routed to correct channels, we can eg. evaluate each supervision segment with an ASR correctly (feeding correct channel to it).

**Comment by desh2608** [comment]
I think what you are referring to is actually how `cuts.trim_to_supervisions(keep_overlapping=False)` works. It creates 1 cut per supervision segment, but overlapping supervisions are not kept for the cut. For example, consider the following illustration from the function docstring:

```
        For example, the following cut::

                    Cut
            |-----------------|
             Sup1
            |----|  Sup2
               |-----------|

        is transformed into two cuts::

             Cut1
            |----|
             Sup1
            |----|
               Sup2
               |-|
                    Cut2
               |-----------|
               Sup1
               |-|
                    Sup2
               |-----------|
```
If we specify `keep_overlapping=False`, it would discard ``Sup2`` in ``Cut1`` and ``Sup1`` in ``Cut2``. But Cut1 and Cut2 are still overlapping, and have exactly 1 segment each.
