### ISSUE TITLE
MonoCut change  features.storage_path and save new jsonl.gz file

### ISSUE THREAD

**Issue by CuiDonCai** [lhotse-speech/lhotse#964]
as title describe, I want to change feature store path, is there a way change it and save to file? 
python script or lhost command is fine.

```
   cuts = CutSet.from_file(cut_dir)
    for cut in cuts:
        cut.features.storage_path = new_path
```
how does it save to file after changed values?

**Comment by CuiDonCai** [comment]
@desh2608

**Comment by CuiDonCai** [comment]
I know `with_features_path_prefix` method  can meet my demand. if the more powerful need, you can be try `fastcopy`.

**Comment by desh2608** [comment]
I think `fastcopy` may be required. After you have modified the cut manifest, you can then just save to disk using `to_file()`. Maybe @pzelasko has a better solution.

**Comment by CuiDonCai** [comment]
> I think `fastcopy` may be required. After you have modified the cut manifest, you can then just save to disk using `to_file()`. Maybe @pzelasko has a better solution.

thanks.
