### ISSUE TITLE
Loudness normalisation

### ISSUE THREAD

**Issue by saveli** [lhotse-speech/lhotse#966]
Is there a way to do audio normalisation on-the-fly on file-level (`Recording.from_file()`) using `AudioTransform`?

Reason is, when using `annotate_with_whisper` in `SupervisionSegment` sometimes `alginment=None` despite `text` being not `None`.
After normalising the file manually (ffmpeg & loudnorm), the error was gone.

Hence, it is still loud enough for whisper to find text (speech prob > no speech threshold), but alignment fails.

**Comment by desh2608** [comment]
@saveli you can consider adding https://github.com/csteinmetz1/pyloudnorm as an optional dependency and using their methods for normalization.

**Comment by saveli** [comment]
@pzelasko I'm not that firm in lhotse's data processing behind the scenes. You would have to do a 2-pass (find peak & adjust volume) loudness normalisation.

Therefore, for now I will use @desh2608 suggestion, thanks.
