### ISSUE TITLE
Loading audio files from S3 AWS

### ISSUE THREAD

**Issue by mrezasoltani** [lhotse-speech/lhotse#981]
Hi, I have created a a cutset for my own dataset. The actual audio wav files are in a S3 bucket. However, when I try to use this cutset in a dataloader, I get an error for "No such file or directory:". The audio files exist in the S3 bucket, and I can verify it by downloading them using boto3:

> client = boto3.client("s3")
>  bucket = "my_bucket"
>  prefix = "some_folder/xxxx.wav"
>  client.download_file(bucket, prefix, local_path).

However, I cannot use them through my dataloader. This is my Recording structure:

> Recording(
>             id = record_id,
>             sources = [
>                 AudioSource(
>                     type='url', 
>                     channels = [0],
>                     source = os.path.join("my_bucket/some_folder", xxxx.wav)
>                 )
>             ],
>             num_samples = compute_num_samples(duration=Seconds(record_duration), sampling_rate=sr),
>             sampling_rate = sr,
>             duration = record_duration
> )

I have already installed smart_open[s3].

Can you please help me?

Thanks

**Comment by pzelasko** [comment]
You need to make sure the source is in the following format: `s3://my-bucket/my-file.wav`

**Comment by mrezasoltani** [comment]
Thanks
