### ISSUE TITLE
load_kaldi_data_dir with segments

### ISSUE THREAD

**Issue by yasumori** [lhotse-speech/lhotse#987]
Hello, when loading a kaldi data dir including `feats.scp` and `segments` into CutSet, what would be the best approach?

I used `lhotse.kaldi.load_kaldi_data_dir` to load a kaldi data dir into `recordings`, `supervisions` and `features`, and then creating a CutSet from `CutSet.from_manifests` fails to find a supervision corresponding to each cut. 

Since each supervision inherits its start time from kaldi `segments`, `create_cut_set_eager` cannot match supervisions with their corresponding cut: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/cut/set.py#L2894-L2899

I got around this by forcing a supervision start and duration to be cut start and duration, but I'm sure there is a cleaner approach to doing this, or I'd appreciate it if you could let me know if I'm missing a better way to load features and supervisions from kaldi data dir.

I'll leave my workaround way to load a kaldi data dir.

``` python
recs, sups, feats = lhotse.kaldi.load_kaldi_data_dir(
        args.kaldi_dir,
        sampling_rate=args.sampling_rate,
        frame_shift=args.frame_shift,
    )

# here, matching supervisions with cuts fails
cutset = lhotse.CutSet.from_manifests(
        recordings=recs,
        supervisions=sups
        features=feats,
    )

sup_dict = {}
for sup in sups:
    sup_dict[sup.id] = sup

for cut in cutset:
    storage_key = cut.features.storage_key
    # match supervision with cut by features.storage_key
    supervision = sup_dict[storage_key]
    # if duration is too different between supervision cut,
    # something wrong is happening
    sup_dur = supervision.duration
    if sup_dur - cut.duration > 0.05:
        raise ValueError("supervision duration and cut duration is too different.")

    # discard supervision.start inheritated from segments
    # and assign cut.duration and cut.start to supervision
    supervision.duration = cut.duration
    supervision.start = cut.start

    cut.supervisions.append(supervision)
```

**Comment by pzelasko** [comment]
The issue seems to be that `load_kaldi_data_dir` has hardcoded `start=0` when it creates `Features` manifests. Technically that code should use the `start` time of the segment corresponding to a given feature matrix. Would you be interested in making a PR with these changes? (CC @jtrmal @desh2608 FYI since you were also using Kaldi import thing).

**Comment by jtrmal** [comment]
nice catch
y.

**Comment by yasumori** [comment]
> Would you be interested in making a PR with these changes? (CC @jtrmal @desh2608 FYI since you were also using Kaldi import thing).

Sure, I'm happy to contribute
