### ISSUE TITLE
Bucketing sampler drops some cuts 

### ISSUE THREAD

**Issue by mrezasoltani** [lhotse-speech/lhotse#990]
Hi,

I am aware of related issues reported on bucketing sampler, ddp, and missing cuts. However, still I am experiencing this issue. This is my problem:

I am using DynamicBucketingSampler with some finite and even with inf duration (by setting a batch size) for my dataloader creation. I have a very large set of audio files, in which I am testing an ASR model for just transcribing(inference only and no training). In particular, a long call, including many cuts can have its constructing cuts in different batches and handled with different GPUs (I am using ddp with single/multi node with different number of GPUs per node). So, once all calculations are done, I need to gather all results from all GPUs, so I can run a decoding function to sort and merge correct cuts to produce a valid long call. However, it seems some cuts are being missed and  one or some processes hang, so I need to terminate them manually. When I dug into it, I figured out, for example, the gathered results are coming from the batch one before the last batch since one of the processes has finished its job; however, other processes (in this example, there are 4 gpus and one node), seem to have more cuts to add. Indeed this is the case since in the last batch, those remaining 3 gpus have the complete list of cuts. However, since the results are returned back from not the last batch (for those 3 GPUs), I missed some cuts, so some long calls have incomplete transcriptions (due to the missed cuts). It is worth to mention that I use dist.all_gather_object to gather my results from all processes (my results are not tensor, they are dictionaries, so I needed to use this function).

Could you please help me on this ?

Thanks

**Comment by pzelasko** [comment]
You might want to check out `Join` context manager in PyTorch to allow uneven number of batches for each GPU, check out the following tutorial: https://pytorch.org/tutorials/advanced/generic_join.html

**Comment by mrezasoltani** [comment]
> You might want to check out `Join` context manager in PyTorch to allow uneven number of batches for each GPU, check out the following tutorial: https://pytorch.org/tutorials/advanced/generic_join.html

Thanks.
